<?php

/*
  --------------------------------------------------------------------------
  GAzie - Gestione Azienda
  Copyright (C) 2004-2024 - Antonio De Vincentiis Montesilvano (PE)
  (http://www.devincentiis.it)
  <http://gazie.sourceforge.net>
  --------------------------------------------------------------------------
  Questo programma e` free software;   e` lecito redistribuirlo  e/o
  modificarlo secondo i  termini della Licenza Pubblica Generica GNU
  come e` pubblicata dalla Free Software Foundation; o la versione 2
  della licenza o (a propria scelta) una versione successiva.

  Questo programma  e` distribuito nella speranza  che sia utile, ma
  SENZA   ALCUNA GARANZIA; senza  neppure  la  garanzia implicita di
  NEGOZIABILITA` o di  APPLICABILITA` PER UN  PARTICOLARE SCOPO.  Si
  veda la Licenza Pubblica Generica GNU per avere maggiori dettagli.

  Ognuno dovrebbe avere   ricevuto una copia  della Licenza Pubblica
  Generica GNU insieme a   questo programma; in caso  contrario,  si
  scriva   alla   Free  Software Foundation, 51 Franklin Street,
  Fifth Floor Boston, MA 02110-1335 USA Stati Uniti.
  --------------------------------------------------------------------------
 */
$strScript = array("admin_aziend.php" =>
    array('title' => 'Gestione delle aziende',
        'ins_this' => 'Enter the configuration of the company',
        'upd_this' => 'Change the configuration of the company ',
        'err' => array(
            'ragso1' => 'You must enter a Company Name',
            'sexper' => 'You must enter a sex',
            'datnas' => 'Birthdate incorrect',
            'indspe' => 'You must enter a address',
            'citspe' => 'You must enter a city',
            'prospe' => 'You must enter a province',
            'codfis' => 'Tax code is formally incorrect',
            'cf_sex' => 'The tax code is not a natural',
            'pariva' => 'The VAT code is formally incorrect',
            'cf_pg' => 'The tax code is not a legal',
            'cf_emp' => 'You must provide your tax code',
            'regdat' => 'The picture must be in PNG',
            'imasize' => 'The picture has a size greater than 64kb',
            'colore' => 'The color you choose has a brightness of less than 408 (hex88 +88 +88)',
            'image' => 'You must enter a picture for the company logo',
            'capspe' => 'Invalid postal code',
            'pec' => 'Email address formally wrong',
            'e_mail' => 'Email address formally wrong',
            'web_url' => 'Web address formally wrong',
            'cod_ateco' => 'ATECO 2007 code invalid',
			'sez_rc' => 'The sectional of immediate invoices cannot be the same as that used for the reverse charge'
        ),
        'codice' => "Code ",
        'ragso1' => "Company name 1",
        'ragso2' => "Company name 2",
        'image' => "Company logo<br />(jpg,png,gif) around 400x400px max 64kb",
        'intermediary' => "Agenzia delle Entrate intermediary",
        'sedleg' => "Legal address",
        'legrap_pf_nome' => "Legal representative ",
        'sexper' => "Sex or legal person ",
        'sexper_value' => array('' => '-', 'M' => 'Male', 'F' => 'Female', 'G' => 'Legal'),
        'datnas' => 'Birthdate',
		'order_type_label'=>'Production type',
        'luonas' => 'Place of Birth - County',
        'indspe' => 'Address',
        'latitude' => 'Latitudine',
        'longitude' => 'Longitude',
        'capspe' => 'Postal code',
        'citspe' => 'City - Province',
        'country' => 'Country',
        'id_language' => 'Language',
        'id_currency' => 'Currency',
        'telefo' => 'Telephone',
        'fax' => 'Fax',
        'codfis' => 'Tax code',
        'pariva' => 'VAT code',
        'REA_ufficio' => 'Provincia ufficio REA (elem.1.2.4.1 FAE)',
        'REA_numero' => 'Ufficio REA (elem.1.2.4.2 FAE)',
        'REA_capitale' => 'Capitale Sociale (elem.1.2.4.3 FAE)',
        'REA_socio' => 'Socio (elem.1.2.4.4 FAE)',
        'REA_socio_value' => array(''=>'-----------', 'SU' => 'Socio Unico', 'SM' => 'più Soci'),
        'REA_stato' => 'Stato (se in liquidazione elem.1.2.4.5 FAE)',
        'REA_stato_value' => array('LN' => 'non in liquidazione', 'LS' => 'in liquidazione'),
        'pec' => 'Posta Elettronica Certificata',
        'e_mail' => 'e mail',
        'web_url' => 'Web url<br />(ex: http://companyname.com)',
        'gazSynchro' => 'Moduli sincronizzazioni ecommerce e/o devices',
        'cod_ateco' => 'Activity code (ATECOFIN)',
        'regime' => 'Accounting regime',
        'regime_value' => array('0' => 'Ordinary', '1' => 'Semplified'),
        'fiscal_reg' => 'Regime fiscale',
        'fiscal_reg_value' => array('RF01' => 'Ordinario', 'RF02' => 'Contribuenti minimi', 'RF03' => 'Nuove iniziative produttive', 'RF04' => 'Agricoltura e attività connesse e pesca',
            'RF05' => 'Vendita sali e tabacchi', 'RF06' => 'Commercio dei fiammiferi', 'RF07' => 'Editoria', 'RF08' => 'Gestione di servizi di telefonia pubblica'),
        'decimal_quantity' => 'N&ordm; decimal quantity',
        'decimal_quantity_value' => array(0, 1, 2, 3, 9 => 'Float'),
        'decimal_price' => 'N&ordm; decimal price',
        'stock_eval_method' => 'Method of stock enhancement',
        'stock_eval_method_value' => array(0 => 'Standard', 1 => 'Weighted average cost', 2 => 'LIFO', 3 => 'FIFO'),
        'mascli' => 'Master customers account ',
        'masfor' => 'Master suppliers account',
        'masban' => 'Master banks account',
        'mas_staff' => 'Master employees account',
        'mas_fixed_assets' => 'Mastro immobilizzazioni',
        'mas_found_assets' => 'Mastro fondo ammortamenti',
        'mas_cost_assets' => 'Mastro costi ammortamento',
        'lost_cost_assets' => 'Conto quote perse ammortamento',
        'min_rate_deprec' => 'Minimum rate depreciation (%)',
        'super_amm_account'=>'Conto costo super ammortamento',
        'super_amm_rate'=>'Percentuale eccedente il 100%',
        'capital_loss_account'=>'Conto minusvalenze',
        'capital_gains_account'=>'Conto plusvalenze',
        'cassa_' => 'Cash account',
        'ivaacq' => 'Purchases VAT account',
        'ivaven' => 'Sales VAT account',
        'ivacor' => 'Tickets VAT account',
        'ivaera' => 'Treasury VAT account',
        'split_payment' => 'PA Split Payment VAT account',
        'impven' => 'Taxable sales account',
        'imptra' => 'Transport revenues account',
        'impimb' => 'Packaging revenues account',
        'impspe' => 'Revenues of collection account',
        'impvar' => 'Miscellaneous revenues account',
        'boleff' => 'Stamp account',
        'omaggi' => 'Gifts account',
        'sales_return' => 'Sales return account',
        'impacq' => 'Taxable purchases account',
        'cost_tra' => 'Transport costs account',
        'cost_imb' => 'Packaging costs account',
        'cost_var' => 'Miscellaneous costs account',
        'purchases_return' => 'Purchases return account',
        'coriba' => 'Portfolio Ri.Ba account',
        'cotrat' => 'Portfolio draft account',
        'cocamb' => 'Portfolio bills account',
        'c_ritenute' => 'Withholding account',
        'c_ritenute_autonomi' => 'Ritenute autonomi da versare',
        'payroll_tax' => 'Payroll tax percent',
        'c_payroll_tax' => 'Payroll tax account',
        'ritenuta' => '% Withholding',
        'upgrie' => 'Last page of VAT summary reg.',
        'upggio' => 'Last page of the journal',
        'upginv' => 'Last Page of Book Inventories',
        'upgve' => 'Last pages of Sales invoice reg.',
        'upgac' => 'Last pages of Purchases invoice reg.',
        'upgco' => 'Last pages of Tickets invoice reg.',
        'sezione' => 'VAT section ',
        'acciva' => 'VAT advance rate (%)',
        'taxstamp_limit' => 'Tax stamp exemption limit',
        'taxstamp' => 'Amount stamp operations without VAT',
        'taxstamp_vat' => 'Taxstamp VAT rate',
        'taxstamp_account' => 'Conto costo bolli',
        'perbol' => 'Rate of stamps on draft (%)',
        'round_bol' => 'Round of stamps',
        'round_bol_value' => array(1 => 'cent', 5 => 'cents', 10 => 'cents',
            50 => 'cents', 100 => 'cents (unit)'),
        'virtual_taxstamp' => 'Tax stamp mode',
        'virtual_taxstamp_value' => array(0 => 'No', 1 => 'Material', 2 => 'Virtual'),
        'virtual_stamp_auth_prot' => 'Virtual stamp authorizzation number ',
        'virtual_stamp_auth_date' => ' date ',
        'causale_pagam_770' => 'Causale del pagamento ritenuta(mod.770)',
        'causale_pagam_770_value' => array('' => '-------------------',
            'A' => 'Prestazioni di lavoro autonomo rientranti nell’esercizio di arte o professione abituale',
            'B' => 'Utilizzazione economica, da parte dell’autore o dell’inventore, di opere dell’ingegno, di brevetti industriali e di processi, formule o informazioni relativi a esperienze acquisite in campo industriale, commerciale o scientifico',
            'C' => 'Utili derivanti da contratti di associazione in partecipazione e da contratti di cointeressenza, quando l’apporto è costituito esclusivamente dalla prestazione di lavoro',
            'D' => 'Utili spettanti ai soci promotori e ai soci fondatori delle società di capitali',
            'E' => 'Levata di protesti cambiari da parte dei segretari comunali',
            'G' => 'Indennità corrisposte per la cessazione di attività sportiva professionale',
            'H' => 'Indennità corrisposte per la cessazione dei rapporti di agenzia delle persone fisiche e delle società di persone, con esclusione delle somme maturate entro il 31.12.2003, già imputate per competenza e tassate come reddito d’impresa',
            'I' => 'Indennità corrisposte per la cessazione da funzioni notarili',
            'L' => 'Utilizzazione economica, da parte di soggetto diverso dall’autore o dall’inventore, di opere dell’ingegno, di brevetti industriali e di processi, formule e informazioni relative a esperienze acquisite in campo industriale, commerciale o scientifico',
            'L1' => 'Redditi derivanti dall’utilizzazione economica di opere dell’ingegno, di brevetti industriali e di processi, formule e informazioni relativi a esperienze acquisite in campo industriale, commerciale o scientifico, che sono percepiti da soggetti che abbiano acquistato a titolo oneroso i diritti alla loro utilizzazione',
            'M' => 'Prestazioni di lavoro autonomo non esercitate abitualmente, obblighi di fare, di non fare o permettere',
            'M1' => 'redditi derivanti dall’assunzione di obblighi di fare, di non fare o permettere',
            'N' => 'Indennità di trasferta, rimborso forfetario di spese, premi e compensi erogati: .. nell’esercizio diretto di attività sportive dilettantistiche; .. in relazione a rapporti di collaborazione coordinata e continuativa di carattere amministrativo-gestionale, di natura non professionale, resi a favore di società e associazioni sportive dilettantistiche e di cori, bande e filodrammatiche da parte del direttore e dei collaboratori tecnici',
            'O' => 'Prestazioni di lavoro autonomo non esercitate abitualmente, obblighi di fare, di non fare o permettere, per le quali non sussiste l’obbligo di iscrizione alla gestione separata (Circ. Inps 104/2001)',
            'O1' => 'Redditi derivanti dall’assunzione di obblighi di fare, di non fare o permettere, per le quali non sussiste l’obbligo di iscrizione alla gestione separata (Circ. INPS n. 104/2001);',
            'P' => 'Compensi corrisposti a soggetti non residenti privi di stabile organizzazione per l’uso o la concessione in uso di attrezzature industriali, commerciali o scientifiche che si trovano nel territorio dello Stato, ecc',
            'Q' => 'Provvigioni corrisposte ad agente o rappresentante di commercio monomandatario',
            'R' => 'Provvigioni corrisposte ad agente o rappresentante di commercio plurimandatario',
            'S' => 'Provvigioni corrisposte a commissionario',
            'T' => 'Provvigioni corrisposte a mediatore',
            'U' => 'Provvigioni corrisposte a procacciatore di affari',
            'V' => 'Provvigioni corrisposte a incaricato per le vendite a domicilio e provvigioni corrisposte a incaricato per la vendita porta a porta e per la vendita ambulante di giornali quotidiani e periodici (L. 25.02.1987, n. 67)',
            'V1' => 'Redditi derivanti da attività commerciali non esercitate abitualmente (ad esempio, provvigioni corrisposte per prestazioni occasionali ad agente o rappresentante di commercio, mediatore, procacciatore d’affari o incaricato per le vendite a domicilio);',
            'W' => 'Corrispettivi erogati nel 2012 per prestazioni relative a contratti d’appalto cui si sono resi applicabili le disposizioni contenute nell’art. 25-ter D.P.R. 600/1973',
            'X' => 'Canoni corrisposti nel 2004 da società o enti residenti, ovvero da stabili organizzazioni di società estere di cui all’art. 26-quater, c. 1, lett. a) e b) D.P.R. 600/1973, a società o stabili organizzazioni di società, situate in altro Stato membro dell’Unione Europea in presenza dei relativi requisiti richiesti, per i quali è stato effettuato il rimborso della ritenuta ai sensi dell’art. 4 D. Lgs. 143/2005 nell’anno 2006',
            'Y' => 'Canoni corrisposti dall’1.01.2005 al 26.07.2005 da soggetti di cui al punto precedente',
            'Z' => 'Titolo diverso dai precedenti'
        ),
        'sperib' => 'RIBA collection costs to be charged ',
        'desez' => 'Description of ',
        'reverse_charge_sez' => 'Sezione utilizzata per il reverse charge',
        'fatimm' => 'Sezione delle Fatture Immediate',
        'fatimm_value' => array('R' => 'Report section', 'U' => 'Section of last entry',
            '1' => 'Always 1', '2' => 'Always 2', '3' => 'Always 3'),
        'artsea' => 'Ricerca articoli per',
        'artsea_value' => array('C' => 'Code', 'B' => 'Barcode', 'D' => 'Description', 'T' => 'All'),
        'templ_set' => 'Template set of the documents',
        'colore' => 'Background color of documents',
        'conmag' => 'Stock records',
        'conmag_value' => array(0 => 'Never', 1 => 'Manual (not recommended)', 2 => 'Automatic'),
        'ivam_t' => 'Frequency VAT payment',
        'ivam_t_value' => array('M' => 'Monthly', 'T' => 'Quarterly'),
        'preeminent_vat' => 'Usually VAT rate',
        'interessi' => 'Interest on Quarterly VAT',
        'amm_min' => 'Tabella Ammortamenti Ministeriali',
        'fae_tipo_cassa' => 'Tipo Cassa (fatture elettroniche)',
        'ra_cassa' => 'Ritenuta su cassa previdenziale'
    ),
    "report_aziend.php" =>
    array('title' => 'List of installed enterprise',
        'ins_this' => 'Create new company',
        'upd_this' => 'Update company ',
        'codice' => 'ID',
        'ragso1' => 'Company name',
        'e_mail' => 'Internet',
        'telefo' => 'Telephone',
        'regime' => 'Regime',
        'regime_value' => array('0' => 'Ordinary', '1' => 'Semplified'),
        'ivam_t' => 'VAT Frequency',
        'ivam_t_value' => array('M' => 'Monthly', 'T' => 'Quarterly')
    ),
    "create_new_company.php" =>
    array('title' => 'Create a new enterprise',
        'errors' => array('Code must be between 1 and 999!',
            'Company code already in use!'
        ),
        'codice' => 'ID number (code)',
        'ref_co' => 'Azienda di riferimento per il popolamento dei dati',
        'clfoco' => 'Create accounting plane',
        'users' => 'Allow the users of the company reference',
        'clfoco_value' => array(0 => 'No (not recommended)',
            1 => 'Yes, but without customers, suppliers and banks',
            2 => 'Yes, including customers, suppliers and banks'),
        'base_arch' => 'Populating base archive',
        'base_arch_value' => array(0 => 'No (not recommended)',
            1 => 'Yes, but without carriers and packaging',
            2 => 'Yes, including carriers and packaging'),
        'artico_catmer' => 'Duplicazione articoli di magazzino',
        'artico_catmer_value' => array(0 => 'No (default)',
            1 => 'Sì (normalmente sulle installazione didattiche)')
    ),
    "admin_pagame.php" =>
    array("Payments method",
        "Payment code",
        "Description",
        "Payment type",
        "Simultaneous collection",
        'pagaut' => "Simultaneous payment",
        "Type of effect",
        "Effect days",
        "Excluded month",
        "Next month",
        "Next day",
        "Number of payments",
        "Periodicity",
        "Bank account",
        "Note",
        array('C' => 'Simultaneous','O' => 'bonifico', 'K' => 'Payment cards', 'D' => 'rimessa diretta', 'I' => 'RID', 'B' => 'Bank recepit', 'T' => 'Bill of exchange', 'V' => 'RID'),
        array('S' => 'Yes', 'N' => 'No'),
        array('D' => 'invoice date', 'G' => 'fix day', 'F' => 'end of month'),
        array('Q' => 'quindicinali', 'M' => 'mensili', 'B' => 'bimestrali', 'T' => 'trimestrali', 'U' => 'quadrimestrali', 'S' => 'semestrali', 'A' => 'annuali'),
        "Il codice scelto &egrave; gi&agrave; stato usato!",
        "La descrizione &egrave; vuota!",
        "Il codice dev'essere compreso tra 1 e 99",
		'Non hai scelto la tipologia di pagamento per la fattura elettronica',
        'ins_this' => 'Insert new payments method',
        'fae_mode' => "PA electronic invoice mode",
				'web_payment_ref'=>'Riferimento  al codice pagamento ecommerce'
    ),
    "report_aliiva.php" =>
    array('title' => "V.A.T. rates",
        'ins_this' => 'Insert a new VAT rate',
        'codice' => "Code",
        'descri' => "Description",
        'type' => "Type",
        'aliquo' => "Rate",
        'taxstamp' => 'Subject to stamp duty',
        'yn_value' => array(1 => 'Yes', 0 => 'No'),
        'fae_natura' => "Nature - PA electronic invoice",
        'operation_type'=>"Operation type"
    ),
    "admin_aliiva.php" =>
    array("VAT rate",
        "Code",
        "Description",
        "% rate",
        "Note",
        "The chosen code has already been used!",
        "The code must be between 1 and 99",
        "The description is empty!",
        "% Rate invalid!",
        "Type VAT",
        "Select the nature of the exemption / exclusion!",
        'fae_natura' => "Nature - PA electronic invoice",
        'taxstamp' => 'Subject to stamp duty',
        'operation_type'=>"Operation type",
        'yn_value' => array(1 => 'Si', 0 => 'No'),
        'annota' => 'Descrizione estesa'
    ),
    "admin_banapp.php" =>
    array('title' => 'Bank support management',
        'ins_this' => 'Insert new bank support',
        'upd_this' => 'Update bank support',
        'errors' => array('Invalid code (min=1 max=99)!',
            'The code chosen is already been used!',
            'Enter description!',
            'Invalid ABI code!',
            'Invalid CAB code!'
        ),
        'codice' => "Code ",
        'descri' => "Description ",
        'codabi' => "ABI Code",
        'codcab' => "CAB Code ",
        'locali' => "City",
        'codpro' => "State",
        'annota' => "Note",
        'report' => 'Report of Banks support',
        'del_this' => ' Bank support'
    ),
    "admin_imball.php" =>
    array('title' => 'Package management',
        'ins_this' => 'Insert new package type',
        'upd_this' => 'Update package',
        'errors' => array('Invalid code (min=1 max=99)!',
            'The code chosen is already been used!',
            'Enter description!',
            'The weight can not be negative!'
        ),
        'codice' => "Code ",
        'descri' => "Description ",
        'weight' => "Weight",
        'annota' => "Note",
        'report' => 'List of the packages',
        'del_this' => 'package'
    ),
    "admin_portos.php" =>
    array('title' => 'Rendered ports management',
        'ins_this' => 'Insert new rendered port',
        'upd_this' => 'Update rendered port',
        'errors' => array('Invalid code (min=1 max=99)!',
            'The code chosen is already been used!',
            'Enter description!'
        ),
        'codice' => "Code ",
        'descri' => "Description ",
        'annota' => "Note",
        'incoterms' => 'Incoterms-standard ICC',
        'report' => 'List of the ports',
        'del_this' => 'port'
    ),
    "admin_spediz.php" =>
    array('title' => 'Delivery management',
        'ins_this' => 'Insert new delivery',
        'upd_this' => 'Update delivery',
        'errors' => array('Invalid code (min=1 max=99)!',
            'The code chosen is already been used!',
            'Enter description!'
        ),
        'codice' => "Code ",
        'descri' => "Description ",
        'annota' => "Note",
        'report' => 'List of deliveries',
        'del_this' => 'delivery'
    ),
    "report_banche.php" =>
    array('title' => "Bank accounts",
        'ins_this' => 'Insert new bank account',
        'msg' => array('EXISTING BANK ACCOUNT ONLY ON PLAN OF ACCOUNTS', 'View and/or print the ledgers'),
        'codice' => "Code",
        'ragso1' => "Name",
        'iban' => "IBAN code",
        'citspe' => "City",
        'prospe' => "Province",
        'telefo' => "Telephone"
    ),
    "admin_bank_account.php" =>
    array("Bank account ",
        "Code number (from acconting plan) ",
        "Description ",
        "Bank credit (choose in place of description)",
        "Address ",
        "Postal code ",
        "City - County code ",
        "Nation ",
        "IBAN code ",
        'sia_code' => 'SIA Code',
        'eof' => 'File RiBA record with end of line characters',
        'eof_value' => array('S' => 'Yes', 'N' => 'No'),
        "Head office ",
        "Telephone ",
        "Fax ",
        "e-mail ",
        "Note ",
        "The accounts of the plan does not have the master banks!",
        "In configuration company was not selected a master banks!",
        "IBAN is incorrect!",
        "Existing code!",
        "Code less than 1!",
        "Description empty!",
        "The nation is incompatible with the IBAN!",
		'transfer_fees_acc'=>'Conto spese bonifici',
		'transfer_fees'=>'Addebito per bonifici'),
    "admin_vettore.php" =>
    array('title' => 'Shipper admin',
        'ins_this' => 'Insert new shipper',
        'upd_this' => 'Update shipper n.',
        'errors' => array('Company name missing!',
            'Address missing!',
            'City missing!',
            'Postal code missing!',
            'Tax code is incorrect',
            'VAT registration number is incorrect',
            'VAT registration number missing!'
        ),
        'codice' => "Code",
        'ragione_sociale' => 'Company name',
        'indirizzo' => 'Address',
        'cap' => 'Postal Code',
        'citta' => 'City',
        'provincia' => 'Province',
        'partita_iva' => 'VAT registration number',
        'codice_fiscale' => 'Tax code',
        'n_albo' => 'Shipper registration number',
        'telefo' => 'Telephone',
        'descri' => 'Other description',
        'annota' => 'Note',
        'report' => 'List of shippers',
        'del_this' => 'shipper'
    ),
    "admin_utente.php" =>
    array('title' => 'Management of the Users',
        'ins_this' => 'Insert new User',
        'upd_this' => 'Update User',
        'err' => array(
            'exlogin' => 'Nickname already exist!',
            'user_lastname' => 'Enter Surname!',
            "user_name" => "Enter Nickname!",
            'Password' => "Enter Password!",
            'passold' => "La vecchia password &egrave; sbagliata!",
            'passlen' => "The password is not long enough!",
            'confpass' => "The password is different from that of confirmation!",
            'upabilit' => "You can't increase your level of competency the operation is reserved for the administrator!",
            'filmim' => "The file must be in JPG format",
            'filsiz' => "The image must not be larger than 64kb",
            'Abilit' => "You can not have a level lower than 9 because you are the last administrator!",
            'Abilit_stud' => "You can not have a level lower than 7 because you are the last administrator!",
            'charpass' => "The password can not contain any special characters \" / < >",
			'email'=>'Indirizzo e-mail formalmente errato'
        ),
        "user_name" => "Nickname",
        'user_lastname' => "Surname",
        'user_firstname' => "Name",
        'user_email' => "Mail (anche per recupero password)",
        'image' => 'Image<br />(only JPG format, max 64kb)',
        'Abilit' => "Level",
        'Abilit_value' => array('9' => 'Admin', '8' => 'Advanced/Student','5'=>'User','0'=>'None'),
		'company'=>'Company',
        'mesg_co' => array('Non &egrave; stato trovato nulla!', 'Minimo 2 caratteri', 'Azienda di lavoro'),
        'Access' => "Access number",
        'user_password_old' => 'Vecchia Password',
        'user_password_new' => 'Nuova Password',
        'user_password_ver' => 'Verifica Password',
		'user_active' => 'Abilitazione utente',
		'user_active_value' => array('1'=>'Attivo','0'=>'Disattivo'),
        'lang' => 'Language',
        'theme'=>'Interface engine.<br>It will be active from next login',
        'style' => 'Theme structure',
        'skin' => 'Theme style',
        'mod_perm' => 'Modules permit',
        'report' => 'Users list',
        'del_this' => 'User',
        'del_err' => 'You can not delete because you\'re the only one with administrator rights!',
        'body_text'=> 'Testo contenuto nelle email che invierai'
    ),
    "config_aziend.php" =>
    array('title' => 'Configurazione avanzata azienda'),
	"edit_privacy_regol.php" =>
    array('title' => 'Regolamento per l’utilizzo e la gestione delle risorse informatiche',
        'ins_this' => 'Inserisci il Regolamento per l’utilizzo e la gestione delle risorse informatiche',
        'upd_this' => 'Modifica il Regolamento per l’utilizzo e la gestione delle risorse informatiche',
        'err' => array(
            'body_text' => 'Testo del regolamento troppo breve'
        ),
        'body_text' => "Testo "
 	)
);
?>
