<?php

/*
  --------------------------------------------------------------------------
  GAzie - Gestione Azienda
  Copyright (C) 2004-present - Antonio De Vincentiis Montesilvano (PE)
  (https://www.devincentiis.it)
  <https://gazie.sourceforge.net>
  --------------------------------------------------------------------------
  Questo programma e` free software;   e` lecito redistribuirlo  e/o
  modificarlo secondo i  termini della Licenza Pubblica Generica GNU
  come e` pubblicata dalla Free Software Foundation; o la versione 2
  della licenza o (a propria scelta) una versione successiva.

  Questo programma  e` distribuito nella speranza  che sia utile, ma
  SENZA   ALCUNA GARANZIA; senza  neppure  la  garanzia implicita di
  NEGOZIABILITA` o di  APPLICABILITA` PER UN  PARTICOLARE SCOPO.  Si
  veda la Licenza Pubblica Generica GNU per avere maggiori dettagli.

  Ognuno dovrebbe avere   ricevuto una copia  della Licenza Pubblica
  Generica GNU insieme a   questo programma; in caso  contrario,  si
  scriva   alla   Free  Software Foundation, 51 Franklin Street,
  Fifth Floor Boston, MA 02110-1335 USA Stati Uniti.
  --------------------------------------------------------------------------
 */

/*
  -- TRANSLATED BY : Dante Becerra Lagos (softenglish@gmail.com)
 */

 //*+- Nuove stringhe per modulo select_analisi_avanzamento_per_fornitore.php - DC - 19 apr 2018 (NON TRADOTTE)

$strScript = array("admin_client.php" =>
    array('title' => 'Administarcion de clientes',
        'ins_this' => 'Insertar nuevo cliente',
        'upd_this' => 'Actualizar cliente',
        'mesg' => array('La busqueda no dio resultados!',
            'Inserte al menos 2 caracteres!',
            'Cambiando cliente'
        ),
        'errors' => array('Usted debe indicar la Razon Social',
            'Usted debe indicar la direccion',
            'Usted debe indicar la CAP',
            'Usted debe indicar la ciudad',
            'Usted debe indicar la region',
            'Usted debe indicar el genero',
            'IBAN no es correcto',
            'IBAN y el pais son difrentes',
            'El codigo fiscal es obligatorio para una persona natural',
            'El IVA esta formalmente incorrecto!',
            'Existe ya un cliente con el mismo IVA',
            'El codigo fiscal esta formalmente incorrecto',
            'Existe ya un cliente con el mismo Codigo de Fiscal',
            'C.F. faltante! &iexcl;En autom&aacute;tico ha sido < br / > programado con el mismo valor del IVA!',
            'Es una persona natural, introduzca el c&oacute;digo fiscal',
            'Existe un registro con el mismo IVA',
            'Existe un registro con el mismo c&oacute;digo fiscal',
            'Usted debe elegir el metodo de pago',
            'El c&oacute;digo de cliente ya est&aacute; ah&iacute;, intentar la entrada con la que se propone (m&aacute;s 1)',
            'The date of birth is wrong',
            'Email formalmente mal la dirección'
        ),
        'link_anagra' => ' Haga clic a continuaci&oacute;n para introducir sus datos personales en la tabla existente de cuentas',
        'codice' => "Codigo ",
        'ragso1' => "Nombre de la empresa 1",
        'ragso1_placeholder' => "opp. nome cognome legale rappresentante",
        'ragso2' => "Nombre de la empresa 2",
        'sedleg' => "Domicilio Legal",
        'luonas' => 'Birthplace',
        'datnas' => 'Date of birth',
        'pronas' => 'Province of birth',
        'counas' => 'Country of birth',
        'legrap_pf_nome' => "Representante Legal ",
        'legrap_pf_title' => "la ragione sociale lasciata vuota verrà riempita con questi campi",
        'fiscal_rapresentative_id' => "Fiscal rapresentante",
        'sexper' => "Genero/persona juridica ",
        'sexper_value' => array('' => '-', 'M' => 'Masculino', 'F' => 'Femenino', 'G' => 'Juridica'),
        'indspe' => 'Direccion',
        'capspe' => 'Codigo Postal',
        'citspe' => 'Ciudad - Region',
        'country' => 'Pais',
        'id_language' => 'Lengua',
        'id_currency' => 'Moneda',
        'telefo' => 'Telefono',
        'fax' => 'Fax',
        'cell' => 'Celular',
        'codfis' => 'Codigo Fiscal',
        'pariva' => 'I.V.A.',
        'pec_email' => 'Posta Elettronica Certificata',
        'e_mail' => 'e mail',
        'id_agente' => 'Agente',
        'cosric' => 'Conto di ricavo',
        'codpag' => 'Metodo de pago *',
        'sconto' => '% Sconto chiusura',
        'sconto_rigo' => 'Sconto sui righi documenti',
        'banapp' => 'Banco de apoyo',
        'portos' => 'Puerto - Rendimiento',
        'spediz' => 'Embarque',
        'imball' => 'Imballo',
        'listin' => 'Lista de precios aplicados',
        'id_des' => 'Destino del registro',
        'destin' => 'Descripci&oacute;n del destino libre',
        'iban' => 'IBAN',
        'maxrat' => 'El importe m&aacute;ximo de la tasa',
        'ragdoc' => 'Agrupaci&oacute;n de los documentos',
        'addbol' => 'Pozo costo de debito',
        'speban' => 'Costos bancarias de débito ',
        'spefat' => 'Costes de facturaci&oacute;n de débito',
        'stapre' => 'Los precios de impresion sobre el DDT ',
        'allegato' => 'Anexo IVA - Clientes',
        'yn_value' => array('S' => 'Si', 'N' => 'No'),
        'aliiva' => 'Reduccion de I.V.A.',
        'ritenuta' => '% Retenci&oacute;n',
        'status' => 'Visibilidad de Investigacion',
        'status_value' => array('' => 'Activa', 'HIDDEN' => 'Desabilitada'),
        'annota' => 'Anotaciones',
        'fe_cod_univoco' => 'Código de cliente único (factura electrónica)',
        'fatt_email' => 'Inviare fattura:',
        'fatt_email_value' => array(0 => 'No, solo stampa PDF', 1 => 'In formato PDF su email', 2=>'In formato XML su PEC',3=>'In formato PDF su email + formato XML su PEC'),
        'operation_type' => 'Tipo di operazione'
    ),
    "report_docven.php" =>
    array('title' => 'Lista dei documenti di vendita',
        'mail_alert0' => 'Invio documento con email',
        'mail_alert1' => 'Hai scelto di inviare una e-mail all\'indirizzo: ',
        'mail_alert2' => 'con allegato il seguente documento di vendita:',
        'fae_alert0' => 'Generazione documento FAE',
        'fae_alert1' => 'Hai scelto di generare la fattura elettronica ',
        'fae_alert2' => '',
        'report_alert0' => 'Mostra tutti i documenti',
        'report_alert1' => 'Sicuro di voler mostrare tutti i documenti?',
        'print_lot' => 'Stampa certificati',
    ),
    "admin_agenti.php" =>
    array("Agentes de venta ",
        "Agentes de venta",
        "Numero",
        "Proveedor",
        "Telefono",
        "Fax",
        "% Comisiones",
        "Categoria Mercaderia",
        "Articulo",
        "Porcentaje",
        "Especificos para ",
        "ya se ha insertado!",
        "Falta de datos necesarios para a&ntilde;adir una l&iacute;nea!",
        "El porcentaje de la comisi&oacute;n debe ser superior a 0,01!",
        "Usted est&aacute; tratando de insertar un agente sin conectarse a un proveedor!",
        "No se incluy&oacute; el n&uacute;mero de agente",
        "Estas intentando ingresar en un proveedor que ya es un agente!",
        "Usted est&aacute; tratando de insertar un n&uacute;mero de agente que ya existe!",
        "Esta elimimando un agente!",
        "Lista de Comisiones ",
        'title' => 'Administarcion de agente de venta',
        'ins_this' => 'Insertar nuevo agente de venta'
    ),
    "select_provvigioni.php" =>
    array("Seleccionar para imprimir la lista de las Comisiones ",
        "Agente de venta",
        "Todos los agentes ",
        "Inserte min. 2 caracteres!",
        "No se ha encontrado nada !",
        "Fecha de Periodo inicio ",
        "Fecha de Periodo final"
    ),
    "admin_docven.php" =>
    array('none',
        'doc_name' => array("DDT" => "Nota de entrega de Ventas",
            "FAD" => "Nota de entrega faturada",
            "FAI" => "Factura Inmediata invoice",
            "FAP" => "Cuenta",
            "FNC" => "Nota de credito al cliente",
            "FND" => "Nota de debito al cliente",
            "VCO" => "Boleta de venta",
            "DDV" => "D.d.T. per Cessione in Conto Visione",
            "DDY" => "D.d.T. da non fatturare automaticamente",
            "DDS" => "Notula Servizio (no fat.15 mese succ.)",
            "RDV" => "Ricevuto DdT di Reso da C/Visione",
            "VRI" => "Recibido"
        ),
        'title' => 'Documento de venta',
        'tipdoc' => ' documento de venta tipo: ',
        'mesg' => array('La busqueda no dio resultados!',
            'Inserte al menos 2 caracteres!',
            'Cambiando cliente / proveedor'
        ),
        " cuerpo ",
        " pie de pagina ",
        " Subir ",
        " Seccion ",
        " Direccion ",
        " Fecha ",
        " Lista de precios ",
        " Pago ",
        " Banco ",
        " Consignatario ",
        " Causal ",
        " Bodega ",
        " Ventas ",
        "Vector",
        "Item",
        "Cantidad",
        "Tipo",
        "Ingreso",
        "I.V.A.",
        "Codigo",
        "Descripcion",
        "M.U.",
        "Precio",
        "Reduccion",
        "Cantidad",
        "Empaque",
        "Entrega",
        "Transporte",
        "Puerto ",
        "Transporte de inicio",
        "horass",
        "Tributable",
        "Impuesto",
        "Cantidad Cuerpo",
        "Peso",
        "Total",
        "Fecha de comienzo del transporte no es correcta!",
        "Fecha de comienzo de transporte anteriores a la fecha de emision!",
        "No hay ninguna fila  de documento !",
        "tratas de cambiar el DDT, con una fecha anterior a la edici&oacute;n anterior con DDT!",
        "tratas de cambiar el DDT con una fecha posterior a la del DDT con la pr&oacute;xima edici&oacute;n!",
        "Est&aacute;s intentando editar el documento con una fecha anterior a el mismo documento con el n&uacute;mero anterior!",
        "Est&aacute;s intentando editar el documento con fecha posterior a la del mismo documento con la pr&oacute;xima edici&oacute;n!",
        "La fecha de emisi&oacute;n no puede ser anterior a la &uacute;ltima DDT emitida!",
        "La fecha de emisi&oacute;n no puede ser anterior al &uacute;ltimo documento de la misma naturaleza emitido!",
        "La fecha de emisi&oacute;n no es correcta!",
        "Usted no ha seleccionado el cliente!",
        "Non hai selezionato la modalit&agrave; di pagamento!",
        "Una fila no tiene ninguna descripci&oacute;n!",
        "Una l&iacute;nea es sin la unidad de medida!",
        "Causal de Bodega",
        "Peso Neto",
        "Peso Bruto",
        "Unidades",
        "Volumen",
        "Comisiones",
        "Quieres modificar un D.d.T. ya facturado!",
        "Este documento ya esta contabilizado",
        "Per questo documento è obbligatorio selezionare il DdT di cessione in c/visione di riferimento",
        "La quantità è stata forzata ad 1 perché l'articolo prevere in numero di serie",
        'Non è stato selezionato il cespite da alienare sul relativo rigo',
		'Un rigo di tipo normale è senza quantità',
        'speban' => "Gastos de recaudaci&oacute;n",
        'speban_title' => 'Gastos de recaudaci&oacute;n no documentados/prorratas',
        'traspo_title' => 'Gastos de transporte no documentados',
        'stamp' => 'Sellos',
        'ritenuta' => 'Deducci&oacute;n de impuestos por adelantado ',
        'netpay' => 'Neto a pagar ',
        'id_agente' => "Agente de venta",
        'in_artsea' => 'B&uacute;squeda por ',
        'vat_constrain' => '(forza) IVA al ',
        'taxstamp' => 'Taxstamp',
        'virtual_taxstamp' => 'Mode',
        'virtual_taxstamp_value' => array(0 => 'No', 1 => 'Material', 2 => 'Virtual'),
        'ragbol' => "Raggr.DDT",
        'ragbol_title' => 'Raggruppamento DDT',
        'order_date' => "Data Ordine",
        'ragbol_value' => array(0 => 'A', 1 => 'B', 2 => 'C', 3 => 'D', 4 => 'E', 5 => 'F', 6 => 'G'),
        'zero_rows' => 'The document no contains rows or products. For add  them to the body enter the "%" value for a complete list or to make a partial search',
        'weight' => 'weight',
        'discount_alert' => 'discount taken from article\'s informations',
        'last_row' => 'Last row',
        'id_doc_ritorno_title' => 'Seleziona il DdT per cessione in c/visione di riferimento',
        'id_doc_ritorno_alert' => 'Non è stato selezionato il DdT per cessione in c/visione di riferimento'
    ),
    "select_docforprint.php" =>
    array('title' => 'Ristampa documenti',
        array(1 => "D.d.T. de venta", 2 => "Factura diferida", 3 => "Factura inmediata que acompa&ntilde;a", 4 => "Factura inmediata simple", 5 => "Nota Credito a Cliente", 6 => "Nota Debito a Cliente"),
        " en la secci&oacute;n ",
        "Fecha",
        "Protocollo",
        "Numero",
        " inicio",
        " termino",
        "Tipo ",
        "Seleccione Cliente ",
        "inserte min. 2 caratteri!",
        "Todos los clientes!",
        "No se ha encontrado nada!",
        "El n&uacute;mero inicio debe ser mayor que cero!",
        "El n&uacute;mero de termino debe ser mayor o igual al n&uacute;mero inicio!",
        "El protocolo debe ser mayor que cero!",
        "El protocolo de termino debe ser mayor o igual que el protocolo de inicio !",
        "La fecha inicio no es correcta!",
        "La fecha termino no es correcta!",
        "La fecha de finalizaci&oacute;n debe ser posterior al inicio !",
        "Hay documentos imprimibles en los intervalos seleccionados !"
    ),
    "admin_broven.php" =>
    array(array("VPR" => "Presupuestos para clientes", "VOR" => "Pedidos de los clientes", "VOW" => "Pedidos de los sitio web"),
        'mesg' => array('La busqueda no dio resultados!',
            'Inserte al menos 2 caracteres!',
            'Cambiando cliente / proveedor'
        ),
        " cuerpo ",
        " pie de pagina ",
        " Tira sobre ",
        " Secci&oacute;n ",
        " Dirrecion ",
        " Fecha ",
        " Lista ",
        " Pago ",
        " Banco ",
        " Destino ",
        " Causal ",
        " Bodega ",
        " Venta ",
        "Transporte",
        "Articulo",
        "Cantidad",
        "Tipo",
        "Ingresos",
        "I.V.A.",
        "Codigo",
        "Descripcion",
        "U.M.",
        "Precio",
        "Descuento ",
        "Cantidad",
        "Embalaje",
        "Expedicion",
        "Trasporte",
        "Puerto",
        "Inicio trasporte",
        " Horas ",
        "Imponible",
        "Impuesto",
        "Cantidad de Administraci&oacute;n",
        "Peso",
        "Total",
        "La fecha de inicio del transporte no es correcta!",
        "La fecha de inicio del transporte no puede ser anterior a la fecha de edici&oacute;n!",
        "No renglones para poder emitir el documento!",
        "Esta tratando de modificar el DdT con una fecha anterior a aquella del DdT con numero precedente!",
        "Esta tratando de modificar el DdT con una fecha posterior a aquella del DdT con numero succesivo!",
        "Esta tratando de modificar el documento con una fecha anterior a aquel del mismo tipo de documento con numero antecedente!",
        "Est&aacute;s intentando modificar el documento con una fecha sucesiva a aquello del mismo tipo de documento con n&uacute;mero sucesivo!",
        "La fecha de emisi&oacute;n no puede ser anterior a aquella del &uacute;ltimo DdT emetido!",
        "La fecha de emisi&oacute;n no puede ser anterior a aquella del &uacute;ltimo documento del mismo tipo emitido!",
        "La fecha de emisi&oacute;n no es correcta!",
        "Usted no ha seleccionado el cliente!",
        "Usted no ha seleccionado un método de pago!",
        "Una fila no tiene ninguna descripci&oacute;n!",
        "Una l&iacute;nea es sin la unidad de medida!",
        "Causal de bodega",
        "Peso neto",
        "Peso bruto",
        "N.paquetes",
        "Volumen",
        "Comisiones",
        "Desea cambiar un D.d.T. ya facturado!",
        "Este documento ya ha sido contabilizado!",
        'speban' => "Gastos de recaudaci&oacute;n",
        'speban_title' => 'Gastos de recaudaci&oacute;n no documentado/prorratas',
        'traspo_title' => 'Gastos  de trasporte no documentado',
        'stamp' => 'Sellos',
        'ritenuta' => 'Ritenuta ',
        'netpay' => 'Netto a pagare',
        'id_agente' => "Agente de venta",
        'print_total' => "Print total",
        'print_total_value' => array(0 => 'No', 1 => 'Yes'),
        'delivery_time' => "Delivery_days",
        'day_of_validity' => "Days of validity",
        'taxstamp' => 'Taxstamp',
        'virtual_taxstamp' => 'Mode',
        'virtual_taxstamp_value' => array(0 => 'No', 1 => 'Material', 2 => 'Virtual'),
        'weight' => 'peso',
        'zero_rows' => 'The document no contains rows or products. For add  them to the body enter the "%" value for a complete list or to make a partial search',
        'discount_alert' => 'discount taken from article\'s informations',
        'last_row' => 'Last row'
    ),
    "report_contract.php" =>
    array('title' => 'Reporte de los contratos concluidos',
        'vat_section' => ' de IVA seccion n.',
        'link1' => 'Insertar nuevo contrato',
        'link2' => 'Crear factura/boleta de contratos',
        'id' => 'ID',
        'date' => 'Fecha',
        'number' => 'Numero',
        'customer' => 'Cliente',
        'current_fee' => 'Honorario Actual'
    ),
    "admin_contract.php" =>
    array('title' => 'Administracion de contrato',
        'ins_this' => 'Insertar nuevo contrato con ',
        'upd_this' => 'Actualizar contrato concluido con ',
        'errors' => array('Fecha de estipulacion no correcta',
            'Fecha de inicio per&iacute;odo contractual no correcta',
            'Fecha &uacute;ltima adecuaci&oacute;n del canon no es correcta',
            'Fecha de estipulaci&oacute;n sucesiva a aquella de comienzo',
            'Fecha de inicio posterior al ultimo ajuste anual ',
            'No ha seleccionado un cliente',
            'No seleccionado un método de pago',
            'Por lo menos una l&iacute;nea que falta en la descripci&oacute;n',
            'Por lo menos una l&iacute;nea que falta de las unidad de medida',
            'El contrato no tiene texto',
            'La cuota actual no puede ser cero'
        ),
        'mesg' => array('La busqueda no dio resultados!',
            'Inserte al menos 2 caracteres!',
            'Cambiando cliente / proveedor'
        ),
        'address' => 'Dirrecion',
        'vat_section' => 'Seccion IVA',
        'doc_type' => 'Reciboto a ser emitido',
        'doc_type_value' => array('VRI' => 'Recibido', 'FAI' => 'Factura'),
        'doc_number' => 'Numero de Contrato',
        'conclusion_date' => 'Fecha de Conclusion',
        'start_date' => 'Fecha de Inicio',
        'months_duration' => 'Duraci&oacute;n en Meses',
        'initial_fee' => 'Honorario Inicial',
        'periodic_reassessment' => 'Reevaluacion Anual',
        'bank' => 'Banco de pago',
        'payment_method' => 'metodo de pago',
        'periodicity' => 'periodicidad',
        'periodicity_value' => array(1 => 'mensual', 2 => 'bimensual', 3 => 'trimestral', 4 => 'cuatrimestral', 6 => 'semestral', 12 => 'anual'),
        'tacit_renewal' => 'Renovaci&oacute;n tacita',
        'current_fee' => 'Honorario Actual',
        'cod_revenue' => 'Cuanta de ingreso',
        'vat_code' => 'Codigo de IVA',
        'body_text' => 'Texto del contrato',
        'last_reassessment' => 'Ultima reevaluacion',
        'last_document_date' => 'Ultima fecha de documento',
        'id_agente' => 'Agente',
        'provvigione' => '% commision',
        'rows_title' => 'Otras objeciones y/ o descripciones',
        'descri' => 'Description de Objecion ',
        'unimis' => 'U.M.',
        'quanti' => 'Cantidad',
        'price' => 'Precio',
        'discount' => 'Descuento',
        'append' => 'Recordatorio Appendice para uso administrativo',
        'customer' => 'Cliente contratante'
    ),
    "delete_contract.php" =>
    array('title' => 'Eliminar contrato ',
        'alert' => '¿Est&aacute;s seguro de que deseas eliminar este contrato?'
    ),
    "invoice_from_contract.php" =>
    array('title' => 'Crear factura / recibidos de los contratos',
        'vat_section' => ' de la seccion IVA n.',
        'on' => ' en ',
        'period' => 'Periodo',
        'period_value' => array(1 => 'mes de ', 2 => 'bimestre ', 3 => 'trimestre ', 4 => 'cuatrimestre ', 6 => 'semestre ', 12 => 'anualidad '),
        'n_creation' => 'Numero de doc',
        'norows' => 'No hay contratos para ser facturados',
        'expired' => 'Contrato expiro',
        'err_date' => 'Fecha de ultima factura<br />anterior a la seleccionada',
        'ref' => 'Desde contrato concluido en fecha '
    ),
    "admin_scontr_fast" =>
    array('ins_this' => 'Emetti scontrino con PREZZI IVA INCLUSA',
        'upd_this' => 'Modifica scontrino con PREZZI IVA INCLUSA n.',
	),
    "admin_scontr.php" =>
    array('title' => 'Administrar impuesto recibible',
        'ins_this' => 'emitir un nuevo impuesto recibible en : ',
        'upd_this' => 'Actualizar impuesto recibible n.',
        'errors' => array(
              'datemi'=>'Fecha de emision incorrect',
              'clfoco'=>'No se selecciono cleinte',
              'pagame'=>'No se selecciono metodo de pago',
              'rowdes'=>'Linea sin descripcion',
              'unimis'=>'Linea sin unidad de medida',
              'totzer'=>'El total of recibibles no puede ser cero',
              'incaut'=>'No se puede cobrar el pago automaticamente con un cliente anonimo',
              'codfis'=>'Codigo fiscal incorrecto ',
              'ecrclo'=>'QUE NO HAN HECHO EL DIARIO DE CONTABILIDAD DE CAJA REGISTRADORA',
           'cashlimit'=>'La cantidad no emite un documento de venta de forma anonima'
        ),
        'war'=>array('serial'=>"La quantità è stata forzata ad 1 perché l'articolo prevede il numero di serie"),
        'customer' => 'Cliente',
        'search_customer' => array('No encontrado!',
            'Inserte min 2 caracteres!',
            'Cambiar customer',
            'Cliente Coiche',
            ' F.C.:',
            'Anonimo'
        ),
        'indspe' => 'Direccion',
        'seziva' => 'Seccion IVA',
        'tipdoc' => 'Tipo de Documento',
        'listin' => ' n. de lista',
        'datemi' => 'Fecha de Emision',
        'caumag' => 'Causal de bodega',
        'sconto' => 'Descuento',
        'address' => 'Direccion',
        'pagame' => 'Pago',
        'codric' => 'C/ingreso',
        'codvat' => '%IVA',
        'total' => 'Total',
        'id_agente' => 'Agente',
        'in_rows_title' => 'inserte fila',
        'item' => 'Item',
        'search' => ' buscar ',
        'in_artsea_value' => array('C' => 'Codigo de Item', 'B' => 'Codigo de Barra', 'D' => 'Descripcion'),
        'tiprig' => 'Tipo',
        'tiprig_value' => array(0 => 'Normal', 1 => 'Oferta', 2 => 'Descriptivo'),
        'body_title' => 'cuerpo',
        'foot_title' => 'totales',
        'nrow'=>'Rigo',
        'upper_row' => 'Subir!',
        'codart' => 'Codigo',
        'descri' => 'Descripcion',
        'unimis' => 'U.M.',
        'quanti' => 'Cantidad',
        'prezzo' => 'Pricio',
        'provvigione' => '% Comision',
        'amount' => 'Cantidad',
        'sconto' => 'Descuento',
        'other_row'=>'Altri dati',
        'conf_row'=>'Inserisci rigo',
        'net' => 'Peso neto',
        'units' => 'Piezas',
        'volume' => 'Volumen',
        'taxable' => 'Tributable',
        'tax' => 'IVA',
        'confirm' => 'Confirm sent data to ECR?',
        'vat_constrain' => '(forza) IVA al ',
        'taxstamp' => 'Bollo',
        'virtual_taxstamp' => 'Modo',
        'virtual_taxstamp_value' => array(0 => 'No', 1 => 'Materiale', 2 => 'Virtuale'),
        'send_ecr'=>'INVIA al registratore di cassa ',
        /** ENRICO FEDELE */
        'add_article' => 'Añadir un nuevo artículo',
        'weight' => 'peso'
    ),
    "genera_effett.php" =>
    array('title' => 'Generar los efectos de los documentos tributables',
        'errors' => array('No hay documentos que pueden generar efectos con lo seleccionado'
        ),
        'preview' => 'Vista previa de creaci&oacute;n de efecto',
        'date_reg' => 'Fecha',
        'protoc' => 'Protocolo/Seccion',
        'doc_type' => 'Tipo de Document',
        'doc_type_value' => array('FAD' => 'Factura Diferida  al cliente',
            'FAI' => 'Factura Inmediata  al cliente',
            'FND' => 'NOTA de Deuda al cliente'
        ),
        'type' => 'Tipo',
        'type_value' => array('B' => ' Recibo Bancario',
            'T' => ' Giro',
            'V' => ' Payment against notice'
        ),
        'customer' => 'Cliente',
        'tot' => 'Total',
        'total_value' => array('B' => 'Total Recibos Banco',
            'T' => 'Total Giros',
            'V' => ' Total Payment against notice'
        ),
        'gen' => 'generara',
        'end' => 'finalizando '
    ),
    "distin_effett.php" =>
    array('title' => 'Lista de Papel de cuentas y recibos bancarios',
        'errors' => array('No hay efectos en el l&iacute;mite seleccionado',
            'Fecha Incorrecta',
            'La fecha de inicio es posterior a la final',
            'La fecha de emisi&oacute;n es posterior a la inicial'
        ),
        'preview' => 'Vista previa de la lista de papel',
        'header' => array('Num' => '', 'Tipo' => '', 'Fecha de Expiracion' => '', 'Cantidad' => '',
            'Cliente/V.R.' => '', 'Factura/Cantidad' => '', 'Banco/ABI-CAB' => ''
        ),
        'date_emi' => 'Fecha Lista',
        'bank' => 'Credito Bancario',
        'date_ini' => 'Fecha de Expiracion Inicial',
        'date_fin' => 'Fecha de Expiracion Final',
        'num_ini' => 'Numero Inicial',
        'num_fin' => 'Numero Final',
        'period' => 'Seleccione plazos proximos',
        'period_value' => 'Plazos proximos',
        'reprint' => 'Rotulados',
        'reprint_value' => array('S' => 'Si', 'N' => 'No'),
        'type' => 'Tipo de cuenta: ',
        'type_value' => array('B' => 'Recibo Bancario', 'T' => 'Cuenta', 'V' => 'MAV'),
        'tot' => 'Total of list'
    ),
    "select_filerb.php" =>
    array('title' => 'Creacion de Archivo RiBa (formato CBI)',
        'errors' => array('No hay efectos en el l&iacute;mite seleccionado',
            'Fecha incorracta',
            'La fecha de inicio es posterior a la final',
            'La fecha de emisi&oacute;n es posterior a la inicial'
        ),
        'preview' => 'Vista previa de contenido archivo RiBa ( formato CBI)',
        'header' => array('Num' => '', 'Tipo' => '', 'Fecha de Expiracion' => '', 'Cantidad' => '',
            'cliente/V.R.' => '', 'Factura/Cantidad' => '', 'Banco/ABI-CAB' => ''
        ),
        'date_emi' => 'Fecha de lista',
        'bank' => 'Credito Bancario',
        'date_ini' => 'Fecha de Expiracion Inicial',
        'date_fin' => 'Fecha de Expiracion Final',
        'num_ini' => 'Numero Inicial',
        'num_fin' => 'Numero Final',
        'period' => 'Seleccione plazos proximos',
        'period_value' => 'Plazos proximos',
        'reprint' => 'Rutulados',
        'reprint_value' => array('S' => 'Si', 'N' => 'No'),
        'tot' => 'Total del contenido del archivo',
        'eof' => 'Record with characters at the end of line',
        'eof_title' => 'Record with characters at the end of line chr 13 e 10'
    ),
    "select_filemav.php" =>
    array('title' => 'Creacion de Archivo MAV (formato CBI)',
        'errors' => array('No hay efectos en el l&iacute;mite seleccionado',
            'Fecha incorracta',
            'La fecha de inicio es posterior a la final',
            'La fecha de emisi&oacute;n es posterior a la inicial'
        ),
        'preview' => 'Vista previa de contenido archivo MAV ( formato CBI)',
        'header' => array('Num' => '', 'Tipo' => '', 'Fecha de Expiracion' => '', 'Cantidad' => '',
            'cliente/V.R.' => '', 'Factura/Cantidad' => '', 'Banco/ABI-CAB' => ''
        ),
        'date_emi' => 'Fecha de lista',
        'bank' => 'Credito Bancario',
        'date_ini' => 'Fecha de Expiracion Inicial',
        'date_fin' => 'Fecha de Expiracion Final',
        'num_ini' => 'Numero Inicial',
        'num_fin' => 'Numero Final',
        'period' => 'Seleccione plazos proximos',
        'period_value' => 'Plazos proximos',
        'reprint' => 'Rutulados',
        'reprint_value' => array('S' => 'Si', 'N' => 'No'),
        'tot' => 'Total del contenido del archivo'
    ),
    "error_msg.php" =>
    array('admin_scontr' => array(0 => 'Advertencia!<br />No tiene privilegios para enviar datos a la caja registradora (ECR), p&oacute;ngase en contacto con su administrador para cambiar la configuraci&oacute;n de la tabla gaz_cash_register')
    ),
    "report_scontr.php" =>
    array('title' => 'Informe de crédito fiscal',
        'seziva' => ' de la secci&oacute;n de IVA n.',
        'link1' => 'Emitir un nuevo crédito fiscal',
        'link2' => 'Ejecutar el cierre diario de la caja registradora',
        'id' => 'ID',
        'date' => 'Fecha',
        'number' => 'Numero',
        'invoice' => 'Factura adjuntas',
        'print_lot' => 'Stampa certificato',
        'pagame' => 'Pagamento',
        'status' => 'Estado',
        'status_value' => array(0 => 'Emitida', 1 => 'Registrada'),
        'send' => 'Retransmitir a ECR',
        'amount' => 'Amount'
    ),
    "report_broven.php" =>
    array('title' => 'Las cotizaciones y pedidos',
        'mail_alert0' => 'Invio documento con email',
        'mail_alert1' => 'Hai scelto di inviare una e-mail all\'indirizzo: ',
        'mail_alert2' => 'con allegato il seguente documento:',
        'title_value' => array('VPR' => 'Las citas a los clientes',
            'VOR' => 'Pedidos de los clientes',
            'VOW' => 'Los pedidos de la p&aacute;gina web'),
        'link_title' => array('VPR' => 'Nuevas citas con los clientes',
            'VOR' => 'Nuevo Pedidos de los clientes',
            'VOW' => 'Obtener Pedidos de la p&aacute;gina web'),
        'link_value' => array('VPR' => 'admin_broven.php?Insert&tipdoc=VPR',
            'VOR' => 'admin_broven.php?Insert&tipdoc=VOR',
            'VOW' => 'import_gaziecart.php'),
        'issue_ord' => 'Proceso de pedidos',
        'id' => 'ID',
        'type' => 'Tipo',
        'type_value' => array('VPR' => 'Citas',
            'VOR' => 'Pedidos',
            'VOW' => 'Pedidos WEB'),
        'date' => 'Fecha',
        'number' => 'N&uacute;mero',
        'issue' => 'Procesa',
        'status' => 'Estado',
        'status_value' => array(0 => '', 1 => 'PROCESA')
    ),
    "resend_to_ecr.php" =>
    array('title' => 'Retransmision de datos a caja registradora',
        'head' => 'Reemitir el recibo n.',
        'on' => ' en: ',
        'total' => 'Cantidad TOTAL',
        'message' => " ADVERTENCIA!!! <br />Est&aacute; intentando volver a emitir un recibo tributario expedido, esto no es normal.<br />S&oacute;lo cuando se hayan tenido problemas que han impedido la transmisi&oacute;n de datos a la registradora en el proceso de expedici&oacute;n de una nueva boleta que es correcto.<br />Antes de proceder le recomendamos  hacerlo manualmente en la registradora para asegurarse de que no se deja en un estado de espera y luego no pudo completar la emision",
        'submit' => 'Enviar de todas formas'
    ),
    "close_ecr.php" =>
    array('title1' => 'Realizar el cierre de la caja registradora',
        'title2' => ' y trasladar de los recibos emitidos al libro',
        'message' => "ADVERTENCIA!!! <br />No hay boletas emitidas y  no cerradas/contabilizadas en esta caja registradora",
        'date' => 'Fecha',
        'num' => 'Numero',
        'sez' => 'Seccion IVA',
        'customer' => 'Cliente',
        'anony' => 'Anonimo',
        'importo' => 'Cantidad'
    ),
    "accounting_documents.php" =>
    array('title' => 'Crear movimientos contables de los documentos tributables',
        'errors' => array('Fecha Incorrecta',
            'No hay documentos para ser escritos en lo seleccionado'
        ),
        'vat_section' => ' de seccion de IVA n.',
        'date' => 'hasta :',
        'type' => 'Registro IVA ',
        'type_value' => array('F' => 'de facturas de ventas', 'V' => 'de cargos'),
        'proini' => 'Protocolo Initial',
        'profin' => 'Protocolo Final',
        'preview' => 'Vista previa Contabilidad',
        'date_reg' => 'Fecha',
        'protoc' => 'Protocolo',
        'doc_type' => 'Tipo',
        'doc_type_value' => array('FAD' => 'FACTURA DIFERIDA AL CLIENTE',
            'FAI' => 'FACTURA INMEDITA AL CLIENTE',
            'FNC' => 'NOTA DE CREDITO AL CLIENTE',
            'FND' => 'NOTA DE DEUDA AL CLIENTE',
            'VCO' => 'HONORARIOS',
            'VRI' => 'RECIBIDOS',
            'AFA' => 'FACTURA DE COMPRA',
            'AFC' => 'NOTA DE CREDITO DE LA COMPRA',
            'AFD' => 'NOTA DE DEUDA DE LA COMPRA'
        ),
        'customer' => 'Cliente/Proveedor',
        'taxable' => 'Tributable',
        'vat' => 'IVA',
        'stamp' => 'Sellos en las Cuentas',
        'tot' => 'Total'
    ),
    "import_gaziecart.php" =>
    array('title' => 'Importazione ordini web provenienti da GAzieCart',
        'errors' => array('Non ci sono ordini da importare dalla casella e-mail'
        ),
        'email' => 'Direcci&oacute;n para recibir &oacute;rdenes: ',
        'pass' => 'Contrase&ntilde;a utilizada para acceder a: ',
        'server' => 'Direcci&oacute;n del servidor: ',
        'name' => 'Orden WEB',
        'amount' => 'Totales de mercanc&iacute;as',
        'tot' => 'TOTALES ',
        'tax' => 'IVA',
        'des1' => ' en el sitio web: ',
        'mesg' => array('La busqueda no dio resultados!',
            'Inserte al menos 2 caracteres!',
            'Cambiando cliente / proveedor'
        ),
        'errors' => array('Seleccione el cliente!',
            'Seleccione el tipo de pago',
            'Habilitar la extensi&oacute;n php_imap en php.ini para importar pedidos'
        ),
    ),
    "select_effett.php" =>
    array(0 => 'Imprimir Cuentas',
        'title' => 'Select for view and/or print Bank receipts and Bills',
        'ins_this' => 'Issue bill of exchange to:',
        'upd_this' => 'Update bill of exchange to: ',
        'del_this' => 'Borrar cuenta de cambio',
        'sourcedoc' => 'Documento de origen',
        'source' => 'Origen',
        'link_1' => 'Crear cuenta desde Facturas',
        'link_2' => 'Nueva cuenta de cambio',
        'link_3' => 'Cuentas de contabildad para cambio',
        'link_4' => 'Imprimir Cuenta de cambio',
        'link_5' => 'Cuentas para reporte de cambio',
        'link_6' => 'Crear archivo Ri.Ba.',
        'link_7' => 'Crear archivo MAV',
        'report' => 'Lista de cuentas de cambio',
        'mesg' => array('La busqueda no dio resultados!',
            'Inserte al menos 2 caracteres!',
            'Cambiando cliente'
        ),
        'errors' => array('Incorrect date!',
            'The start date is later than the final',
            'Bill start number is greater than the final number!',
            'Invoice date is later than issue date!',
            'Issue date is later than expiry date!',
            'Invalid bill number ',
            'Select customer',
            'Invalid amount',
            'Select the bank support',
            'Select payment method'
        ),
        'progre' => 'Number',
        'type' => 'Tipo',
        'type_pay' => array('B' => 'Bank receipt', 'T' => 'Promissory', 'V' => 'MAV'),
        'clfoco' => 'Cliente',
        'date_emi' => 'Date of Issue',
        'numfat' => 'Number of invoice',
        'vat_section' => 'IVA section',
        'date_doc' => 'Data Factura',
        'totfat' => 'Factura amount',
        'salacc' => 'Dep&oacute;sito y el Equilibrio',
        'salacc_value' => array('C' => 'Dep&oacute;sito', 'S' => 'El equilibrio'),
        'impeff' => 'Cuenta amount',
        'status' => 'Estado',
        'cigcup' => 'CIG e CUP',
        'date_exp' => 'Expiry date',
        'account_id' => 'Contabilidad nombre',
        'pagame' => 'Metodo de pago',
        'banapp' => 'Bank support',
        'banacc' => 'Bank credit',
        'num_ini' => 'Numero de cuenta inicio  ',
        'date_ini' => 'Fecha de vencimiento inicial ',
        'num_fin' => 'Numero de cuenta final',
        'date_fin' => 'Fecha de vencimiento final ',
        'type_value' => array('B' => 'Recibos bancarios', 'T' => 'Giros-cuentas', 'V' => 'MAV'),
        'header' => array('Num' => '', 'Fecha de vencimiento' => '', 'Cantidad' => '',
            'Cliente' => '', 'Factura' => '', 'Banco' => ''
        )
    ),
    "report_doctra.php" =>
    array('title' => 'Bills of VAT section: ',
        'ddt_type' => array("T" => "sale",
            "V" => "to vision",
            "Y" => "triangulation",
            "S" => "Notula di Servizio", //Notula
            "DDR" => "returned from supplier",
            "DDL" => "to exeternal processing"
        ),
        'header' => array(
            "ID" => 'id_tes',
            "Number" => "numdoc",
            "Type" => 'ddt_type',
            "Date" => "datemi",
            "Customer" => "ragso1",
            "Status" => "",
            "Print" => "",
            "Mail" => "",
            "Origin" => "",
            "Delete" => ""
        ),
        'to_invoice' => 'invoiceable',
        'print_invoice' => 'Printing deferred invoice',
        'print_ddt' => 'Print bill',
        'print_lot' => 'Print certified',
        'from_suppl' => 'Bill to supplier',
        'doc_returned' => 'Reso da c/visione',
        'delete_returned' => 'Elimina il reso',
        'view_ord' => 'order view',
        'acc_entry' => 'view accounting entry of deferred invoice',
        'no_mail' => 'Email not present',
        'mail_alert0' => 'Invio documento con email',
        'mail_alert1' => 'Hai scelto di inviare una e-mail all\'indirizzo: ',
        'mail_alert2' => 'con allegato il seguente documento di vendita:',
        'report_alert0' => 'Mostra tutti i documenti',
        'report_alert1' => 'Sicuro di voler mostrare tutti i documenti?'
    ),
    "emissi_fatdif.php" =>
    array('title' => 'Selezione per la fatturazione dei Documenti di Trasporto della sezione IVA ',
        'ddt_type' => array("T" => "vendita",
            "V" => "c/visione",
            "Y" => ""   //triangolazione"
        ),
        'mesg' => array('La ricerca non ha dato risultati!',
            'Inserire almeno 2 caratteri!',
            'Cambia cliente'
        ),
        'errors' => array('Una data  non &egrave; corretta!',
            'La data di emissione non pu&ograve; essere antecedente alla data dell\'ultimo DdT !',
            'La data di inizio dei DdT da emettere non pu&ograve; essere successivo alla data dell\'ultimo!',
            'L\'ultimo documento emesso ha una data successiva a quella di emissione!',
            'La data di emissione precede quella dell\'ultima fattura emessa',
            'aut_pay' => 'Pagamento che prevede l\'incasso automatico',
            'no_bank' => 'ATTENZIONE! MANCA LA BANCA D\'APPOGGIO',
            'cust_pay' => 'Cliente con diversi pagamenti',
        ),
        'cliente' => 'Cliente: ',
        'date_exe' => 'Data di emissione ',
        'date_ini' => 'Data inizio periodo ',
        'date_fin' => 'Data fine periodo ',
        'doc_type' => ' Tipo Documenti',
        'traspo' => 'SPESE DI TRASPORTO',
        'incasso' => 'SPESE INCASSO',
        'n_inv' => ' Fatturabili nel periodo',
        'add_invoice' => 'Verrà generata la FATTURA DIFFERITA N.',
        'preview_inv' => 'Anteprima di fatturazione',
        'submit_inv' => 'CONFERMA LA GENERAZIONE DELLE FATTURE COME DA ANTEPRIMA'
    ),
    "select_partner_status.php" =>
    array('title' => 'Selezione per la visualizzazione e/o la stampa dello scadenzario dei clienti',
        'print_title' => 'SUPPLIERS DATETABLE ',
        'errors' => array('La data  non &egrave; corretta!',
            'err' => 'Ci sono degli errori che impediscono la stampa'
        ),
        'date_ini' => 'Data di riferimento ',
        'header' => array('ID' => '', 'Importo apertura' => '', 'Data Scadenza' => '', 'Importo chiusura' => ''
            , 'Data chiusura' => '', 'Giorni di esposizione' => '', 'Stato' => ''
        ),
        'status_value' => array(0 => 'APERTA', 1 => 'CHIUSA', 2 => 'ESPOSTA', 3 => 'SCADUTA', 9 => 'ANTICIPO')
    ),
    "report_schedule.php" =>
    array('title' => 'Lista dei movimenti delle partite',
        'header' => array('ID' => 'id',
            'Identificativo partita' => "id_tesdoc_ref",
            'Movimento contabile apertura (documento)' => "id_rigmoc_doc",
            'Movimento contabile chiusura (pagamento)' => "id_rigmoc_pay",
            'Importo' => "amount",
            'Scadenza' => "expiry",
            'status_value' => array(0 => 'OPEN', 1 => 'CLOSED', 2 => 'RISK', 3 => 'EXPIRED', 9 => 'ANTICIPO')
        ),
    ),
    "select_schedule.php" =>
    array('title' => 'Selezione per la visualizzazione e/o la stampa delle partite aperte',
        'mesg' => array('La ricerca non ha dato risultati!',
            'Inserire almeno 2 caratteri!',
            'Cambia cliente/fornitore'
        ),
        'errors' => array('La data  non &egrave; corretta!',
            'Non sono stati trovati movimenti!'
        ),
        'account' => 'Cliente ',
        'orderby' => 'Ordina per: ',
        'orderby_value' => array(0 => 'Scadenza crescente', 1 => 'Scadenza decrescente',
            2 => 'Cliente crescente', 3 => 'Cliente decrescente'
        ),
        /** ENRICO FEDELE */
        /* Aggiunto header per ultima colonna della tabella, per abbellire il layout */
        'header' => array('Cliente' => '', 'ID Partita' => '', 'Status' => '', 'Mov.Cont.' => '', 'Descrizione' => '',
            'N.Doc.' => '', 'Data Doc.' => '', 'Data Reg.' => '', 'Dare' => '', 'Avere' => '',
            'Scadenza' => '', 'Opzioni' => ''
        ),
        /** ENRICO FEDELE */
        'status_value' => array(0 => 'CLOSE', 1 => 'OPEN', 2 => 'RISK', 3 => 'EXPIRED', 9 => 'ANTICIPO'),
        'total_open' => 'Todal partidas abiertas'
    ),
    "delete_schedule.php" =>
    array('title' => 'Cancellazione movimenti chiusi dello scadenzario',
        'ragsoc' => 'Cliente',
        'id_tesdoc_ref' => 'Identificativo partita',
        'descri' => 'Descrizione',
        'amount' => 'Importo'
    ),
    "select_evaord.php" =>
    array('title' => 'Order picking of customer',
        'errors' => array('Non &egrave; stato selezionato un cliente',
            'Non ci sono righi',
            'Non ci sono righi inevasi per generare il documento selezionato',
            'Select payment method',
            'Incorrect date of issue',
            'Incorrect start date of transport',
            'Start date of transport prior to the issue date',
            'YOU HAVE NOT DONE THE CLOSING DAY OF THE CASH REGISTER TO DO BEFORE YOU GIVE A NEW ONE!'
        ),
        'customer' => 'Customer',
        'search_customer' => array('The search yielded no results!',
            'Insert at least 2 characters!',
            'Changing customer',
            'Choice customer',
            ' F.C.:',
            'Anonymous'
        ),
        'indspe' => 'Address',
        'seziva' => 'VAT Section',
        'destin' => 'Destination',
        'banapp' => 'Bank',
        'listin' => 'Price list n.',
        'datemi' => 'Date ',
        'initra' => 'Start date of transport ',
        'traspo' => 'Transport ',
        'spediz' => 'Delivery ',
        'portos' => 'Rendered port ',
        'imball' => 'Pack ',
        'vettor' => 'Shippers ',
        'sconto' => 'Discount',
        'pagame' => 'Payment',
        'preview_title' => 'BACKLOG:',
        'from' => 'from Order n.',
        'del' => ' of ',
        'upd_ord' => ' Updtae order',
        'id_agente' => 'Agent ',
        'codart' => 'Code',
        'descri' => 'Description',
        'unimis' => 'M.U.',
        'quanti' => 'Quantity',
        'prezzo' => 'Price',
        'provvigione' => '%Ag.Com',
        'amount' => 'Amount',
        'taxable' => 'Taxable',
        'issue_fat' => 'Issue with invoice',
        'issue_ddt' => 'Issue with delivery note',
        'issue_cor' => 'Issue with ticket',
        'checkbox' => 'This checkbox must be selected to process the row',
        'alert1' => '&sup1; Section IVA choice is not one normally used for the issuance of immediately invoice',
        'alert2' => '&sup1; The selected section IVA may not coincide with what will be used for the immediate issuance of the invoice for your choice will be equal to the last emitted.'
    ),
    "select_partner_status.php" =>
    array('title' => 'Selezione per la visualizzazione e/o la stampa dello scadenzario dei clienti',
        'print_title' => 'SCADENZARIO CLIENTI ',
        'errors' => array('La data  non &egrave; corretta!',
            'err' => 'Ci sono degli errori che impediscono la stampa'
        ),
        'date_ini' => 'Data di riferimento ',
        'header' => array('ID' => '', 'Importo apertura' => '', 'Data Scadenza' => '', 'Importo chiusura' => ''
            , 'Data chiusura' => '', 'Giorni esposizione' => '', 'Stato' => ''
        ),
        'status_value' => array(0 => 'APERTA', 1 => 'CHIUSA', 2 => 'ESPOSTA', 3 => 'SCADUTA', 9 => 'ANTICIPO'),
        'remove' => 'Elimina tutte le partite chiuse di '
    ),
    "customer_payment.php" =>
    array('title' => 'Riscossione credito da cliente (chiusura partita/e)',
        'errors' => array('La data  non &egrave; corretta!',
            'err' => 'Ci sono degli errori che impediscono la stampa'
        ),
        'partner' => 'Cliente ',
        'date_ini' => 'Data di registrazione',
        'target_account' => "Conto per l'incasso: ",
        'partner' => 'Cliente: ',
        'print_ticket' => "Stampa ricevuta: ",
        'accbal' => 'Saldo risultante dai movimenti contabili: ',
        'paymovbal' => 'Saldo risultante dalle partite aperte: ',
        'header' => array('ID' => '', 'Importo apertura' => '', 'Data Scadenza' => '', 'Importo chiusura' => ''
            , 'Data chiusura' => '', 'Giorni esposizione' => '', 'Stato' => ''
        ),
        'status_value' => array(0 => 'APERTA', 1 => 'CHIUSA', 2 => 'ESPOSTA', 3 => 'SCADUTA', 9 => 'ANTICIPO'),
        'header' => array('ID' => '', 'Importo apertura' => '', 'Data Scadenza' => '', 'Importo chiusura' => ''
            , 'Data chiusura' => '', 'Giorni esposizione' => '', 'Stato' => '', 'Riscuoti' => ''
        ),
        'mesg' => array('La ricerca non ha dato risultati!',
            'Inserire almeno 2 caratteri!',
            'Cambia cliente',
            'Il saldo contabile è diverso da quello dello scadenzario,<br> se vuoi registrare la riscossione di un documento presente solo in contabilità fallo da qui:',
            'Nessun importo è stato riscosso!',
            "Non è stato selezionato il conto per l'incasso",
            'Stai tentando di inserire il pagamento di un cliente senza movimenti'
        ),
    ),
    "print_customer_payment_receipt.php" =>
    array('title' => 'RISCOSSIONE CREDITO DA ',
        'id_tesdoc_ref' => 'ID Partita',
        'descri' => 'Descrizione',
        'numfat' => 'Numero fattura',
        'datfat' => 'Data fattura',
        'amount' => 'Importo riscosso',
        'tot' => 'TOTALE DELLA RISCOSSIONE',
    ),
    "report_fae_sdi.php" =>
    array('title' => 'TRAFFICO DATI FATTURAZIONE ELETTRONICA',
        'table' => 'Tabella su cui stai lavorando: ',
        'id' => 'ID',
        'filename_ori' => 'Nome file primo invio',
        'numfat' => 'N.<br>fattura',
        'codice' => 'Cod. cliente',
        'ragso1' => 'Amministrazione',
        'exec_date' => 'Data di esecuzione ',
        'received_date' => 'Data ricezione ',
        'delivery_date' => 'Data consegna ',
        'filename_son' => 'Nome file padre',
        'id_SDI' => 'ID SDI',
        'filename_ret' => 'Nome file di ritorno',
        'mail_id' => 'UID della mail',
        'flux_status' => 'Stato',
        'flux_status_value' => array('' => 'Generato',
            '#' => 'Non ancora inviata',
            '@' => 'Inviata',
            'NS' => 'Notifica scarto',
            'MC' => 'Mancata Consegna',
            'RC' => 'Ricevuta consegna',
            'NE' => 'Notifica esito',
            'DT' => 'Decorrenza termini'),
        'progr_ret' => 'Progr.',
        'flux_descri' => 'Descrizione',
		'checkfae' => 'Controlla notifiche e aggiorna lo stato delle fatture elettroniche',
        'doc_type_value' => array('FAD' => 'FATTURA DIFFERITA',
            'FAI' => 'FATTURA IMMEDIATA',
            'FAA' => 'FATTURA D\'ACCONTO',
            'FAP' => 'PARCELLA',
            'FAQ' => 'PARCELLA D\'ACCONTO',
            'FNC' => 'NOTA CREDITO',
            'FND' => 'NOTA DEBITO',
            'VCO' => 'FATTURA ALLEGATA A SCONTRINO',
            'VRI' => 'RICEVUTA',
        ),
        'mail_alert0' => 'Invio mail pacchetto fatture elettroniche',
        'mail_alert1' => 'all\'indirizzo: ',
        'mail_alert2' => 'con allegato il seguente file zip:',
        'send_alert0' => 'Inoltro pacchetto fatture elettroniche',
        'send_alert1' => 'tramite la libreria: ',
        'send_alert2' => 'con il seguente file zip:',
    ),
    "admin_destinazioni.php" =>
    array('title' => 'Gestione degli indirizzi di destinazione',
        'ins_this' => 'Inserimento destinazione',
        'upd_this' => 'Modifica la destinazione con cod.',
        'errors' => array('Devi associare la destinazione ad una anagrafica',
            "Manca l'indirizzo",
            "Manca il cap",
            "Manca la citta'"
        ),
        'codice' => "codice",
        'unita_locale1' => "Unita' Locale 1",
        'unita_locale2' => "Unita' Locale 2",
        'indspe' => 'Indirizzo',
        'capspe' => 'Codice Postale',
        'citspe' => 'Citt&agrave; - Provincia',
        'prospe' => 'Provincia',
        'country' => 'Nazione',
        'telefo' => 'Telefono',
        'fax' => 'Fax',
        'cell' => 'Cellulare',
        'e_mail' => 'e mail',
        'fe_cod_ufficio' => 'Cod.Univoco Ufficio (fatt.elettronica)',
        'status' => 'Visibilit&agrave; alla ricerca',
        'status_value' => array('' => 'Attiva', 'HIDDEN' => 'Disabilitata'),
        'annota' => 'Annotazioni',
        'id_anagra' => 'Destinazione legata a',
        'mesg' => array('La ricerca non ha dato risultati!',
            'Inserire almeno 2 caratteri!',
            'Cambia anagrafica'),
    ),
    "select_sconti_articoli.php" =>
    array('title' => 'Sconti clienti/articoli',
        'errors' => array("Manca il cliente", "Manca l'articolo", "Inserire il prezzo netto e/o lo sconto", "Sconto fuori limiti", "Prezzo netto fuori limiti"),
        "Cliente",
        "Inserire min. 2 caratteri",
        "Tutti i clienti!",
        "Non &egrave; stato trovato nulla",
        "Selezione Articolo ",
        "%Sconto",
        "Prezzo netto<br><i>(ha priorit&agrave;)</i>",
        'elenca' => 'Elenca',
        'inserisci' => 'Inserisci/Modifica',
        'cod_art' => 'Articolo',
        'partner' => 'Cliente ',
        'mesg' => array('La ricerca non ha dato risultati!',
            'Inserire almeno 1 carattere!',
            'Cambia articolo',
            'Inserimento effettuato',
            'Modifica apportata',
            'Attenzione!!! Eliminazione sconto',
            'Sei sicuro di voler rimuovere?',
            "Se sei sicuro conferma l'eliminazione"
        ),
        'header' => array(
            'Cod. Cli.' => '',
            'Cliente' => '',
            'Cod. Art.' => '',
            'Articolo' => '',
            'Prezzo netto' => '',
            '%Sconto' => '',
            'Elimina' => ''),
    ),
    "delete_sconto_articolo.php" =>
    array('title' => 'Cancella sconto per articolo',
        'header' => array('Cliente', 'Articolo', '%Sconto', 'Prezzo netto'),
        'mesg' => array(
            'Attenzione!!! Eliminazione sconto',
            'Sei sicuro di voler rimuovere?',
            "Se sei sicuro conferma l'eliminazione",
            "Indietro",
            "ELIMINA !",
            "Num. righe eliminate: "
        ),
    ),
    "select_sconti_raggruppamenti.php" =>
    array('title' => 'Sconti clienti/raggruppamenti statistici',
        'errors' => array("Manca il cliente", "Manca il raggruppamento", "Manca lo sconto", "Sconto fuori limiti"),
        "Cliente",
        "Inserire min. 2 caratteri",
        "Tutti i clienti!",
        "Non &egrave; stato trovato nulla",
        "Selezione Raggruppamento ",
        "%Sconto",
        'elenca' => 'Elenca',
        'inserisci' => 'Inserisci/Modifica',
        'cod_ragstat' => 'Raggruppamento',
        'partner' => 'Cliente ',
        'mesg' => array('La ricerca non ha dato risultati!',
            'Inserire almeno 1 carattere!',
            'Cambia raggruppamento',
            'Inserimento effettuato',
            'Modifica apportata',
            'Attenzione!!! Eliminazione sconto',
            'Sei sicuro di voler rimuovere?',
            "Se sei sicuro conferma l'eliminazione"
        ),
        'header' => array(
            'Cod. Cli.' => '',
            'Cliente' => '',
            'Cod. Ragg.' => '',
            'Raggruppamento' => '',
            '%Sconto' => '',
            'Elimina' => ''),
    ),
    "delete_sconto_raggruppamento.php" =>
    array('title' => 'Cancella sconto per raggruppamento statistico',
        'header' => array('Cliente', 'Raggruppamento', '%Sconto'),
        'mesg' => array(
            'Attenzione!!! Eliminazione sconto',
            'Sei sicuro di voler rimuovere?',
            "Se sei sicuro conferma l'eliminazione",
            "Indietro",
            "ELIMINA !",
            "Num. righe eliminate: "
        ),
    ),
    "select_analisi_avanzamento_per_fornitore.php" =>
    array('title' => 'Analisi avanzamento venduto/acquistato x fornitore',
        "Data Vendite inizio",
        "Data Vendite fine",
        "Data Acquisti inizio",
        "Data Acquisti fine",
        'preview' => 'Anteprima',
        'print' => 'Stampa',
        'totale' => 'TOTALE',
        'partner' => 'Cliente ',
        'errors' => array('Inserire il cliente'
        ),
        'mesg' => array('La ricerca non ha dato risultati!',
            'Inserire almeno 2 caratteri!',
            'Cambia cliente',
        ),
        'header' => array('Cod. fornitore' => '', 'Fornitore' => '', 'Acquistato' => '', 'Venduto' => '',
            'Avanzamento %' => ''
        ),
    ),
    "select_evacmr.php" =>
    array('doc_name' => array("CMR" => "CMR"),
        'title' => 'Evasione ordine/preventivo cliente',
        'errors' => array('Non &egrave; stato selezionato un cliente',
            'Non ci sono righi',
            'Non ci sono righi inevasi per generare il documento selezionato',
            'Non hai selezionato la modalit&agrave; di pagamento',
            'La data di emissione non &egrave; corretta',
            'La data di inizio trasporto non &egrave; corretta',
            'La data di inizio trasporto non pu&ograve; essere precedente alla data di emissione',
            'NON HAI ESEGUITO LA CHIUSURA GIORNALIERA DEL REGISTRATORE DI CASSA FALLO PRIMA DI EMETTERNE UNO!!!',
            "C'è almeno un DdT già emesso con data successiva a quella scelta per l'evasione",
            "C'è almeno uno scontrino emesso con data successiva a quella scelta per l'evasione",
            "C'è almeno una fattura già emessa con data successiva a quella scelta per l'evasione"
        ),
        'customer' => 'Cliente',
        'search_customer' => array('La ricerca non ha dato risultati!',
            'Inserire almeno 2 caratteri!',
            'Cambia cliente',
            'Scegli un cliente',
            ' C.F.:',
            'Anonimo'
        ),
        'indspe' => 'Indirizzo',
        'seziva' => 'Sezione IVA',
        'destin' => 'Destinazione',
        'banapp' => 'Banca',
        'listin' => 'Listino n.',
        'datemi' => 'Data ',
        'initra' => 'Inizio trasporto ',
        'traspo' => 'Trasporto ',
        'spediz' => 'Spedizione ',
        'portos' => 'Porto/Resa ',
        'imball' => 'Imballo ',
        'vettor' => 'Vettore ',
        'sconto' => 'Sconto',
        'pagame' => 'Pagamento',
        'preview_title' => 'DA EVADERE:',
        'from' => 'dal ',
        'del' => ' del ',
        'upd_ord' => ' Modifica il preventivo/ordine',
        'id_agente' => 'Agente ',
        'codart' => 'Codice',
        'descri' => 'Descrizione',
        'unimis' => 'U.M.',
        'quanti' => 'Quantità ',
        'prezzo' => 'Prezzo',
        'provvigione' => '%Prov',
        'amount' => 'Importo',
        'taxable' => 'Imponibile',
        'issue_fat' => 'Evadi con Fattura Immediata',
        'issue_ddt' => 'Evadi con Documento di Trasporto',
        'issue_cor' => 'Evadi con Corrispettivo',
        'checkbox' => 'Questa checkbox dev\'essere selezionata per evadere il rigo',
        'alert1' => '&sup1; La sezione IVA scelta non &egrave; quella<br/>normalente usata per<br/>l\'emissione delle Fatture immediate.',
        'alert2' => '&sup1; La sezione IVA selezionata potrebbe non<br/>coincidere con quella che verr&agrave; usata per<br/>l\'emissione della Fattura immediata che per<br/>Vostra scelta sar&agrave; uguale all\'ultima emessa.'
    ),
    "asset_sales.php" =>
    array('title' => 'Fattura di vendita cespite-bene ammmortizzabile a',
        'mesg' => array('La ricerca non ha dato risultati!', 'Inserire almeno 2 caratteri', 'Cambia cliente'),
        'info' => array('gg_to_year_end_1' => ' giorni mancano alla fine dell\'anno ',
            'gg_to_year_end_2' => ' quando potranno essere ammortizzati € '),
        'err' => array('regdat' => 'La data di registrazione precede quella della fattura',
            'numfat' => 'Non è stato introdotto il numero della fattura',
            'clfoco' => 'Non è stato scelto il fornitore',
            'pagame' => 'Non è stata scelta la modalità di pagamento',
            'datfat' => 'La data fattura è sbagliata',
            'descri' => 'Non è stata inserita una descrizione del bene acquistato',
            'ss_amm_min' => 'Non è stata inserita la sottospecie della tabella Ammortamenti Ministeriali'),
        'war' => array('update' => 'Sono consentite le modifiche solo ad alcuni campi perché'
            . ' l\'inserimento di questo cespite ha creato sul piano dei conti un sottoconto su ognuno dei'
            . ' tre mastri scelti per l\'immobilizzazione, il fondo ammortamento e per le quote di costi'
            . ' annuali per ammortamenti. Inoltre è stata fatta una registrazione contabile ed IVA '
            . ' pertanto se volete modificare gli altri dati dovrete agire in prima nota sul seguente'
            . ' movimento contabile'),
        'seziva' => "Sez. IVA",
        'indspe' => "Indirizzo",
        'datfat' => "Data fattura",
        'datreg' => "Data registr.",
        'pagame' => "Pagamento",
        'valamm' => "% ammortamento",
        'numfat' => "Numero fatt.",
        'id' => 'Bene da alienare',
        'mas_found_assets' => 'Fondo ammort.',
        'mas_cost_assets' => 'Costo ammort.',
        'des_fixed_assets' => 'Immobilizzazione ',
        'des_found_assets' => 'Fondo ammortamento ',
        'des_cost_assets' => 'Ammortamento ',
        'id_no_deduct_vat' => 'IVA indetraibile',
        'no_deduct_vat_rate' => '% IVA indetraibile',
        'acc_no_deduct_cost' => 'Costo indeducibile',
        'no_deduct_cost_rate' => '% quota indeducibile',
        'descri' => 'Descrizione bene',
        'quantity' => 'Quantità',
        'unimis' => 'Unità Misura',
        'a_value' => 'Prezzo',
        'codvat' => 'I.V.A.',
        'amount' => 'Costo totale del bene € ',
        'ss_amm_min' => 'Ammort.Minister.',
        'super_ammort' => '% Super ammortamento'
    ),
    "fae_packaging.php" =>
    array('title' => 'Genera un file zip contenente una o più fatture elettroniche di vendita',
        'errors' => array('Data non corretta',
            'Non ci sono fatture nell\'intervallo selezionato'
        ),
        'vat_section' => ' della sezione IVA n.',
        'date' => 'Fino al :',
        'vat_register' => 'Registro IVA ',
        'vat_register_value' => array('F' => 'delle Fatture di Vendita', 'V' => 'dei Corrispettivi'),
        'proini' => 'Protocollo iniziale',
        'profin' => 'Protocollo finale',
        'preview' => 'Le fatture elettroniche sotto indicate genereranno un pacchetto con nome: ',
        'date_reg' => 'Data',
        'protoc' => 'Protocollo',
        'doc_type' => 'Tipo',
        'doc_type_value' => array('FAD' => 'FATTURA DIFFERITA',
            'FAI' => 'FATTURA IMMEDIATA',
            'FAA' => 'FATTURA D\'ACCONTO',
            'FAP' => 'PARCELLA',
            'FAQ' => 'PARCELLA D\'ACCONTO',
            'FNC' => 'NOTA CREDITO',
            'FND' => 'NOTA DEBITO',
            'VCO' => 'FATTURA ALLEGATA A SCONTRINO',
            'VRI' => 'RICEVUTA',
        ),
        'customer' => 'Cliente',
        'pec' => "all'indirizzo PEC: ",
        'sdi' => 'al Codice SDI: ',
        'taxable' => 'Imponibile',
		'no_tax'=>'Non Imp., Escl., ecc.',
        'vat' => 'I.V.A.',
        'tot' => 'Totale',
        'mail_alert0' => 'Invio mail per richiesta codice SdI o PEC',
        'mail_alert1' => 'all\'indirizzo: '
    ),
    "delete_zip_package.php" =>
    array('title' => 'Elimina il pacchetto di fatture elettroniche nome file: ',
        'head' => 'Il pacchetto zip contiene i seguenti XML delle fatture elettroniche (che non saranno eliminate):',
        'danger' => 'ATTENZIONE!!! Questo file risulta essere già stato inviato all\'intermediario! Eliminare solo nel caso in cui lo stesso non abbia provveduto alla trasmissione delle fatture in esso contenute al SdI',
        'customer' => 'Cliente',
        'doc_type_value' => array('FAD' => 'FATTURA DIFFERITA',
            'FAI' => 'FATTURA IMMEDIATA',
            'FAA' => 'FATTURA D\'ACCONTO',
            'FAP' => 'PARCELLA',
            'FAQ' => 'PARCELLA D\'ACCONTO',
            'FNC' => 'NOTA CREDITO',
            'FND' => 'NOTA DEBITO',
            'VCO' => 'CORRISPETTIVO',
            'VRI' => 'RICEVUTA',
        ),
		'danger_confirm'=>'Sono consapevole. Eliminalo comunque!'
    ),
    "acquire_external_invoice.php" =>
    array('title' => 'Importa file XML fattura elettronica di vendita',
		'btn_acquire'=>'ACQUISISCI!',
        'war' => array(
            'ok_suppl' => 'Il cliente è già in archivio',
            'no_suppl' => 'Ho già questa anagrafica ma è un nuovo cliente',
            'no_anagr' => "Di questo nuovo cliente non ho l'anagrafica, utilizzerò questi dati per crearla",
            'no_db' => "Di questo file è stato fatto solo l'upload ma non è stata confermata la registrazione"
        ),
        'err' => array(
            'filmim' => 'Il file deve essere nel formato XML o P7M',
            'invalid_xml' => 'Il contenuto del file non è un XML valido',
            'invalid_fae' => 'Il contenuto del file XML non sembra essere una fattura elettronica',
            'file_exists' => 'Un file con questo nome è stato già stato acquisito',
            'not_mine' => 'La fattura che stai tentando di importare non è stata emessa da questa azienda',
            'no_upload' => 'File non inviato',
            'no_pagame' => 'Non hai selezionato la modalità di pagamento',
            'no_codric' => 'Non hai selezionato il codice conto di costo',
            'no_codvat' => 'Non hai selezionato l\'aliquota IVA',
            'same_content' => 'Una fattura di questo fornitore, contenente lo stesso numero e data fattura, è già stato acquisito'
        ),
        'head_text1' => "La fatture elettronica: ",
		'head_text2' => " che stai per acquisire è visibile in fondo.<br/> In questo form ti proponiamo di imputare i ricavi secondo quanto contenuto sugli archivi, e ti invitiamo a controllare ed eventualmente apportare le modifiche opportune. Avrai comunque la possibilità di modificarla sia prima che dopo averla contabilizzata agendo attraverso le apposite interfacce. Dopo l'acquisizione verrai portato sulla lista delle fatture di vendita già inserite",
        'seziva' => 'Sezione IVA',
        'datreg' => 'Data Registrazione',
		'pagame'=>'Modalità di pagamento',
        'nrow' => 'Rigo',
        'codart' => 'Codice',
        'descri' => 'Descrizione',
        'unimis' => 'U.M.',
        'quanti' => 'Quantità ',
        'prezzo' => 'Prezzo',
        'amount' => 'Importo',
        'sconto' => 'Sconto',
        'taxable' => 'Imponibile',
        'tax' => 'I.V.A.',
        'operation_type' => 'Tipo oper.',
        'conto' => 'Conto',
	),
	);
?>