<?php
/*
  --------------------------------------------------------------------------
  GAzie - MODULO 'VACATION RENTAL'
  Copyright (C) 2022-present - Antonio Germani, Massignano (AP) - telefono +39 340 50 11 912
  (http://www.programmisitiweb.lacasettabio.it)

  --------------------------------------------------------------------------
  --------------------------------------------------------------------------
  GAzie - Gestione Azienda
  Copyright (C) 2004-present - Antonio De Vincentiis Montesilvano (PE)
  (http://www.devincentiis.it)
  <http://gazie.devincentiis.it>
  --------------------------------------------------------------------------
  Questo programma e` free software;   e` lecito redistribuirlo  e/o
  modificarlo secondo i  termini della Licenza Pubblica Generica GNU
  come e` pubblicata dalla Free Software Foundation; o la versione 2
  della licenza o (a propria scelta) una versione successiva.

  Questo programma  e` distribuito nella speranza  che sia utile, ma
  SENZA   ALCUNA GARANZIA; senza  neppure  la  garanzia implicita di
  NEGOZIABILITA` o di  APPLICABILITA` PER UN  PARTICOLARE SCOPO.  Si
  veda la Licenza Pubblica Generica GNU per avere maggiori dettagli.

  Ognuno dovrebbe avere   ricevuto una copia  della Licenza Pubblica
  Generica GNU insieme a   questo programma; in caso  contrario,  si
  scriva   alla   Free  Software Foundation, 51 Franklin Street,
  Fifth Floor Boston, MA 02110-1335 USA Stati Uniti.
  --------------------------------------------------------------------------
 */

$strScript = array(
    "user_login.php"=>
      array('warning_sess'=>'ATTENTION : Les sessions ont été désactivées dans votre navigateur. Vous devez les activer ou changer de navigateur',
        'login'=>'Accès',
        'log_instr'=>'Veuillez saisir votre e-mail et votre mot de passe',
        'forgot'=>'Mot de passe oublié?',
        'log_in'=>'Se connecter',
        'required'=>'Nécessaire',
        'pw_recover'=>'Récupérer mot de passe',
        'recover'=>'Récupérer',
        'wrong_mail'=>'Un email a été envoyé pour récupérer le mot de passe. Si vous ne l\'avez pas reçue, cela signifie que vous vous êtes trompé d\'adresse, ou qu\'elle s\'est retrouvée dans le dossier spam, ou que vous n\'êtes pas un utilisateur.',
        'body_mail_recover'=>'Bonjour, </br>Pour définir le mot de passe, cliquez sur ce lien: ',
        'pw_confirm'=>'Confirmer mot de passe',
        'pw_repeat'=>'Réécrire le mot de passe comme ci-dessus',
        '2fa_title'=>'Authentification à double facteur',
        '2fa_desc'=>'Entrez le code qui vient de vous être envoyé par e-mail (si vous ne l\'avez pas reçu, vérifiez dans le dossier spam).',
        '2fa_body_mail'=>'Pour accéder à votre page utilisateur, utilisez ce code: ',
        'wrong_pw'=>'Mauvais mot de passe.',
        'too_er'=>'Trop de mauvaises tentatives. Vous êtes bloqué!',
        'invalid_keys'=>'Identifiants erronés.',
        'invalid_mail'=>'Adresse incorrecte.',
        'no_user'=>'Vous n\'avez pas été trouvé dans les archives : contactez l\'administrateur.',
        'no_pw_yet'=>'Vous n\'avez pas encore défini votre mot de passe : utilisez la récupération de mot de passe pour le saisir',
		'no_json_anagra'=>'Vous n\'avez jamais saisi de mot de passe, entrez-en un en cliquant sur Mot de passe oublié ou contactez l\'administrateur.',
        'reset_success'=>'Le mot de passe a été défini ; il est possible de se connecter avec le nouveau mot de passe.',
        'dashboard' => 'Panneau de commande'
      ),
    "browse_document.php" =>
      array('title' => "Lista dei Documenti/Certificati",
        'errors' => array('Il formato del file non è stato accettato!',
        'Il file è troppo grande!',
        'Il file è vuoto!',
        'Nessun file selezionato'),
        'ins_this' => "Inserisci un Documento e/o Certificato",
        'upd_this' => "Modifica Documento e/o Certificato",
        'ins_this_img' => "Inserisci un'immagine",
        'upd_this_img' => "Modifica immagine",
        'item' => "Articolo di riferimento",
        'table_name_ref' => "Tabella di riferimento",
        'note' => "Didascalia/Appunti/Note",
        'ext' => "Estensione",
        'select' => "Sel.",
        'code' => "Codice"),
	"thanks.php" =>
      array('title' => 'Vacation rental thank you page',
        'thanks' => "THANKS!",
        'booked' => "The reservation has been made.",
        'instr_sent' => "The summary with all the information has been sent to the e-mail address provided.<br>",
        'not_received' => "If you have not received the email and have checked your spam folder, contact the site administrator.",
        'close'=>'This message will close in ',
      ),
    "report_facility.php" =>
      array('title' => 'Lista deglle strutture ricettive',
        'codice' => "Codice",
        'descri' => "Descrizione",
        'ricerca' => "Ricerca",
        'good_or_service' => "Merce-Servizio",
        'good_or_service_value' => array(0=>'Merce',1=>'Servizio',2=>'Composizione'),
        'unimis' => "U.M.",
        'catmer' => "Cat. merc.",
        'preacq' => 'Prezzo acquisto',
        'preve1' => 'Prezzo vend.1',
        'stock' => 'Giacenza',
        'aliiva' => 'IVA',
        'retention_tax' => 'Ritenuta',
        'payroll_tax' => 'Cassa Prev.',
        'barcode' => 'Cod.Barre',
        'clone' => 'Duplica',
        'cosear'=>'aggiungi "%" e invia per ricerca, oppure seleziona',
        'clfoco'=>'Fornitore',
        'lot'=>'Lotto'
      ),
	 "report_extra.php" =>
      array('title' => 'Lista degli extra',
        'codice' => "Codice",
        'descri' => "Descrizione",
        'ricerca' => "Ricerca",
        'good_or_service' => "Merce-Servizio",
        'good_or_service_value' => array(0=>'Merce',1=>'Servizio',2=>'Composizione'),
        'unimis' => "U.M.",
        'catmer' => "Cat. merc.",
        'preacq' => 'Prezzo acquisto',
        'preve1' => 'Prezzo vend.1',
        'stock' => 'Giacenza',
        'aliiva' => 'IVA',
        'retention_tax' => 'Ritenuta',
        'payroll_tax' => 'Cassa Prev.',
        'barcode' => 'Cod.Barre',
        'clone' => 'Duplica',
        'cosear'=>'aggiungi "%" e invia per ricerca, oppure seleziona',
        'clfoco'=>'Fornitore',
        'lot'=>'Lotto'
      ),
    "report_accommodation.php" =>
      array('title' => 'Lista degli alloggi',
        'codice' => "Codice",
        'descri' => "Descrizione",
        'ricerca' => "Ricerca",
        'good_or_service' => "Merce-Servizio",
        'good_or_service_value' => array(0=>'Merce',1=>'Servizio',2=>'Composizione'),
        'unimis' => "U.M.",
        'catmer' => "Cat. merc.",
        'preacq' => 'Prezzo acquisto',
        'preve1' => 'Prezzo vend.1',
        'stock' => 'Giacenza',
        'aliiva' => 'IVA',
        'retention_tax' => 'Ritenuta',
        'payroll_tax' => 'Cassa Prev.',
        'barcode' => 'Cod.Barre',
        'clone' => 'Duplica',
        'cosear'=>'aggiungi "%" e invia per ricerca, oppure seleziona',
        'clfoco'=>'Fornitore',
        'lot'=>'Lotto'
      ),
    "report_booking.php" =>
      array("Elenco delle prenotazioni ",
        "codice",
		'number' => 'Numero prenotazione',
		'weekday_repeat' => 'settimanale',
		'status' => 'Stato',
		'print' => 'settimanale',
		'duplicate' => 'Duplica',
		'delete' => 'Cancella',
		'cancel' => 'Elimina',
		'submit' => 'Inserisci',
		'date' => 'data emissione',
    'booking' => 'Booking n.',
    'of' => 'of',
    'email_give_point' => 'With reference to the reservation in question, we inform you that have been attributed',
    'email_give_point2' => 'points with the following motivation:',
    'email_give_point3' => 'Your current balance is',
    'points' => 'points',
		'title_value' => array('VPR' => 'Preventivi a clienti',
        'VOR' => 'Elenco prenotazioni',
        'VOW' => 'Elenco prenotazioni dal web',
        'VOG' => 'Prenotazioni settimanali del giorno'),
		'type' => 'Tipo',
        'type_value' => array('VPR' => 'Preventivo',
        'VOR' => 'Prenotazione',
        'VOW' => 'Prenotazione web',
        'VOG' => 'Prenotazione settimanale del giorno'),
		'mail_alert0' => 'Invio documento con email',
        'mail_alert1' => 'Hai scelto di inviare una e-mail all\'indirizzo: ',
        'mail_alert2' => 'con allegato il seguente documento di vendita:',
		'search' => 'Search',
    'email_selfchek' => 'In reference to your self check-in we inform you that it is: ',
    'email_selfchek_msg' => 'More advise: '
       ),
    "admin_movmag.php" =>
      array("movimento di magazzino ",
        "Data della registrazione ",
        "Causale ",
        "Cliente",
        "Fornitore",
        "C",
        "F",
        "Articolo",
        "Data documento ",
        "Descrizione doc.",
        "Sconto chiusura ",
        "Unit&agrave; di misura ",
        "Quantit&agrave; ",
        "Prezzo",
        "Sconto su rigo",
        "La data del documento non &egrave; corretta!",
        "La data di registrazione non &egrave; corretta!",
        "La data del documento &egrave; successiva a quella di registazione!",
        "Non &egrave; stato selezionato l'articolo!",
        "La quantit&agrave; non pu&ograve; essere uguale a zero!",
        "Questo movimento può essere modificato esclusivamente dal modulo Registro di campagna!",
        "Articolo con lotto",
        "Gli articoli composti possono essere caricati sono con una produzione!",
        "Si può caricare olio lampante da recupero solo se è sfuso!",
        "Non è stato indicato il recipiente di stoccaggio!",
        "Al consumatore finale si può vendere solo olio confezionato!",
        "Manca il codice operazione SIAN!",
        "La cessione omaggio è solo per olio confezionato!",
        "Lo scarico di morchie può avvenire solo da oli NON confezionati!",
        "Nello storno inventario bisogna indicare se carico o scarico",
        "L'inventario di magazzino deve essere un carico",
        "Non si può fare uno storno ad un inventario che non esiste",
        "Nel recipiente di stoccaggio selezionato non c'è sufficiente quantità",
        "La data di registrazione è precedente all'ultimo movimento inviato al SIAN. Se si conferma, questo movimento non sarà inviato al SIAN",
        "Quantità articolo non sufficiente! Se si conferma si creerà una quantità negativa",
        "La somma dei singoli lotti disponibili non corrisponde alla quantità inserita. Se la giacenza è corretta, allora, prima di inventariare, bisognerà aggiustare manualmente i lotti",
        "Non può uscire un lotto in data precedente alla sua creazione",
         'operat' => 'Operazione',
         'operat_value' => array(-1 => "Scarico", 0 => "Non opera", 1 => "Carico"),
        'cod_operaz_value' => array(11=>'',0=>'S0-Vendita olio a consumatore finale',6=>'S6-Cessione omaggio olio confezionato',7=>'S7-Scarico olio destinato ad altri usi',8=>'S8-Scarico olio autoconsumo',12=>'SP-Perdite o cali di olio',13=>'Q-Separazione morchie'),
        'cop_operazione' => 'Codice operazione SIAN',
        'cod_operaz_value_carico' => array(11=>'',10=>'C10-Carico olio lampante da recupero'),
        'partner' => 'Cliente/Fornitore',
        'del_this' => 'Elimina il movimento di magazzino',
        'amount' => " Valore in ",
        ),
    "report_caumag.php" =>
      array("causali di magazzino ",
        "Lista delle "
      ),
    "admin_catmer.php" =>
      array("categoria merceologica ",
        "Numero ",
        "Descrizione ",
        "Immagine (jpg,png,gif) max 64Kb: ",
        "% di ricarico ",
        "Annotazioni ",
        "codice gi&agrave; esistente!",
        "la descrizione &egrave; vuota!",
        "Il file immagine dev'essere nel formato PNG",
        "L'immagine non dev'essere pi&ugrave; grande di 64Kb",
        "Descrizione estesa",
        "ID riferimento e-commerce",
        'web_url' => 'Web url<br />(es: http://site.com/group.html)',
        'top' => 'Bottone su home ecommerce'
      ),
    "admin_ragstat.php" =>
      array("raggruppamento statistico ",
        "Numero ",
        "Descrizione ",
        "Immagine (jpg,png,gif) max 64kb: ",
        "% di ricarico ",
        "Annotazioni ",
        "codice gi&agrave; esistente!",
        "la descrizione &egrave; vuota!",
        "Il file immagine dev'essere nel formato PNG",
        "L'immagine non dev'essere pi&ugrave; grande di 64Kb",
        'web_url' => 'Web url<br />(es: http://site.com/group.html)'
      ),
    "admin_caumag.php" =>
    array("causale di magazzino ",
        "Codice ",
        "Descrizione ",
        "Dati documento ",
        "Operazione",
        "Aggiorna Esistenza",
        "No",
        "Si",
        "Scarico",
        "Non opera",
        "Carico",
        "Cliente/Fornitore",
        "Cliente",
        "Entrambi",
        "Fornitore",
        "codice gi&agrave; esistente!",
        "la descrizione &egrave; vuota!",
        "il codice dev'essere un numero minore di 99"
      ),
    "genera_movmag.php" =>
      array("Genera movimenti di magazzino da documenti",
        "Data inizio ",
        "Data fine",
        "Azienda senza obbligo di magazzino fiscale!",
        " successiva alla ",
        "  righi sono da traferire in magazzino:",
        " Non ci sono righi da trasferire in magazzino!"),
    "select_giomag.php" =>
      array(0 => 'Stampa giornale di magazzino',
        'title' => 'Selezione per la visualizzazione e/o la stampa del giornale di magazzino',
        'errors' => array('La data  non &egrave; corretta!',
            'La data di inizio dei movimenti contabili da stampare non pu&ograve; essere successiva alla data dell\'ultimo !',
            'La data di stampa non pu&ograve; essere precedente a quella dell\'ultimo movimento!'
        ),
        'date' => 'Data di stampa ',
        'date_ini' => 'Data registrazione inizio  ',
        'date_fin' => 'Data registrazione fine ',
        'mode' => 'Tipo di stampa sul pdf',
        'cover' => 'Stampa copertina',
        'subtitle' => 'Titolo aggiuntivo sul pdf (facoltativo)',
        'mode_value' => array(1 => 'Tutti i movimenti', 2 => 'Solo le entrate', 3 => 'Solo le uscite'),
        'price_value' => array(1 => 'con prezzi', 2 => 'senza prezzi con rag.sociale'),
        'header' => array('Data' => '', 'Causale' => '', 'Descrizione documento' => '' ,
          'Articolo' => '', 'Prezzo' => '', 'Importo' => '', 'UM' => '', 'Quantit&agrave;' => ''
          )
      ),
    "recalc_exist_value.php" =>
    array("Rivalutazione esistenza articoli da movimenti di magazzino",
        "Anno di riferimento",
        "Metodo di rivalutazione, scelto in configurazione azienda",
        "Sono stati movimentati i seguenti",
        "articoli durante il ",
        "Movimenti",
        "Codice",
        "Descrizione",
        "Esistenza",
        "UM acq.",
        "Valore precedente",
        "Valore rivalutato",
        "NON RIVALUTATO vedi nota ",
        "(1) perch&egrave; ci sono degli acquisti negli anni successivi al ",
        "(2) perch&egrave; non ci sono movimenti di acquisto nel ",
        "Non ci sono articoli movimentati!"),
    "inventory_stock.php" =>
    array('title' => "Inventario fisico di magazzino",
        'del' => "del",
        'catmer' => "Categoria Merceologica ",
        'select' => "Sel.",
        'code' => "Codice",
        'descri' => "Descrizione articolo",
        'mu' => "U.M.",
        'load' => "Carico",
        'unload' => "Scarico",
        'value' => "Nuovo valore giacenza",
        'v_a' => "Valore attuale",
        'v_r' => "Valore reale",
        'g_a' => "Giacenza attuale",
        'g_r' => "Giacenza reale",
        'g_v' => "Valore giacenza",
        'noitem' => "Non sono stati trovati articoli in questa categoria merceologica",
        'errors' => array(" La giacenza reale non pu&ograve; essere negativa",
        " Il valore reale non pu&ograve; essere negativo o uguale a zero",
        " Si st&agrave; tentando di fare l'inventario con giacenza attuale e reale entrambe a zero",
        " Per questo articolo è già stato fatto l'inventario nello stesso giorno"),
        'preview_title' => 'Confermando le scelte fatte si registreranno i seguenti movimenti di magazzino:'
    ),
    "select_schart.php" =>
      array(0 => 'Stampa schedari di magazzino',
        'title' => 'Selezione per la visualizzazione e/o la stampa delle schede di magazzino',
        'mesg' => array('La ricerca non ha dato risultati!',
            'Inserire almeno 1 carattere!',
            'Cambia articolo'
        ),
        'errors' => array('La data  non &egrave; corretta!',
            'La data di inizio dei movimenti contabili da stampare non pu&ograve; essere successiva alla data dell\'ultimo !',
            'La data di stampa non pu&ograve; essere precedente a quella dell\'ultimo movimento!',
            'L\'articolo iniziale non pu&ograve; avere un codice successivo a quello finale!',
            'La categoria merceologica iniziale non pu&ograve; avere un codice successivo a quello finale!'
        ),
        'date' => 'Data di stampa ',
        'cm_ini' => 'Categoria merceologica inizio ',
        'art_ini' => 'Articolo inizio ',
        'date_ini' => 'Data registrazione inizio  ',
        'cm_fin' => 'Categoria merceologica fine ',
        'art_fin' => 'Articolo fine ',
        'date_fin' => 'Data registrazione fine ',
        'header' => array('Data' => '', 'Causale' => '', 'Magazzino' => '', 'Descrizione<br \>documento' => '',
            'Prezzo' => '', 'UM' => '', 'Quantit&agrave;' => '',
            'Valore<br \>carico' => '', 'Valore<br \> scarico' => '',
            'Quantit&agrave;<br \>giacenza' => '', 'Valore<br \>giacenza' => ''
        ),
        'tot' => 'Consistenza'
      ),
    "stampa_schart.php" =>
      array(0 => 'SCHEDA DI MAGAZZINO dal ', 1 => ' al ',
        'bot' => 'a riportare : ',
        'top' => 'da riporto :  ',
        'item_head' => array('Codice', 'Cat.Merc', 'Descrizione', 'U.M.', 'ScortaMin.'),
        'header' => array('Data', 'Causale', 'Descrizione documento',
            'Prezzo', 'UM', 'Quantita',
            'Val. carico', 'Val. scarico',
            'Q.ta giacenza', 'Val. giacenza'
        ),
        'tot' => 'Consistenza al '
      ),
    "select_deplia.php" =>
      array('title' => 'Selezione per la stampa del catalogo',
        'mesg' => array('La ricerca non ha dato risultati!',
            'Inserire almeno 1 carattere!',
            'Cambia articolo'
        ),
        'errors' => array('La data  non &egrave; corretta!',
            'L\'articolo iniziale non pu&ograve; avere un codice successivo a quello finale!',
            'La categoria merceologica iniziale non pu&ograve; avere un codice successivo a quello finale!'
        ),
        'date' => 'Data di stampa ',
        'cm_ini' => 'Categoria merceologica inizio ',
        'art_ini' => 'Articolo inizio ',
        'cm_fin' => 'Categoria merceologica fine ',
        'art_fin' => 'Articolo fine ',
        'barcode' => 'Stampa',
        'jumpcat' => 'Cambio pagina al cambio categoria',
        'barcode_value' => array(0 => 'Immagini', 1 => 'Codici a Barre'),
        'listino' => 'Listino',
        'listino_value' => array(1 => ' di Vendita 1', 2 => ' di Vendita 2', 3 => ' di Vendita 3', 4 => ' di Vendita 4', 'web' => ' di Vendita Online')
      ),
    "select_listin.php" =>
      array('title' => 'Selezione per la stampa dei listini',
        'mesg' => array('La ricerca non ha dato risultati!',
            'Inserire almeno 1 carattere!',
            'Cambia articolo'
        ),
        'errors' => array('La data  non &egrave; corretta!',
            'L\'articolo iniziale non pu&ograve; avere un codice successivo a quello finale!',
            'La categoria merceologica iniziale non pu&ograve; avere un codice successivo a quello finale!'
        ),
        'date' => 'Data di stampa ',
        'cm_ini' => 'Categoria merceologica inizio ',
        'art_ini' => 'Articolo inizio ',
        'cm_fin' => 'Categoria merceologica fine ',
        'art_fin' => 'Articolo fine ',
        'listino' => 'Listino',
        'listino_value' => array(0 => 'd\'Acquisto', 1 => ' di Vendita 1', 2 => ' di Vendita 2', 3 => ' di Vendita 3', 4 => ' di Vendita 4', 'web' => ' di Vendita Online'),
        'id_anagra' => 'Fornitore (vuoto per tutti)',
        'ordineStampa' => 'Ordine di Stampa',
        'alternativeOrdineStampa' => array('default',
            'codice articolo',
            'descrizione articolo',
            'categoria articolo'
        ),
        'tipoStampa' => 'Tipo di Stampa',
        'alternativeTipoStampa' => array('espansa', 'compatta', 'verticale'),
      ),
    "admin_booking.php" =>
    array(array("VPR" => "Nuova prenotazione", "VOR" => "Prenotazione diretta", "VOW" => "Prenotazione dal Web", "VOG" => "Ordine settimanale del giorno"),
        'mesg' => array('La ricerca non ha dato risultati!',
            'Inserire almeno 2 caratteri!',
            'Cambia cliente'),
        'title' => 'Prenotazioni',
        " Prenotazione ",
        " piede ",
        " Tira su ",
        " Sezione ",
        " Indirizzo ",
        " Data ",
        " Listino ",
        " Pagamento ",
        " Banca ",
        " Destinazione ",
        " Causale ",
        " magazzino ",
        " vendita ",
        "Vettore",
        "Alloggio",
        "Quantit&agrave;",
        "Tipo",
        "Ricavo",
        "I.V.A.",
        "Codice",
        "Descrizione",
        "U.M.",
        "Prezzo",
        "Sconto",
        "Importo",
        "Imballo",
        "Spedizione",
        "Trasporto",
        "Porto",
        "Inizio trasporto",
        " ore ",
        "Imponibile",
        "Imposta",
        "Tot.Corpo",
        "Peso",
        "Totale",
        "Le date del check-in e/o check-out non sono corrette!",
        "La data del check-out non può essere precedente al check-in",
        "Non ci sono righi per poter emettere il documento!",
        "Stai tentando di modificare il DdT con una data antecedente a quella del DdT con numero precedente!",
        "Stai tentando di modificare il DdT con una data successiva a quella del DdT con numero successivo!",
        "Stai tentando di modificare il documento con una data antecedente a quello dello stesso tipo di documento con numero precedente!",
        "Stai tentando di modificare il documento con una data successiva a quello dello stesso tipo di documento con numero successivo!",
        "La data di emissione non pu&ograve; essere antecedente a quella dell'ultimo DdT emesso!",
        "La data di emissione non pu&ograve; essere antecedente a quella dell'ultimo documento dello stesso tipo emesso!",
        "La data di emissione non &egrave; corretta!",
        "Non hai selezionato il cliente!",
        "Non hai selezionato la modalit&agrave; di pagamento!",
        "Un rigo &egrave; senza la descrizione!",
        "Un rigo &egrave; senza l'unit&agrave; di misura!",
        "Causale mag.",
        "Peso netto",
        "Peso lordo",
        "N.Colli",
        "Volume",
        "Provvigioni",
        "Vuoi modificare un D.d.T. gi&agrave; fatturato!",
        "Questo documento &egrave; gi&agrave; stato contabilizzato!",
        "E stata superata la capienza massima di persone ammesse per l'alloggio",
        "Il numero di adulti è superiore a quello ammesso per l'alloggio",
        "Il numero di minori è superiore a quello ammesso per l'alloggio",
        "Prima di inserire un alloggio è necessario inserire le date di check-in e check-out",
        "ATTENZIONE OVERBOOKING! Il periodo inserito risulta occupato",
        "ATTENZIONE OVERBOOKING! Non c'è sufficiente disponibilità di questo extra",
        "ATTENZIONE Il numero di notti sono inferiori al soggiorno minimo delle impostazioni generali",
        "ATTENZIONE il numero di notti supera il massimo consentito",
        "The tourist tax does not refer to the accommodation. First enter the accommodation and then the tourist tax.",
        'speban' => "Spese incasso",
        'speban_title' => 'Spese incasso non documentate/rate',
        'traspo_title' => 'Spese trasporto non documentate',
        'stamp' => 'Bolli',
        'ritenuta' => 'Ritenuta ',
        'netpay' => 'Netto a pagare',
        'id_agente' => "Agente di vendita",
        'print_total' => "Stampa totale",
        'print_total_value' => array(0 => 'No', 1 => 'Si'),
        'delivery_time' => "Tempi di consegna",
        'day_of_validity' => "Giorni di validità ",
        'vat_constrain' => '(forza) IVA al ',
        'taxstamp' => 'Bollo',
        'virtual_taxstamp' => 'Modo',
        'virtual_taxstamp_value' => array(0 => 'No', 1 => 'Materiale', 2 => 'Virtuale'),
        'typerow_booking' => array(0 => 'Alloggio', 2 => 'Rigo descrittivo'),
        'weight' => 'peso',
        'zero_rows' => 'Il documento non contiene righi di alloggi, compila la ricerca alloggio nella sezione inserimento alloggio, inserisci il valore % per avere una lista completa o per effettuare una ricerca parziale',
        'discount_alert' => 'sconto da anagrafe articoli',
        'last_row' => 'Ultimo rigo inserito',
        'Security deposit to be paid in cash at check-in: EURO',
        'In the absence of damages, the deposit will be returned at check-out',
        'Owner',
        'access1' => '<p>Nous vous envoyons une copie de votre réservation en pièce jointe</p><p>',
        'access2' => 'et les codes d\'accès suivants',
        'booking_number' => 'Numéro de réservation',
        'best_regards' => 'Merci et sincères salutations',
        'on_behalf' => 'Location pour le compte de ',
        'acc_prev' => 'Pour accepter le devis et effectuer votre réservation, utilisez ce lien: ',
        'book_now' => 'RÉSERVER MAINTENANT',
        'access_prev' => '<p>Nous vous envoyons une copie de votre devis en pièce jointe</p>',
        'upd_data' => 'Mise à jour des données',
        'discount_applied' => 'Remise appliquée €'
    ),
    "admin_house.php" =>
      array('title' => 'Gestione degli alloggi',
        'ins_this' => 'Inserimento alloggio',
        'upd_this' => 'Modifica l\'alloggio',
        'err' => array(
            'codice' => 'Il codice alloggio &egrave; gi&agrave; esistente',
            'movmag' => 'Si st&agrave; tentando di modificare il codice alloggio con dei movimenti di magazzino associati',
            'filmim' => 'Il file dev\'essere nel formato PNG, JPG, GIF',
            'filsiz' => 'L\'immagine non dev\'essere pi&ugrave; grande di 64Kb',
            'valcod' => 'Inserire un codice valido',
            'descri' => 'Inserire una descrizione',
            'unimis' => 'Inserire l\'unit&agrave; di misura delle vendite',
            'aliiva' => 'Inserire l\'aliquota I.V.A.',
            'lotmag' => 'Per avere la tracciabilità per lotti è necessario attivare la contabilità di magazzino in configurazione azienda',
            'no_ins' => 'Non sono riuscito ad inserire l\'alloggio sul database',
            'char' => 'Sul codice alloggio ho sostituito i caratteri speciali non consentiti con "_" ',
            'codart_len' => 'Il codice alloggio ha una lunghezza diversa da quella stabilita in configurazione avanzata azienda ',
            'no_web' => 'Per attivare l\'alloggio nell\'e-commerce è necessario che sia inserito il riferimento ID e-commerce nella scheda magazzino'
        ),
        'war' => array(
            'ok_ins' => 'Alloggio inserito con successo'
        ),
        'codice' => "Codice",
        'descri' => "Descrizione",
        'accommodation_type' => "Tipologia di alloggio",
        'accommodation_type_value' => array(3 => 'Apartament', 4 => 'Vacation house', 5=> 'Bed & breakfast', 6=> 'Room', 7=> 'tourist rental'),
        'body_text' => "Testo descrittivo",
        'lot_or_serial' => 'Lotti o numeri seriali',
        'lot_or_serial_value' => array(0 => 'No', 1 => 'Lotti', 2 => 'Seriale/Matricola'),
        'barcode' => "Codice a Barre EAN13",
        'image' => "Immagine (jpg,png,gif) max 64Kb",
        'unimis' => "Unit&agrave; di misura vendite",
        'quality' => "Qualità",
        'larghezza' => "Larghezza (mm)",
        'lunghezza' => "Lunghezza (mm)",
        'spessore' => "Spessore (mm)",
        'bending_moment'=>"Resistenza es.Wx cm³",
        'catmer' => "Categoria merceologica",
        'ragstat' => "Raggruppamento statistico",
        'preacq' => array( 0=>'Costo di produzione', 1=>'Prezzo d\'acquisto', 2=>'Costo di produzione' ),
        'preve1' => 'Prezzo di vendita listino 1',
        'preve2' => 'Prezzo di vendita listino 2',
        'preve3' => 'Prezzo di vendita listino 3',
        'preve4' => 'Prezzo di vendita listino 4',
        'preve1_sc' => 'Prezzo scontato 1',
        'preve2_sc' => 'Prezzo scontato 2',
        'preve3_sc' => 'Prezzo scontato 3',
        'preve4_sc' => 'Prezzo scontato 4',
        'sconto' => 'Sconto',
        'aliiva' => 'Aliquota IVA',
        'retention_tax' => 'Applica la ritenuta d\'acconto',
        'retention_tax_value' => array(0 => 'No', 1 => 'Si'),
        'payroll_tax' => 'Genera rigo Cassa Previdenziale',
        'payroll_tax_value' => array(0 => 'No', 1 => 'Si'),
        'esiste' => 'Esistenza attuale',
        'valore' => 'Valore dell\'esistente',
        'last_cost' => 'Costo dell\'ultimo acquisto',
        'scorta' => 'Scorta minima',
        'riordino' => 'Lotto acquisto',
        'uniacq' => 'Unit&agrave; di misura acquisti',
        'classif_amb' => 'Classificazione ambientale',
        'classif_amb_value' => array(0=>'non classificato',1=>'irritante',2=>'nocivo',3=>'tossico',4=>'molto tossico'),
        'maintenance_period' => 'Periodicità manutenzione (gg)',
        'peso_specifico' => 'Peso specifico (kg/l) o Moltiplicatore',
        'volume_specifico' => 'Volume specifico',
        'pack_units' => 'Pezzi in imballo',
        'codcon' => 'Conto di ricavo su vendite',
        'id_cost' => 'Conto di costo su acquisti',
        'annota' => 'Annotazioni (pubblicate anche sul web)',
        'fornitori-codici' => 'Codici Fornitori',
        'document' => 'Documenti e/o certificazioni',
        'imageweb' => 'immagini e foto',
        'web_mu' => 'Unit&agrave; di misura online',
        'web_price' => 'Prezzo di vendita online',
        'web_multiplier' => 'Moltiplicatore prezzo web',
        'web_public' => 'Sincronizza sul sito web',
        'web_public_value' => array(0 => 'No', 1 => 'Si', 2 => 'Attivo e prestabilito', 3 => 'Attivo e pubblicato in home', 4 => 'Attivo, in home e prestabilito', 5 => 'Disattivato su web'),
        'ordinabile_value' => array( '' => '----','S' => 'Open','N'=> 'Close'),
        'movimentabile' => 'Articolo Movimentabile',
        'movimentabile_value' => array ( '' => '----','S' => 'Si','N'=>'No','E' => 'Esaurito'),
        'codice_fornitore' => 'Codice del produttore',
        'utilizzato' => 'Utilizzato',
        'depli_public' => 'Pubblica sul catalogo',
        'depli_public_value' => array(0 => 'No', 1 => 'Si'),
        'web_url' => 'Web url<br />(es: http://site.com/item.html)',
        'modal_ok_insert' => 'Casa inserita con successo clicca sulla X in alto a destra per uscire oppure...',
        'iterate_invitation' => 'INSERISCI UN\'ALTRA CASA',
        'browse_for_file' => 'Sfoglia',
        'id_anagra' => 'Fornitore di riferimento',
        'last_buys' => 'Ultimi acquisti da fornitori',
        'ordinabile' => 'Accommodation opening',
        'durability_mu' => 'Unità di misura durabilità',
        'durability' => 'Valore durabilità',
        'warranty_days' => 'Giorni di garanzia',
        'id_agent' => 'Proprietario/responsabile',
        'unita_durability' => array('' => '', '>' => '>', '<' => '<', 'H' => 'H', 'D' => 'D', 'M' => 'M'),
        'deposit_type_value' => array(0 => 'a valore', '1' => 'a percentuale sul totale'),
        'mesg' => array('La ricerca non ha dato risultati!',
            'Inserire almeno 1 carattere!',
            'Cambia fornitore'
        )
    ),
	"admin_facility.php" =>
    array('title' => 'Gestione delle strutture turistiche',
        'ins_this' => 'Inserimento struttura turistica',
        'upd_this' => 'Modifica la struttura turistica',
        'err' => array(
            'codice' => 'Il codice alloggio &egrave; gi&agrave; esistente',
            'empty_var' => 'Deve esserci per forza almeno un\'alloggio inserito nella struttura',
            'grcod' => 'Questo alloggio appartiene già ad un\'altra struttura',
            'descri' => 'Inserire una descrizione',
            'no_ins' => 'Non sono riuscito ad inserire l\'aalloggio sul database',
            'char' => 'Sul codice alloggio ho sostituito i caratteri speciali non consentiti con "_" ',
            'codart_len' => 'Il codice alloggio ha una lunghezza diversa da quella stabilita in configurazione avanzata azienda per gli articoli ',
            'filmim' => 'Il file dev\'essere nel formato png, x-png, jpg, gif, x-gif, jpeg',
            'filetoobig' => 'Controllare che il file selezionato non superi le dimensioni impostate nella configurazione php'
        ),
        'war' => array(
            'ok_ins' => 'Alloggio inserito con successo'
		),
		'info' => 'La struttura turistica è qui intesa come un insieme di alloggi presenti nello stesso stabile. <br/>Un esempio classico è un hotel che ha le camere nello stesso edificio.',
		'home' => "ID struttura",
		'variant' => "Alloggi",
		'codice' => "ID struttura",
        'descri' => "Descrizione",
		'image' => 'immagine',
        'web_public' => 'Sincronizza sul sito web',
        'web_public_value' => array(0 => 'No', 1 => 'Si', 2 => 'Attivo e prestabilito', 3 => 'Attivo e pubblicato in home', 4 => 'Attivo, in home e prestabilito', 5 => 'Disattivato su web'),
		'body_text' => 'Descrizione estesa',
        'depli_public' => 'Pubblica sul catalogo',
        'depli_public_value' => array(0 => 'No', 1 => 'Si'),
        'web_url' => 'Web url<br />(es: http://site.com/item.html)',
        'modal_ok_insert' => 'Alloggio inserito con successo clicca sulla X in alto a destra per uscire oppure...',
        'mesg' => array(
        )
    ),
	"banner_search.php" =>
    array('title' => 'Iframe total search',
        'err' => array(
			'date_uguali'=> 'check-in and check-out dates are identical',
			'start>end'=> 'Check-in date is after check-out date'
        ),
        'war' => array(
            'ok' => 'ok riempitura array'
		),
		'guest'=>'Guests',
		'look'=>'Look at',
		'price'=>'Price',
		'search'=>"Search",
		'open_calendar'=>"Open total calendar",
		'imposta'=>"For price or to book, set check-in and check-out date",
		'risultato'=>"Availability for the dates requested",
		'book'=>"Book",
		'nessun_risultato'=>"There is no availability for your requested dates. Try to modify them or look at the total calendar.",
		'for_night' => 'for night',
		'nights' => 'nights',
		'over_guest' => 'Attention: this accommodation is available but it has a max capability of',
		'persons' => 'persons',
		'avviso' => 'The minimum stay is',
		'avviso2' => 'There are increasing discounts for 12, 21 and 28 nights.',
		'over_max_booking' => 'Some accommodations have the maximum limit of ',
		'over_max_booking2' => 'Try to reduce the nights in the request.',
		'no_search_house' => 'The requested accommodation is not available, check availability in your calendar. Or there are these alternatives:',
		'msg_minstay' => 'This accommodation would be available but the minimum stay is',
		'msg_minstay2' => 'nights while you requested only',
		'available' => 'AVAILABLE! Look at it or book it now',
    'alternative' => 'Alternative availability bookable:'
    ),
	"booking_form.php" =>
    array('title' => 'Booking form',
        'err' => array(
			'date_uguali'=> 'Les dates d\'arrivée et de départ sont les mêmes',
			'start>end'=> 'La date d\'arrivée est postérieure à la date de départ',
			'no_payment'=> 'Vous devez sélectionner un mode de paiement',
			'no_ccinfo'=> 'Les données de carte de crédit sont incorrectes ou manquantes',
			'email-error' => 'Les adresses e-mail que vous avez écrites ne sont pas les mêmes',
			'email-validate' => 'L\'adresse e-mail que vous avez écrite est erronée',
			'inexistent_booking' => 'Il n\'y a pas de réservation avec ce numéro',
			'wrong_data' => 'Erreur data',
			'too_many_error' => 'Trop d\'erreurs. Votre accès est bloqué. Veuillez réessayer plus tard',
			'text_missing' => 'Le texte du feedback est manquant ou trop court',
			'err_codfis' => 'Erreur de code fiscal : corrigez-la et réessayez',
			'coupon_error' => 'Le code de réduction n\'est pas appliqué car il n\'est pas valide',
			'cliente_anonimo' => 'Ce devis est destiné à un utilisateur anonyme, vous ne pouvez pas l\'utiliser pour réserver. Demandez un devis avec vos coordonnées ou faites une réservation sur le site Web',
      'accesso_negato' => 'Accès refusé',
      'errore_proforma' => 'ERRORE nella generazione contratto proforma'
        ),
        'war' => array(
            'ok' => 'ok riempitura array',
            'pay_thanks' => 'Grazie, il pagamento è stato inoltrato. Un operatore lo eseguirà quanto prima.'
		),
    'print'=>'Imprimer',
    'minors' => 'Mineurs',
    'adults' => 'Adultes',
    'total_people' => 'Nombre total de personnes',
    'people_number_change' => 'Modifier personnes',
    'request_upd_btn'=>'Demander modification ou annulation',
    'booking_req' => 'Demande de modification de réservation',
    'user' => 'Utilisateur',
    'declaration' => "Je déclare être le titulaire de la réservation et demander irrévocablement sa <strong>modification / annulation / substitution</strong> comme indiqué ci-dessus. Je suis conscient que cette demande a une valeur contraignante conformément à l’art. 1326 du Code civil italien et modifiera le contrat correspondant que j’ai signé à l’époque, et qu’elle peut entraîner des frais ou des pénalités conformément aux clauses contractuelles. Ceci constitue une signature électronique conforme au Règlement (UE) n° 910/2014 eIDAS.",
    'declaration2' => "Dichiaro di essere il titolare della prenotazione e di richiederne irrevocabilmente la <strong> modifica / cancellazione / sostituzione </strong> come sopra indicato. Sono consapevole che tale richiesta ha valore vincolante ai sensi dell'art. 1326 c.c. e modificherà il relativo contratto da me a suo tempo firmato, solo previa approvazione del proprietario, e che può comportare costi o penali come da clausole contrattuali. Questa è una firma elettronica conforme al Regolamento (UE) n. 910/2014 elDAS.",
    'body1' => 'Gentile cliente,<br><br>abbiamo ricevuto la sua richiesta di',
	'body2' => 'pour la réservation ID:',
    'body3' => 'Vous trouverez ci-joint une copie PDF avec les détails.<br><br>Cordialement,<br>',
    'sent_req' => 'Demande envoyée avec succès. Une copie vous a été envoyée à',
    'sent_req2' => 'Un administrateur examinera votre demande dans les plus brefs délais et vous recevrez une notification.',
    'req_title' => 'Demande de modification ou d\'annulation de la réservation n° ',
    'action_req' => 'Action demandée',
    'deleting' => 'Annulation',
    'date_changing' => 'Modification des dates',
    'changement_acc' => 'Remplacement du logement',
    'new_accommodation' => 'Nouveau logement',
		'guest'=>'Clients',
		'rules_label'=>'Le contrat de bail',
		'privacy_label'=>'Lire les règles de confidentialité',
		'rules_button'=>'Contrat de location',
		'privacy_button'=>'Règles de confidentialité',
		'title'=>'Formulaire de réservation',
		'dashboard' => 'Panneau de commande',
		'booking' => 'La réservation',
		'submit'=>'Aller au sommaire',
		'return'=>'Retour',
		'tur_tax' => 'Taxe de séjour',
		'submitpay'=>'Signer le bail et payer',
		'check_submit2' => "Oui, je confirme avoir lu intégralement le contrat, avoir eu la possibilité de le télécharger et/ou de l'imprimer. Je suis conscient que le contrat ne sera contraignant qu'après confirmation par le propriétaire, et que cette confirmation est soumise au paiement immédiat du dépôt de garantie, ce qui constitue une manifestation supplémentaire de l'intention de conclure l'accord. Cette déclaration d'intention constitue une signature électronique conformément à l'article 1326 du Code civil et est conforme au règlement (UE) n° 910/2014 (eIDAS). L'adresse IP, la date et l'heure de la signature sont enregistrées à des fins probatoires.",
		'check_submit' => 'Oui, je confirme avoir lu et accepter pleinement les clauses suivantes : 1,2,3,4,5,6,7.',
		'contractor' => 'L\'Entrepreneur',
		'how_sign' => 'Pour signer, cochez les cases de confirmation',
		'price_for' => 'Prix pour  ',
		'discount_to' => 'Remise à appliquer ',
		'select_guest' => 'Sélectionnez les voyageurs ',
		'max_capability' => 'Capacité maximale ',
		'persons' => ' personne',
		'adults' => 'adultes',
		'children' => 'Enfants jusqu\'à ',
		'price' => 'Prix',
		'each' => 'chaque',
		'per_person' => 'par personne',
		'per_booking' => 'par réservation',
		'per_night' => 'par nuit',
		'per_person_night' => 'Prix par jour et par personne.',
		'out_stock' => 'Non disponible pour cette période',
		'quantity' => 'correcte',
		'per_stay' => 'par séjour',
		'per_night_adult' => 'par nuit et uniquement par adulte',
		'per_person_adult' => 'personne majeure',
		'required' => 'Exigé',
		'read_rules' => 'J\'ai lu et j\'accepte le bail',
		'read_privacy' => 'J\'accepte le traitement des données sensibles',
		'price_sum' => 'Récapitulatif des prix',
		'booking_tot' => 'Prix total de la location',
		'which_deposit' => 'Montant à payer pour confirmer la réservation (acompte de confirmation)',
		'select_pay_deposit' => 'Sélectionnez le type de paiement pour l\'acompte de confirmation',
		'select_pay_balance' => 'Sélectionnez le type de paiement pour votre solde',
		'bank_transfer' => 'Virement bancaire',
		'hype_transfer' => 'Hype Virement',
		'hype_transfer_instruction' => '<b>Effectuez le transfert d\'argent entre Hyper vers le numéro de téléphone suivant dans les 6 heures et envoyez une copie du reçu.</b> Le défaut d\'envoi du reçu entraînera l\'annulation automatique de la réservation.</h4>',
		'credit_card_offline' => 'Carte de crédit hors ligne',
		'payment' => 'Paiement',
		'transfer_instruction' => '<b>Effectuez le virement bancaire aux coordonnées suivantes dans un délai de 6 heures et envoyez une copie du reçu.</b> Le défaut d\'envoi du reçu entraînera l\'annulation automatique de la réservation.',
		'bank_beneficiary' => 'Beneficiary',
		'amount' => 'Amount',
		'bank_reason' => 'Payment Reason:',
		'unsecure_protocol' => '> ATTENTION your connection is not secure, you are in http <',
		'secure_protocol' => 'You are in a secure connection https',
		'amount_pay' => 'Amount to pay',
		'nights' => 'nights',
		'name' => 'Prénom',
		'surname' => 'Nom',
		'address' => 'Adresse',
		'postalcode' => 'Postal code',
		'city' => 'City',
		'provincia' => 'District',
		'nation' => 'Nation',
		'vatcode' => 'Vat code',
		'phone' => 'Telephone',
		'email' => 'E-mail',
		'email2' => 'Just to avoid issue, repeat e-mail',
		'apartment' => 'Apartment',
		'house' => 'House',
		'bandb' => 'Bed & breakfast',
    'room' => 'Room',
		'loc' => 'Tourist rental',
		'for' => 'for',
		'and' => 'and',
		'card_holder' => 'Card holder (prenom et nom)',
		'card_number' => 'Card number',
		'cvv' => 'CVV number (Card Validation Value)',
		'expiry' => 'Expiration',
		'email_confirm_body' => 'Bonjour, <br>merci d\'avoir choisi de passer des vacances dans notre établissement, nous vous envoyons une copie de votre demande de réservation en pièce jointe. Le responsable en a déjà été informé et la réservation sera confirmée dans les plus brefs délais selon les règles de la structure. ',
		'email_confirm_subject' => 'Demande de réservation n.',
		'email_confirm_addbody' => '<p>Dans les 6 heures, vous devez effectuer le paiement de l\'acompte comme suit :</p>',
		'email_confirm_addbody_warning' => '<p>Attention : Le défaut de paiement ou le défaut d\'envoi du reçu entraînera la suppression automatique de la réservation.</p>',
		'email_confirm_addbody_receipt' => '<p>Une fois le paiement effectué, vous devrez envoyer le reçu.</p>',
		'email_confirm_add_access_url' => 'Vous trouverez la réservation sur votre page utilisateur personnelle du site web (tableau de bord), où vous pourrez également ajouter des extras et effectuer des paiements supplémentaires.',
		'email_confirm_add_access_code' => ' et les codes d\'accès suivants: ',
		'regards' => 'Meilleures salutations',
		'of' => 'sur',
		'discount_code' => 'Si vous avez un code de réduction, écrivez-le ici ; vous le verrez à l\'étape suivante',
		'coupon_apply' => 'Coupon de réduction à appliquer',
		'discount_apply' =>'Remise à appliquer',
		'coupon_error' => 'Code de réduction non appliqué car non valide',
		'paypal_payment' => 'Paiement avec PayPal',
		'paypal_cancelled' => 'La transaction PayPal et la demande de réservation ont été annulées',
		'booking_cancell' => 'L\'annulation de réservation',
		'confirm_cancell' => 'Confirmation de l\'annulation de la réservation.',
		'click_to_paypal' => 'Pour procéder au paiement sur PayPal, cliquez sur le bouton',
		'user_access' => 'Accès utilisateur',
		'deposit' => 'Dépôt de confirmation de bail ',
		'balance' => 'Solde',
		'total_amount' => 'Montant total à payer',
		'paypal_cancelled2' => 'La transaction a été annulée',
		'stripe_payment' => 'Paiement par carte de crédit',
		'accommodation' => 'Hébergement',
		'pay_now' => 'Payer maintenant',
		'payment_success' => 'Paiement effectué correctement',
		'payment_failed' => 'Paiement NON réussi, vérifiez votre carte de crédit',
		'payment_info' => 'Informations sur la transaction',
		'back_to_site' => 'Fermer et revenir au site Web',
		'security_deposit_des2' => 'En plus de ce qui précède, à l\'arrivée, vous devrez payer en espèces un dépôt de garantie de',
		'security_deposit_des' => 'À l\'arrivée, vous devrez payer en espèces un dépôt de garantie de',
		'GENERATO' => 'GÉNÉRÉ pour approbation',
		'PENDING' => 'EN ATTENTE',
		'CONFIRMED' => 'CONFIRMÉ et APPROUVÉ',
		'FROZEN' => 'SURGELÉ',
		'ISSUE' => 'Problèmes à résoudre',
		'CANCELLED' => 'ANNULÉ',
		'changement' => 'Changement de statut de la réservation ',
		'no_extra' => 'Aucun supplément acheté',
		'change_status' => 'Le statut de la réservation est passé à',
		'booking_number' => 'Numéro de réservation',
		'deposit_return' => 'S\'il n\'y a pas de dommage, le dépôt de garantie sera restitué au moment du départ',
		'ask_feedback' => 'Merci d\'être notre voyageur, nous espérons que vous avez apprécié votre séjour. <br> Notre objectif est la satisfaction totale de nos clients. Votre avis est grandement apprécié, il vous suffit de prendre quelques minutes et de laisser un avis, s\'il vous plaît.',
		'ask_feedback2' => 'Votre jugement est très important pour nous. <br> En espérant vous revoir bientôt <br> Cordialement',
		'use_access' => 'Pour laisser un avis, vous devez accéder à votre page utilisateur et ouvrir la réservation.',
		'more_info' => 'Plus d\’infos',
		'booking_status' => 'Conditions de réservation',
		'total_paid' => 'Total payé',
		'transfer_instruction2' => '<b>Effectuez le virement bancaire aux coordonnées suivantes et envoyez une copie du reçu à l\'établissement touristique.</b>',
		'add_extra' => 'Ajouter un nouveau supplément',
		'confirm_extra' => 'Confirmer l\'ajout d\'un nouveau supplément',
		'welcome_back' => 'Heureux de vous revoir',
		'point_lev' => 'Votre niveau de fidélité est:',
		'point_saved' => 'Points enregistrés',
		'gain_level' => 'Niveau de fidélité',
		'give_point' => 'Nous vous remercions d\'avoir séjourné dans notre établissement et nous vous informons qu\'ils vous ont été attribués',
		'give_point1' => 'points et que son niveau de fidélité est',
		'delete_point' => 'Nous vous informons qu\'il y a eu une mise à jour et que nous avons été supprimés',
		'feedback_request' => 'Demande de commentaires ',
		'no_level' => 'Pas de niveau',
		'exp_lev' => 'mais les points sont expirés et votre niveau va être supprimé.',
		'upd_data' => 'Mise à jour des informations',
		'email_extra_sbj' =>'Suppléments ajoutés sur la réservation n.',
		'email_extra_body' =>'<p>Veuillez noter que les extras demandés ont été ajoutés à la réservation en question.</p><p>Vous pouvez consulter la mise à jour sur votre page utilisateur. </p>',
		'selfcheck_button' => 'Lire les règles d\'arrivée autonome',
    'self0' => 'Demander de réaliser le SELF-checkin',
    'self1' => 'Self check-in En cours',
    'self2' => 'Self check-in Activé',
    'self3' => 'Self check-in bloqué',
    'self4' => 'Self check-in NON activable',
		'ins_yourData' => 'Entrez vos informations',
		'minor_notice' =>'',
		'title_vote' => 'Votez votre séjour',
		'subtitle_vote' => 'La note positive n\'est que de 5 étoiles. En dessous de 5 étoiles, vous devez indiquer le problème que vous avez rencontré',
		'placeorder_vote' => 'Écrivez ici quel était le problème',
		'write_feedback' => 'Rédigez commentaire',
		'send_feedback' => 'Envoyer le commentaire',
		'vote_sent' => 'Note envoyée',
		'feedback_sent' => 'Commentaire envoyé',
		'your_booking' => 'Vos réservations',
		'number'=>'Numéro',
		'lease'=>'Emplacement',
		'security_deposit'=>'Caution',
		'status'=>'État ',
		'2fa_des'=>'Authentification à 2 facteurs : À chaque connexion, vous recevrez un code d\'activation par e-mail (il est recommandé d\'activer pour plus de sécurité)',
		'sign_by'=>'Contrat signé en ligne par ',
		'sign_ip'=>'. La signature du contrat a été enregistrée avec IP ',
		'in_data'=>' en date du ',
		'alle_ore'=>' à ',
		'cancell_payment' => 'Annuler le paiement',
		'refund' => 'Remboursement',
    'points' => 'Points',
    'missing' => 'Manquant',
    'next_level' => 'pour le niveau suivant',
    'detail_points' => 'Détail des points'
    ),

  "admin_extra.php" =>
    array('title' => 'Gestione degli extra',
		'ins_this' => 'Inserimento nuovo extra',
		'upd_this' => 'Aggiorna questo extra',
		'codice' => 'Codice extra',
		'descri' =>"Descrizione",
		'catmer' => 'Categoria merceologica',
		'body_text' => 'Descrizione estesa',
		'barcode' => 'Codice a barre',
		'image' => 'immagine base',
		'aliiva' => 'aliquota IVA',
		'web_url' => 'Url pagina web corrispondente',
		'web_public' => 'Pubblicazione sito web',
		'document' => 'Documenti e/o certificazioni',
		'imageweb' => 'immagini e foto HQ',
		'web_public_value' => array(0 => 'No', 1 => 'Si', 2 => 'Attivo e prestabilito', 3 => 'Attivo e pubblicato in home', 4 => 'Attivo, in home e prestabilito', 5 => 'Disattivato su web'),
		'web_price' => 'Prezzo anche su web',
		'mod_prezzo' => 'Modalità applicazione prezzo',
		'web_multiplier' => 'Moltiplicatore prezzo web',
		'web_mu' => 'Unità di misura',
		'retention_tax' => 'Applica la ritenuta d\'acconto',
        'retention_tax_value' => array(0 => 'No', 1 => 'Si'),
		'payroll_tax' => 'Genera rigo Cassa Previdenziale',
        'payroll_tax_value' => array(0 => 'No', 1 => 'Si'),
		'codcon' => 'Conto di ricavo su vendite',
        'id_cost' => 'Conto di costo su acquisti',
		'annota' => 'Annotazione',
		'err' => array(
        'valcod' => 'Non hai inserito il codice dell\'extra',
        'descri' => 'Non hai scritto la descrizione',
        'char' => 'Il codice è stato modificato perché conteneva caratteri speciali non ammessi'
		),
		" Extra ",
		"Descrizione",
		"Prezzo",
		"Modalità prezzo",
		"Codice alloggio",
		"5 booo",
		"codice extra",
		"codice alloggio",
		'typerow_price' => array(0 => 'a prenotazione', 1 => 'a persona', 2 => 'a notte', 3 => 'a persona e a notte', 4 => 'cadauno'),
		'mesg' => array('La ricerca non ha dato risultati!',
            'Inserire almeno 1 carattere!',
            'Cambia fornitore'
      )
    ),
    "lease.php" =>
    array('locatore' => 'The landlord',
    'conduttore' => 'the tenant',
    'parti' => 'The parts',
    'e' => 'and ',
    'contratto_n' => 'Tourist lease agreement n.',
    'body1' => 'stipulate the following: ',
    'oggetto' => 'Object',
    'body2' => 'For residential tourist use only, the landlord leases to the tenant who accepts: ',
    'body3' => 'As described on the website at the page ',
    'body4' => 'Any other thing or service not contemplated in the aforementioned internet page or in this contract are to be considered not included in the rent and therefore not provided.',
    'divieti' => 'Prohibitions and obligations',
    'durata' => 'Duration and times',
    'canone' => 'Fee and expenses',
    'rinvio' => 'Referral',
    'rinvio1' =>'Although not expressly provided for in this contract, the parties declare applicable the provisions of the italian civil code and the italian rules of the tourism code, as well as local italian customs.',
    'apartment' => 'Apartament',
		'house' => 'Vacation house',
		'bandb' => 'Bed & breakfast',
    'room' => 'Room',
		'loc' => 'Tourist rental',
    'body5' => 'The lease is granted for a maximum number of ',
    'body6' => ' people, of which ',
    'body7' => ' adults and ',
    'body8' => ' children under years old ',
    'divieto1' => 'It is forbidden the overnight stay, even occasional, of a number of people higher than that agreed.',
    'divieto2' => 'The tenant undertakes to agree with the landlord the expected arrival and departure times at least 12 hours in advance. The tenant undertakes to notify the landlord, during the trip, of any update of the expected arrival time.',
    'divieto3' => 'With the collection of the keys, the tenant accepts and undertakes to become the keeper of the accommodation for the entire duration of the lease. Therefore, we undertake the obligation to keep it with due diligence and not to cause damage to the accommodation, furniture and appliances, not to make any changes to the arrangement of the furniture and objects and not to carry out any repairs except in advance. authorized by the landlord.',
    'divieto7' => 'Any faults or breakages must be immediately reported to the landlord. If faults or breakages are derived from a correct and conscientious use of the property, they will be charged to the landlord, otherwise they will be charged to the tenant. The technical times for repair and / or restoration will be determined from time to time by a competent technician who will be appointed by the landlord. Pending repair, for the non-use of the faulty asset the tenant declares from now on to renounce any type of compensation.',
    'divieto4' => 'It is strictly forbidden to house animals of any species and size.',
    'divieto5' => 'The landlord will deliver the accommodation in a good state of cleanliness and maintenance. The same must be returned in the same state. To this end, the tenant accepts that cleaning during the stay, as well as the final cleaning upon departure, will be his responsibility.',
    'tour_tax' => 'of tourist tax,',
    'durata1' => 'This contract is stipulated for a fixed period, for a maximum duration of nights ',
    'durata2' => 'Arrival (check-in, delivery) is established and accepted by the tenant for the day',
    'durata2bis' => 'and in the time slot',
    'durata3' => 'The departure (check-out, return) is established and accepted by the conductor for the day',
    'durata4' => ' In this moment this lease will cease without any need for notice, which is understood to be given now by then, with the tenant\'s obligation to return the accommodation to the landlord.',
    'durata5' => 'Arrivals or departures outside the established time slot are not allowed.',
    'canone1' => 'The rent of this lease, agreed and accepted by both parties, is',
    'canone2bis' => ' inclusive ',
    'canone2' => ' of expenses for the consumption of electricity, water and gas. The tenant accepts and undertakes to pay the balance of the lease together with the collection of the keys on the day of arrival.',
    'canone3' => 'As a guarantee, at check-in the tenant agrees to have to pay in cash a non-interest-bearing security deposit of',
    'canone4' => 'Once there is no damage and the final cleaning has taken place, this deposit will be returned upon check-out. Otherwise, the amount will be retained by the landlord by way of reimbursement without prejudice to the right to request greater damage even for any non-use of the accommodation.',
    'recesso' => 'Withdrawal',
    'recesso1' => 'The tenant can withdraw from this contract at least 60 days before the date of arrival; in this case the landlord will refund the confirmatory deposit holding back € 50.00 even if due to force majeure and/or unforeseeable circumstances.',
    'recesso2' => 'The tenant can withdraw from this contract between 59 and 31 days before the arrival date; in this case the landlord will reimburse only half of the confirmatory deposit, keeping the remaining half even if due to force majeure and/or unforeseeable circumstances.',
    'recesso3' => 'The tenant can withdraw from this contract in the 30 days preceding the arrival date; in this case the landlord will keep all the confirmatory deposit even if due to force majeure and/or unforeseeable circumstances.',
    'recesso4' => 'The landlord can withdraw from this contract at least 30 days before the arrival date; in this case he will return the confirmation deposit to the landlord.',
    'recesso5' => 'The landlord may withdraw from this contract within 29 days prior to the arrival date. In this case he will return the confirmatory deposit received as well as a further amount of the same amount as compensation and compensation.',
    'recesso6' => 'Upon check-in, the tenant may terminate the lease early but will not be entitled to any refund for unused nights.',
    'recesso7' => 'If due to extraordinary events that would make the accommodation unusable (by way of example only: fire, earthquake, flooding, etc.) the tenant is forced to terminate the lease early, the landlord will refund the amount of the unused nights. No other damage can be claimed from the landlord.',
    'recesso8' => 'Failure by the tenant to comply with even a single point of this contract as well as the non-presentation of the tenant, in the absence of cancellation, on the date of arrival and within the established time slot will result in the express resolution ipso iure of this contract pursuant to of art. 1456 of the Italian Civil Code and the obligation to pay the balance of the lease.',
    'accettazione' => 'Acceptance',
    'accettazione1' => "Il presente contratto è stato letto integralmente scaricato e/o stampato, approvato e sottoscritto on-line con la spunta sulla apposite caselle: privacy, lettura download e stampa del contratto, firma e accettazione clausole vessatorie ai sensi dell'art. 1326 c.c. Pertanto è conforme al Regolamento (UE) n. 910/2014 (eIDAS). L’indirizzo IP, la data e l’ora della sottoscrizione vengono registrati a fini probatori. L'avvenuto pagamento della caparra confirmatoria costituisce una ulteriore manifestazione della volontà di accettazione",
    'accettazione2' => 'Per ogni controversia in ordine all\'esecuzione del presente contratto viene tra le parti convenuta ed accettata la competenza esclusiva del foro di Fermo.',
    'sign-online' => 'Firmato in modalità telematica',
    'sign-clauses' => 'Ai sensi e per gli effetti degli articoli 1341 e 1342 del Codice Civile, il conduttore dichiara di aver preso visione e di aver approvato on-line specificamente le seguenti clausole: 1,2,3,4,5,6,7.',
    'sign' => 'Signed',
    ),
    "review_viewer.php" =>
    array('title' => 'Reviews viewer',
        'err' => array(
			'date_uguali'=> 'Le date di check-in e check-out sono uguali'
        ),
        'war' => array(
          'ok' => 'ok riempitura array'
		),
		'guest'=>'Guests',
    'opinion' => 'Guest rating',
    'average' => 'Average rating',
    'guest_reviews' => 'Guest reviews',
    'no_review' => 'There are no reviews yet',
    'prev' => ' Previous ',
    'next' => ' Next '
    ),
    "self_checkin.php" =>
    array('title' => 'Gestion des self check-in',
        'choose_sex' => 'Sélectionner le sexe',
        'text1' => 'Parfait, les documents ont été téléchargés avec succès !',
        'text2' => 'Vérifie maintenant que tu as payé la caution et le solde de la location. Si le paiement n’est pas effectué, le self check-in ne pourra pas être activé.',
        'text3' => 'Il reste encore à payer € ',
        'text4' => 'Les paiements peuvent toujours être effectués depuis ta page de réservation utilisateur.',
        'text5' => '<p>Un administrateur examinera les informations envoyées. Si tout est complet, tu recevras le code et les instructions pour le self check-in.</p><p><br>En cas de besoin, n’hésite pas à contacter l’établissement.</p>',
        'instr1' => 'Identification du chef de groupe pour le check-in du ',
        'instr2' => 'Prendre un selfie en tenant une pièce d’identité et une note indiquant le check-in.',
        'instr3' => 'La personne sur ce selfie doit être : ',
        'instr4' => '<p>Tu dois prendre une photo (selfie) de toi-même tenant à la fois ta pièce d’identité et un papier avec les mots " Check-in \'<i>date du check-in</i>\' " écrits à la main. La date doit être celle d’arrivée (ex : 13/06/2023).</p><p>Regarde vers la caméra et cadre de tes épaules au sommet de ta tête, comme pour une photo d’identité ; Utilise un fond uni si possible.</p><p>Assure-toi que la lumière vienne de face, pas de l’arrière, afin que ton visage soit clairement visible sans contre-jour ; LA LUMIÈRE NATURELLE EST RECOMMANDÉE.</p><p>Ne porte pas de lunettes de soleil, de chapeaux ou quoi que ce soit couvrant le visage. Si tu portes des lunettes sur ta photo d’identité, porte-les aussi sur le selfie, sinon retire-les.</p><p>La pièce d’identité doit aussi être entièrement et clairement visible sur le selfie : ATTENTION AUX REFLETS.</p>',
        'instr5' => '<p>Tu dois prendre une photo (selfie) de toi-même tenant à la fois ta pièce d’identité et un papier avec les mots " Check-in \'<i>date du check-in</i>\' " écrits à la main. La date doit être celle d’arrivée (ex : 13/06/2023).</p><p>Regarde vers la caméra et cadre de tes épaules au sommet de ta tête, comme pour une photo d’identité ; Utilise un fond uni si possible.</p><p>Assure-toi que la lumière vienne de face, pas de l’arrière, afin que ton visage soit clairement visible sans contre-jour ; LA LUMIÈRE NATURELLE EST RECOMMANDÉE.</p><p>Ne porte pas de lunettes de soleil, de chapeaux ou quoi que ce soit couvrant le visage. Si tu portes des lunettes sur ta photo d’identité, porte-les aussi sur le selfie, sinon retire-les.</p><p>La pièce d’identité doit aussi être entièrement et clairement visible sur le selfie : ATTENTION AUX REFLETS.</p><p>Utilise la caméra frontale (consomme moins de mémoire).</p>',
        'webcam_start' => 'Démarrer la webcam',
        'take_photo' => 'Prendre la photo',
        'go' => 'Continuer',
        'submit' => 'Valider',
        'selfie_success' => 'Selfie envoyé avec succès, merci !',
        'text6' => 'Télécharge les documents d’identité',
        'instr6' => '<h4>Lors du téléchargement de votre pièce d\'identité avec photo, veuillez faire attention à ce qui suit :</h4>
        <li>Assurez-vous que votre document est valide et non expiré ;</li>
        <li>Vérifiez qu\’il ne présente pas de trous ou de modifications empêchant sa lecture ;</li>
        <li>Vous devez télécharger les deux côtés de votre document (recto et verso) ;</li>
        <li>Lorsque vous prenez une photo du document, évitez de couper les coins ou les bords ;</li>
        <li>Assurez-vous que l’ensemble du document est complètement visible et net ;</li>
        <li>Seuls les formats jpg, jpeg, pdf et png sont acceptés.</li>',
        'text7' => '<b>chef de groupe/chef de famille</b>',
        'text8' => 'l\’invité',
        'text9' => 'entrez le nom et le document de',
        'name' => 'Prénom',
        'surname' => 'Nom',
        'load_doc' => 'Télécharger le RECTO de la pièce d\’identité',
        'load_doc_back' => 'Télécharger le VERSO de la pièce d\’identité',
        'text10' => 'entrez le nom et le document du mineur',
        'no_doc' => 'Pas de document',
        'b_place' => 'Lieu de naissance',
        'b_date' => 'Date de naissance',
        'r_place' => 'Lieu de résidence',
        'country' => 'Nationalité',
        'indspe' => 'Adresse',
        'pronas' => 'Province de naissance',
        'counas' => 'Pays de naissance',
        'tip_doc' => 'Type de document',
        'num_doc' => 'Numéro du document',
        'tip_doc_instr' => 'Le document saisi doit être le même que celui que vous présenterez pendant le séjour.',
        'sex' => 'Sexe',
        'male' => 'Homme',
        'female' => 'Femme',
        'like_boss' => 'Comme le chef de groupe',
        'parent_question' => 'Cet invité est-il mineur ? Au moins un parent est-il présent ?',
        'parent_option' => 'Aucune option sélectionnée : veuillez indiquer si un parent est présent',
        'born_missing' => 'Veuillez remplir tous les champs : date de naissance',
        'citizenship' => 'Citoyenneté',
        'coucard' => 'Pays de délivrance du document',
        'coures' => 'ÉTAT DE RÉSIDENCE',
        'loccard' => 'Lieu de délivrance',
        'no_parent' => 'Aucun parent présent',
        'load_aut' => 'Télécharger l’autorisation parentale',
        'id_card' => 'Pièce d’identité de',
        'id_card_instr' => 'Entrez les informations telles qu’elles apparaissent sur le document.',
        'provincia' => 'Province',
        'send' => 'Envoyer',
        'text11' => 'Parfait, les documents ont été téléchargés avec succès !',
        'text12' => '<p>Vérifiez maintenant que vous avez payé la caution et le solde du loyer. Si le paiement n’est pas effectué, le self check-in ne pourra pas être activé.</p>',
        'text13' => 'Montant restant dû € ',
        'text14' => 'Les paiements peuvent toujours être effectués depuis votre page de réservation utilisateur.',
        'text15' => '<p>Un administrateur examinera ce que vous avez envoyé. Si tout est en ordre, vous recevrez le code et les instructions pour le self check-in.</p><p><br>Pour toute question, n’hésitez pas à contacter l’établissement.</p>',
        'text16' => 'Le pré check-in a été effectué. <br>Un administrateur l’examinera et vous notifiera le résultat.',
        'text17' => '<p>Maintenant, si vous le souhaitez, vous pouvez également payer le solde immédiatement, ou à votre arrivée à l\’établissement.</p>',
        'text18' => '<p>Pour les paiements, l\’ajout d’extras éventuels et tout ce qui concerne votre compte, connectez-vous simplement à l’espace utilisateur du site et ouvrez votre réservation.</p>',
        'stay_from' => 'Séjour du',
        'to' => 'au',
        'self_title' => "Demande d'accès autonome (self check-in) au logement",
        'self_intr' => "<li>La procédure de demande de self check-in se déroulera via une webcam, avec laquelle vous devrez prendre un selfie dans le cadre du processus d'identification.</li>
        <li>Ensuite, des documents d'identité valides et non expirés ainsi que leurs copies doivent être fournis pour tous les invités, y compris les nouveau-nés. NOTE IMPORTANTE : la carte de santé/code fiscal n'est PAS une pièce d'identité.</li>
        <li>Pour continuer, vous devez signer l'avenant au contrat de location que vous avez précédemment signé et régler à l'avance tous les paiements : solde du loyer et dépôt de garantie.</li>
        <li>Une fois cela terminé, un administrateur vérifiera l'exactitude et, si positive, autorisera le self check-in.</li>",
        'addendum_title' => "Avenant au contrat de location n",
        'the_undersigned' => "Le soussigné",
        'self_ask' => "demande à pouvoir accéder au logement de manière autonome, car l'heure prévue d'arrivée ne correspond pas à la plage horaire autorisée. Par conséquent, une fois l'autorisation reçue, il/elle s'engage à vérifier le logement au moment de l'accès autonome et à signaler immédiatement, <b>dans les 2 heures</b>, par email/whatsapp/sms avec photos et texte descriptif, tout éventuel problème constaté concernant la propreté ou l'état du bien ; passé ce délai, il/elle accepte et confirme tacitement que l'état du logement est conforme à celui décrit dans le contrat de location, en bon état de propreté et d'entretien et avec tous les équipements et extras convenus.</p>
        <p>Le soussigné accepte que, pour établir l'heure exacte d'accès au logement, le registre généré automatiquement par les dispositifs électroniques utilisés pour l'accès autonome (boîte à clés/serrure électronique) soit utilisé.",
        'self_ask2' => "Enfin, il/elle déclare être le titulaire du contrat de location susmentionné et être conscient(e) que cette demande a une valeur contraignante conformément à l'art. 1326 c.c., uniquement après l'envoi correct des documents et paiements demandés et sous réserve de l'approbation du propriétaire. <br>La présente déclaration d'intention est signée au moyen d'une procédure électronique simple conformément au Règlement (UE) n° 910/2014 (eIDAS). Le signataire a été identifié par une authentification avec accès restreint utilisant des identifiants personnels. Les données relatives à la signature (IP, horodatage, identifiant utilisateur, contenu signé) sont conservées de manière sécurisée à des fins juridiques et probatoires.</label>",
        'check_to_sign' => "Pour confirmer la demande, il est nécessaire de cocher la case ci-dessus. Cette action a valeur d'acceptation contractuelle conformément à l'art. 1326 c.c.",
        'self_gdpr' => "Les données de signature sont conservées de manière sécurisée à des fins juridiques et de suivi, conformément au RGPD.",
        'sign_by'=>'Online signed by',
        'auth_method' =>"authentication method."
    )
);
?>
