<?php
/*
  --------------------------------------------------------------------------
  GAzie - MODULO 'VACATION RENTAL'
  Copyright (C) 2022-present - Antonio Germani, Massignano (AP) - telefono +39 340 50 11 912
  (http://www.programmisitiweb.lacasettabio.it)

  --------------------------------------------------------------------------
  --------------------------------------------------------------------------
  GAzie - Gestione Azienda
  Copyright (C) 2004-present - Antonio De Vincentiis Montesilvano (PE)
  (http://www.devincentiis.it)
  <http://gazie.devincentiis.it>
  --------------------------------------------------------------------------
  Questo programma e` free software;   e` lecito redistribuirlo  e/o
  modificarlo secondo i  termini della Licenza Pubblica Generica GNU
  come e` pubblicata dalla Free Software Foundation; o la versione 2
  della licenza o (a propria scelta) una versione successiva.

  Questo programma  e` distribuito nella speranza  che sia utile, ma
  SENZA   ALCUNA GARANZIA; senza  neppure  la  garanzia implicita di
  NEGOZIABILITA` o di  APPLICABILITA` PER UN  PARTICOLARE SCOPO.  Si
  veda la Licenza Pubblica Generica GNU per avere maggiori dettagli.

  Ognuno dovrebbe avere   ricevuto una copia  della Licenza Pubblica
  Generica GNU insieme a   questo programma; in caso  contrario,  si
  scriva   alla   Free  Software Foundation, 51 Franklin Street,
  Fifth Floor Boston, MA 02110-1335 USA Stati Uniti.
  --------------------------------------------------------------------------
 */

$strScript = array(
    "user_login.php"=>
      array('warning_sess'=>'ATTENTION: Sessions have been disabled in your browser. You must enable or change browsers',
        'login'=>'login',
        'log_instr'=>'Please enter email and password.',
        'forgot'=>'Forgot password?',
        'log_in'=>'Login',
        'required'=>'Required',
        'pw_recover'=>'Password recovery',
        'recover'=>'Recover',
        'wrong_mail'=>'An email has been sent to recover your password. If you did not receive it, it means that you typed the wrong address, or it ended up in the spam folder, or you are not a user.',
        'body_mail_recover'=>'Hi, </br>To set the password click on this link: ',
        'pw_confirm'=>'Confirm password',
        'pw_repeat'=>'Rewrite password as above',
        '2fa_title'=>'Two-factor authentication',
        '2fa_desc'=>'Enter the code that was just sent to you by email (if you have not received it, check the spam folder).',
        '2fa_body_mail'=>'To access your user page use this code: ',
        'wrong_pw'=>'Wrong Password.',
        'too_er'=>'Too many wrong attempts. You\'re stuck!',
        'invalid_keys'=>'Wrong credentials.',
        'invalid_mail'=>'Incorrect email address.',
        'no_user'=>'You were not found in the archive: contact the administrator.',
		'no_json_anagra'=>'You have never entered your password, enter one by clicking on Forgot password or contact the administrator.',
        'no_pw_yet'=>'You haven\'t set your password yet: use password recovery to enter it',
        'reset_success'=>'Password has been set; you can log in with the new password.',
        'dashboard' => 'Dashboard'
      ),
    "browse_document.php" =>
      array('title' => "Lista dei Documenti/Certificati",
        'errors' => array('Il formato del file non è stato accettato!',
        'Il file è troppo grande!',
        'Il file è vuoto!',
        'Nessun file selezionato'),
        'ins_this' => "Inserisci un Documento e/o Certificato",
        'upd_this' => "Modifica Documento e/o Certificato",
        'ins_this_img' => "Inserisci un'immagine",
        'upd_this_img' => "Modifica immagine",
        'item' => "Articolo di riferimento",
        'table_name_ref' => "Tabella di riferimento",
        'note' => "Didascalia/Appunti/Note",
        'ext' => "Estensione",
        'select' => "Sel.",
        'code' => "Codice"),
	"thanks.php" =>
      array('title' => 'Vacation rental thank you page',
        'thanks' => "THANKS!",
        'booked' => "The reservation has been made.",
        'instr_sent' => "The summary with all the information has been sent to the e-mail address provided.<br>",
        'not_received' => "If you have not received the email and have checked your spam folder, contact the site administrator.",
        'close'=>'This message will close in ',
      ),
    "report_facility.php" =>
      array('title' => 'Lista deglle strutture ricettive',
        'codice' => "Codice",
        'descri' => "Descrizione",
        'ricerca' => "Ricerca",
        'good_or_service' => "Merce-Servizio",
        'good_or_service_value' => array(0=>'Merce',1=>'Servizio',2=>'Composizione'),
        'unimis' => "U.M.",
        'catmer' => "Cat. merc.",
        'preacq' => 'Prezzo acquisto',
        'preve1' => 'Prezzo vend.1',
        'stock' => 'Giacenza',
        'aliiva' => 'IVA',
        'retention_tax' => 'Ritenuta',
        'payroll_tax' => 'Cassa Prev.',
        'barcode' => 'Cod.Barre',
        'clone' => 'Duplica',
        'cosear'=>'aggiungi "%" e invia per ricerca, oppure seleziona',
        'clfoco'=>'Fornitore',
        'lot'=>'Lotto'
      ),
	 "report_extra.php" =>
      array('title' => 'Lista degli extra',
        'codice' => "Codice",
        'descri' => "Descrizione",
        'ricerca' => "Ricerca",
        'good_or_service' => "Merce-Servizio",
        'good_or_service_value' => array(0=>'Merce',1=>'Servizio',2=>'Composizione'),
        'unimis' => "U.M.",
        'catmer' => "Cat. merc.",
        'preacq' => 'Prezzo acquisto',
        'preve1' => 'Prezzo vend.1',
        'stock' => 'Giacenza',
        'aliiva' => 'IVA',
        'retention_tax' => 'Ritenuta',
        'payroll_tax' => 'Cassa Prev.',
        'barcode' => 'Cod.Barre',
        'clone' => 'Duplica',
        'cosear'=>'aggiungi "%" e invia per ricerca, oppure seleziona',
        'clfoco'=>'Fornitore',
        'lot'=>'Lotto'
      ),
    "report_accommodation.php" =>
      array('title' => 'Lista degli alloggi',
        'codice' => "Codice",
        'descri' => "Descrizione",
        'ricerca' => "Ricerca",
        'good_or_service' => "Merce-Servizio",
        'good_or_service_value' => array(0=>'Merce',1=>'Servizio',2=>'Composizione'),
        'unimis' => "U.M.",
        'catmer' => "Cat. merc.",
        'preacq' => 'Prezzo acquisto',
        'preve1' => 'Prezzo vend.1',
        'stock' => 'Giacenza',
        'aliiva' => 'IVA',
        'retention_tax' => 'Ritenuta',
        'payroll_tax' => 'Cassa Prev.',
        'barcode' => 'Cod.Barre',
        'clone' => 'Duplica',
        'cosear'=>'aggiungi "%" e invia per ricerca, oppure seleziona',
        'clfoco'=>'Fornitore',
        'lot'=>'Lotto'
      ),
    "report_booking.php" =>
      array("Elenco delle prenotazioni ",
        "codice",
		'number' => 'Numero prenotazione',
		'weekday_repeat' => 'settimanale',
		'status' => 'Stato',
		'print' => 'settimanale',
		'duplicate' => 'Duplica',
		'delete' => 'Cancella',
		'cancel' => 'Elimina',
		'submit' => 'Inserisci',
		'date' => 'data emissione',
    'booking' => 'Booking n.',
    'of' => 'of',
    'email_give_point' => 'With reference to the reservation in question, we inform you that have been attributed',
    'email_give_point2' => 'points with the following motivation:',
    'email_give_point3' => 'Your current balance is',
    'points' => 'points',
		'title_value' => array('VPR' => 'Preventivi a clienti',
        'VOR' => 'Elenco prenotazioni',
        'VOW' => 'Elenco prenotazioni dal web',
        'VOG' => 'Prenotazioni settimanali del giorno'),
		'type' => 'Tipo',
        'type_value' => array('VPR' => 'Preventivo',
        'VOR' => 'Prenotazione',
        'VOW' => 'Prenotazione web',
        'VOG' => 'Prenotazione settimanale del giorno'),
		'mail_alert0' => 'Invio documento con email',
        'mail_alert1' => 'Hai scelto di inviare una e-mail all\'indirizzo: ',
        'mail_alert2' => 'con allegato il seguente documento di vendita:',
		'search' => 'Search',
    'email_selfchek' => 'In reference to your self check-in we inform you that it is: ',
    'email_selfchek_msg' => 'More advise: '
       ),
    "admin_movmag.php" =>
      array("movimento di magazzino ",
        "Data della registrazione ",
        "Causale ",
        "Cliente",
        "Fornitore",
        "C",
        "F",
        "Articolo",
        "Data documento ",
        "Descrizione doc.",
        "Sconto chiusura ",
        "Unit&agrave; di misura ",
        "Quantit&agrave; ",
        "Prezzo",
        "Sconto su rigo",
        "La data del documento non &egrave; corretta!",
        "La data di registrazione non &egrave; corretta!",
        "La data del documento &egrave; successiva a quella di registazione!",
        "Non &egrave; stato selezionato l'articolo!",
        "La quantit&agrave; non pu&ograve; essere uguale a zero!",
        "Questo movimento può essere modificato esclusivamente dal modulo Registro di campagna!",
        "Articolo con lotto",
        "Gli articoli composti possono essere caricati sono con una produzione!",
        "Si può caricare olio lampante da recupero solo se è sfuso!",
        "Non è stato indicato il recipiente di stoccaggio!",
        "Al consumatore finale si può vendere solo olio confezionato!",
        "Manca il codice operazione SIAN!",
        "La cessione omaggio è solo per olio confezionato!",
        "Lo scarico di morchie può avvenire solo da oli NON confezionati!",
        "Nello storno inventario bisogna indicare se carico o scarico",
        "L'inventario di magazzino deve essere un carico",
        "Non si può fare uno storno ad un inventario che non esiste",
        "Nel recipiente di stoccaggio selezionato non c'è sufficiente quantità",
        "La data di registrazione è precedente all'ultimo movimento inviato al SIAN. Se si conferma, questo movimento non sarà inviato al SIAN",
        "Quantità articolo non sufficiente! Se si conferma si creerà una quantità negativa",
        "La somma dei singoli lotti disponibili non corrisponde alla quantità inserita. Se la giacenza è corretta, allora, prima di inventariare, bisognerà aggiustare manualmente i lotti",
        "Non può uscire un lotto in data precedente alla sua creazione",
         'operat' => 'Operazione',
         'operat_value' => array(-1 => "Scarico", 0 => "Non opera", 1 => "Carico"),
        'cod_operaz_value' => array(11=>'',0=>'S0-Vendita olio a consumatore finale',6=>'S6-Cessione omaggio olio confezionato',7=>'S7-Scarico olio destinato ad altri usi',8=>'S8-Scarico olio autoconsumo',12=>'SP-Perdite o cali di olio',13=>'Q-Separazione morchie'),
        'cop_operazione' => 'Codice operazione SIAN',
        'cod_operaz_value_carico' => array(11=>'',10=>'C10-Carico olio lampante da recupero'),
        'partner' => 'Cliente/Fornitore',
        'del_this' => 'Elimina il movimento di magazzino',
        'amount' => " Valore in ",
        ),
    "report_caumag.php" =>
      array("causali di magazzino ",
        "Lista delle "
      ),
    "admin_catmer.php" =>
      array("categoria merceologica ",
        "Numero ",
        "Descrizione ",
        "Immagine (jpg,png,gif) max 64Kb: ",
        "% di ricarico ",
        "Annotazioni ",
        "codice gi&agrave; esistente!",
        "la descrizione &egrave; vuota!",
        "Il file immagine dev'essere nel formato PNG",
        "L'immagine non dev'essere pi&ugrave; grande di 64Kb",
        "Descrizione estesa",
        "ID riferimento e-commerce",
        'web_url' => 'Web url<br />(es: http://site.com/group.html)',
        'top' => 'Bottone su home ecommerce'
      ),
    "admin_ragstat.php" =>
      array("raggruppamento statistico ",
        "Numero ",
        "Descrizione ",
        "Immagine (jpg,png,gif) max 64kb: ",
        "% di ricarico ",
        "Annotazioni ",
        "codice gi&agrave; esistente!",
        "la descrizione &egrave; vuota!",
        "Il file immagine dev'essere nel formato PNG",
        "L'immagine non dev'essere pi&ugrave; grande di 64Kb",
        'web_url' => 'Web url<br />(es: http://site.com/group.html)'
      ),
    "admin_caumag.php" =>
    array("causale di magazzino ",
        "Codice ",
        "Descrizione ",
        "Dati documento ",
        "Operazione",
        "Aggiorna Esistenza",
        "No",
        "Si",
        "Scarico",
        "Non opera",
        "Carico",
        "Cliente/Fornitore",
        "Cliente",
        "Entrambi",
        "Fornitore",
        "codice gi&agrave; esistente!",
        "la descrizione &egrave; vuota!",
        "il codice dev'essere un numero minore di 99"
      ),
    "genera_movmag.php" =>
      array("Genera movimenti di magazzino da documenti",
        "Data inizio ",
        "Data fine",
        "Azienda senza obbligo di magazzino fiscale!",
        " successiva alla ",
        "  righi sono da traferire in magazzino:",
        " Non ci sono righi da trasferire in magazzino!"),
    "select_giomag.php" =>
      array(0 => 'Stampa giornale di magazzino',
        'title' => 'Selezione per la visualizzazione e/o la stampa del giornale di magazzino',
        'errors' => array('La data  non &egrave; corretta!',
            'La data di inizio dei movimenti contabili da stampare non pu&ograve; essere successiva alla data dell\'ultimo !',
            'La data di stampa non pu&ograve; essere precedente a quella dell\'ultimo movimento!'
        ),
        'date' => 'Data di stampa ',
        'date_ini' => 'Data registrazione inizio  ',
        'date_fin' => 'Data registrazione fine ',
        'mode' => 'Tipo di stampa sul pdf',
        'cover' => 'Stampa copertina',
        'subtitle' => 'Titolo aggiuntivo sul pdf (facoltativo)',
        'mode_value' => array(1 => 'Tutti i movimenti', 2 => 'Solo le entrate', 3 => 'Solo le uscite'),
        'price_value' => array(1 => 'con prezzi', 2 => 'senza prezzi con rag.sociale'),
        'header' => array('Data' => '', 'Causale' => '', 'Descrizione documento' => '' ,
          'Articolo' => '', 'Prezzo' => '', 'Importo' => '', 'UM' => '', 'Quantit&agrave;' => ''
          )
      ),
    "recalc_exist_value.php" =>
    array("Rivalutazione esistenza articoli da movimenti di magazzino",
        "Anno di riferimento",
        "Metodo di rivalutazione, scelto in configurazione azienda",
        "Sono stati movimentati i seguenti",
        "articoli durante il ",
        "Movimenti",
        "Codice",
        "Descrizione",
        "Esistenza",
        "UM acq.",
        "Valore precedente",
        "Valore rivalutato",
        "NON RIVALUTATO vedi nota ",
        "(1) perch&egrave; ci sono degli acquisti negli anni successivi al ",
        "(2) perch&egrave; non ci sono movimenti di acquisto nel ",
        "Non ci sono articoli movimentati!"),
    "inventory_stock.php" =>
    array('title' => "Inventario fisico di magazzino",
        'del' => "del",
        'catmer' => "Categoria Merceologica ",
        'select' => "Sel.",
        'code' => "Codice",
        'descri' => "Descrizione articolo",
        'mu' => "U.M.",
        'load' => "Carico",
        'unload' => "Scarico",
        'value' => "Nuovo valore giacenza",
        'v_a' => "Valore attuale",
        'v_r' => "Valore reale",
        'g_a' => "Giacenza attuale",
        'g_r' => "Giacenza reale",
        'g_v' => "Valore giacenza",
        'noitem' => "Non sono stati trovati articoli in questa categoria merceologica",
        'errors' => array(" La giacenza reale non pu&ograve; essere negativa",
        " Il valore reale non pu&ograve; essere negativo o uguale a zero",
        " Si st&agrave; tentando di fare l'inventario con giacenza attuale e reale entrambe a zero",
        " Per questo articolo è già stato fatto l'inventario nello stesso giorno"),
        'preview_title' => 'Confermando le scelte fatte si registreranno i seguenti movimenti di magazzino:'
    ),
    "select_schart.php" =>
      array(0 => 'Stampa schedari di magazzino',
        'title' => 'Selezione per la visualizzazione e/o la stampa delle schede di magazzino',
        'mesg' => array('La ricerca non ha dato risultati!',
            'Inserire almeno 1 carattere!',
            'Cambia articolo'
        ),
        'errors' => array('La data  non &egrave; corretta!',
            'La data di inizio dei movimenti contabili da stampare non pu&ograve; essere successiva alla data dell\'ultimo !',
            'La data di stampa non pu&ograve; essere precedente a quella dell\'ultimo movimento!',
            'L\'articolo iniziale non pu&ograve; avere un codice successivo a quello finale!',
            'La categoria merceologica iniziale non pu&ograve; avere un codice successivo a quello finale!'
        ),
        'date' => 'Data di stampa ',
        'cm_ini' => 'Categoria merceologica inizio ',
        'art_ini' => 'Articolo inizio ',
        'date_ini' => 'Data registrazione inizio  ',
        'cm_fin' => 'Categoria merceologica fine ',
        'art_fin' => 'Articolo fine ',
        'date_fin' => 'Data registrazione fine ',
        'header' => array('Data' => '', 'Causale' => '', 'Magazzino' => '', 'Descrizione<br \>documento' => '',
            'Prezzo' => '', 'UM' => '', 'Quantit&agrave;' => '',
            'Valore<br \>carico' => '', 'Valore<br \> scarico' => '',
            'Quantit&agrave;<br \>giacenza' => '', 'Valore<br \>giacenza' => ''
        ),
        'tot' => 'Consistenza'
      ),
    "stampa_schart.php" =>
      array(0 => 'SCHEDA DI MAGAZZINO dal ', 1 => ' al ',
        'bot' => 'a riportare : ',
        'top' => 'da riporto :  ',
        'item_head' => array('Codice', 'Cat.Merc', 'Descrizione', 'U.M.', 'ScortaMin.'),
        'header' => array('Data', 'Causale', 'Descrizione documento',
            'Prezzo', 'UM', 'Quantita',
            'Val. carico', 'Val. scarico',
            'Q.ta giacenza', 'Val. giacenza'
        ),
        'tot' => 'Consistenza al '
      ),
    "select_deplia.php" =>
      array('title' => 'Selezione per la stampa del catalogo',
        'mesg' => array('La ricerca non ha dato risultati!',
            'Inserire almeno 1 carattere!',
            'Cambia articolo'
        ),
        'errors' => array('La data  non &egrave; corretta!',
            'L\'articolo iniziale non pu&ograve; avere un codice successivo a quello finale!',
            'La categoria merceologica iniziale non pu&ograve; avere un codice successivo a quello finale!'
        ),
        'date' => 'Data di stampa ',
        'cm_ini' => 'Categoria merceologica inizio ',
        'art_ini' => 'Articolo inizio ',
        'cm_fin' => 'Categoria merceologica fine ',
        'art_fin' => 'Articolo fine ',
        'barcode' => 'Stampa',
        'jumpcat' => 'Cambio pagina al cambio categoria',
        'barcode_value' => array(0 => 'Immagini', 1 => 'Codici a Barre'),
        'listino' => 'Listino',
        'listino_value' => array(1 => ' di Vendita 1', 2 => ' di Vendita 2', 3 => ' di Vendita 3', 4 => ' di Vendita 4', 'web' => ' di Vendita Online')
      ),
    "select_listin.php" =>
      array('title' => 'Selezione per la stampa dei listini',
        'mesg' => array('La ricerca non ha dato risultati!',
            'Inserire almeno 1 carattere!',
            'Cambia articolo'
        ),
        'errors' => array('La data  non &egrave; corretta!',
            'L\'articolo iniziale non pu&ograve; avere un codice successivo a quello finale!',
            'La categoria merceologica iniziale non pu&ograve; avere un codice successivo a quello finale!'
        ),
        'date' => 'Data di stampa ',
        'cm_ini' => 'Categoria merceologica inizio ',
        'art_ini' => 'Articolo inizio ',
        'cm_fin' => 'Categoria merceologica fine ',
        'art_fin' => 'Articolo fine ',
        'listino' => 'Listino',
        'listino_value' => array(0 => 'd\'Acquisto', 1 => ' di Vendita 1', 2 => ' di Vendita 2', 3 => ' di Vendita 3', 4 => ' di Vendita 4', 'web' => ' di Vendita Online'),
        'id_anagra' => 'Fornitore (vuoto per tutti)',
        'ordineStampa' => 'Ordine di Stampa',
        'alternativeOrdineStampa' => array('default',
            'codice articolo',
            'descrizione articolo',
            'categoria articolo'
        ),
        'tipoStampa' => 'Tipo di Stampa',
        'alternativeTipoStampa' => array('espansa', 'compatta', 'verticale'),
      ),
    "admin_booking.php" =>
    array(array("VPR" => "Nuova prenotazione", "VOR" => "Prenotazione diretta", "VOW" => "Prenotazione dal Web", "VOG" => "Ordine settimanale del giorno"),
        'mesg' => array('La ricerca non ha dato risultati!',
            'Inserire almeno 2 caratteri!',
            'Cambia cliente'),
        'title' => 'Prenotazioni',
        " Prenotazione ",
        " piede ",
        " Tira su ",
        " Sezione ",
        " Indirizzo ",
        " Data ",
        " Listino ",
        " Pagamento ",
        " Banca ",
        " Destinazione ",
        " Causale ",
        " magazzino ",
        " vendita ",
        "Vettore",
        "Alloggio",
        "Quantit&agrave;",
        "Tipo",
        "Ricavo",
        "I.V.A.",
        "Codice",
        "Descrizione",
        "U.M.",
        "Prezzo",
        "Sconto",
        "Importo",
        "Imballo",
        "Spedizione",
        "Trasporto",
        "Porto",
        "Inizio trasporto",
        " ore ",
        "Imponibile",
        "Imposta",
        "Tot.Corpo",
        "Peso",
        "Totale",
        "Le date del check-in e/o check-out non sono corrette!",
        "La data del check-out non può essere precedente al check-in",
        "Non ci sono righi per poter emettere il documento!",
        "Stai tentando di modificare il DdT con una data antecedente a quella del DdT con numero precedente!",
        "Stai tentando di modificare il DdT con una data successiva a quella del DdT con numero successivo!",
        "Stai tentando di modificare il documento con una data antecedente a quello dello stesso tipo di documento con numero precedente!",
        "Stai tentando di modificare il documento con una data successiva a quello dello stesso tipo di documento con numero successivo!",
        "La data di emissione non pu&ograve; essere antecedente a quella dell'ultimo DdT emesso!",
        "La data di emissione non pu&ograve; essere antecedente a quella dell'ultimo documento dello stesso tipo emesso!",
        "La data di emissione non &egrave; corretta!",
        "Non hai selezionato il cliente!",
        "Non hai selezionato la modalit&agrave; di pagamento!",
        "Un rigo &egrave; senza la descrizione!",
        "Un rigo &egrave; senza l'unit&agrave; di misura!",
        "Causale mag.",
        "Peso netto",
        "Peso lordo",
        "N.Colli",
        "Volume",
        "Provvigioni",
        "Vuoi modificare un D.d.T. gi&agrave; fatturato!",
        "Questo documento &egrave; gi&agrave; stato contabilizzato!",
        "E stata superata la capienza massima di persone ammesse per l'alloggio",
        "Il numero di adulti è superiore a quello ammesso per l'alloggio",
        "Il numero di minori è superiore a quello ammesso per l'alloggio",
        "Prima di inserire un alloggio è necessario inserire le date di check-in e check-out",
        "ATTENZIONE OVERBOOKING! Il periodo inserito risulta occupato",
        "ATTENZIONE OVERBOOKING! Non c'è sufficiente disponibilità di questo extra",
        "ATTENZIONE Il numero di notti sono inferiori al soggiorno minimo delle impostazioni generali",
        "ATTENZIONE il numero di notti supera il massimo consentito",
        "The tourist tax does not refer to the accommodation. First enter the accommodation and then the tourist tax.",
        'speban' => "Spese incasso",
        'speban_title' => 'Spese incasso non documentate/rate',
        'traspo_title' => 'Spese trasporto non documentate',
        'stamp' => 'Bolli',
        'ritenuta' => 'Ritenuta ',
        'netpay' => 'Netto a pagare',
        'id_agente' => "Agente di vendita",
        'print_total' => "Stampa totale",
        'print_total_value' => array(0 => 'No', 1 => 'Si'),
        'delivery_time' => "Tempi di consegna",
        'day_of_validity' => "Giorni di validità ",
        'vat_constrain' => '(forza) IVA al ',
        'taxstamp' => 'Bollo',
        'virtual_taxstamp' => 'Modo',
        'virtual_taxstamp_value' => array(0 => 'No', 1 => 'Materiale', 2 => 'Virtuale'),
        'typerow_booking' => array(0 => 'Alloggio', 2 => 'Rigo descrittivo'),
        'weight' => 'peso',
        'zero_rows' => 'Il documento non contiene righi di alloggi, compila la ricerca alloggio nella sezione inserimento alloggio, inserisci il valore % per avere una lista completa o per effettuare una ricerca parziale',
        'discount_alert' => 'sconto da anagrafe articoli',
        'last_row' => 'Ultimo rigo inserito',
        'Security deposit to be paid in cash at check-in: EURO',
        'In the absence of damages, the deposit will be returned at check-out',
        'Owner',
        'access1' => '<p>We are sending you a copy of your booking as an attachment</p><p>',
        'access2' => 'and the following access codes',
        'booking_number' => 'Booking number',
        'best_regards' => 'Thanks and best regards',
        'on_behalf' => 'Rental on behalf of ',
        'acc_prev' => 'To accept the quote and make your reservation, use this link: ',
        'book_now' => 'BOOK NOW',
        'access_prev' => '<p>We are sending you a copy of your quote as an attachment</p>',
        'upd_data' => 'Data updating',
        'discount_applied' => 'Discount applied €'
    ),
    "admin_house.php" =>
      array('title' => 'Gestione degli alloggi',
        'ins_this' => 'Inserimento alloggio',
        'upd_this' => 'Modifica l\'alloggio',
        'err' => array(
            'codice' => 'Il codice alloggio &egrave; gi&agrave; esistente',
            'movmag' => 'Si st&agrave; tentando di modificare il codice alloggio con dei movimenti di magazzino associati',
            'filmim' => 'Il file dev\'essere nel formato PNG, JPG, GIF',
            'filsiz' => 'L\'immagine non dev\'essere pi&ugrave; grande di 64Kb',
            'valcod' => 'Inserire un codice valido',
            'descri' => 'Inserire una descrizione',
            'unimis' => 'Inserire l\'unit&agrave; di misura delle vendite',
            'aliiva' => 'Inserire l\'aliquota I.V.A.',
            'lotmag' => 'Per avere la tracciabilità per lotti è necessario attivare la contabilità di magazzino in configurazione azienda',
            'no_ins' => 'Non sono riuscito ad inserire l\'alloggio sul database',
            'char' => 'Sul codice alloggio ho sostituito i caratteri speciali non consentiti con "_" ',
            'codart_len' => 'Il codice alloggio ha una lunghezza diversa da quella stabilita in configurazione avanzata azienda ',
            'no_web' => 'Per attivare l\'alloggio nell\'e-commerce è necessario che sia inserito il riferimento ID e-commerce nella scheda magazzino'
        ),
        'war' => array(
            'ok_ins' => 'Alloggio inserito con successo'
        ),
        'codice' => "Codice",
        'descri' => "Descrizione",
        'accommodation_type' => "Tipologia di alloggio",
        'accommodation_type_value' => array(3 => 'Apartament', 4 => 'Vacation house', 5=> 'Bed & breakfast', 6=> 'Room', 7=> 'tourist rental'),
        'body_text' => "Testo descrittivo",
        'lot_or_serial' => 'Lotti o numeri seriali',
        'lot_or_serial_value' => array(0 => 'No', 1 => 'Lotti', 2 => 'Seriale/Matricola'),
        'barcode' => "Codice a Barre EAN13",
        'image' => "Immagine (jpg,png,gif) max 64Kb",
        'unimis' => "Unit&agrave; di misura vendite",
        'quality' => "Qualità",
        'larghezza' => "Larghezza (mm)",
        'lunghezza' => "Lunghezza (mm)",
        'spessore' => "Spessore (mm)",
        'bending_moment'=>"Resistenza es.Wx cm³",
        'catmer' => "Categoria merceologica",
        'ragstat' => "Raggruppamento statistico",
        'preacq' => array( 0=>'Costo di produzione', 1=>'Prezzo d\'acquisto', 2=>'Costo di produzione' ),
        'preve1' => 'Prezzo di vendita listino 1',
        'preve2' => 'Prezzo di vendita listino 2',
        'preve3' => 'Prezzo di vendita listino 3',
        'preve4' => 'Prezzo di vendita listino 4',
        'preve1_sc' => 'Prezzo scontato 1',
        'preve2_sc' => 'Prezzo scontato 2',
        'preve3_sc' => 'Prezzo scontato 3',
        'preve4_sc' => 'Prezzo scontato 4',
        'sconto' => 'Sconto',
        'aliiva' => 'Aliquota IVA',
        'retention_tax' => 'Applica la ritenuta d\'acconto',
        'retention_tax_value' => array(0 => 'No', 1 => 'Si'),
        'payroll_tax' => 'Genera rigo Cassa Previdenziale',
        'payroll_tax_value' => array(0 => 'No', 1 => 'Si'),
        'esiste' => 'Esistenza attuale',
        'valore' => 'Valore dell\'esistente',
        'last_cost' => 'Costo dell\'ultimo acquisto',
        'scorta' => 'Scorta minima',
        'riordino' => 'Lotto acquisto',
        'uniacq' => 'Unit&agrave; di misura acquisti',
        'classif_amb' => 'Classificazione ambientale',
        'classif_amb_value' => array(0=>'non classificato',1=>'irritante',2=>'nocivo',3=>'tossico',4=>'molto tossico'),
        'maintenance_period' => 'Periodicità manutenzione (gg)',
        'peso_specifico' => 'Peso specifico (kg/l) o Moltiplicatore',
        'volume_specifico' => 'Volume specifico',
        'pack_units' => 'Pezzi in imballo',
        'codcon' => 'Conto di ricavo su vendite',
        'id_cost' => 'Conto di costo su acquisti',
        'annota' => 'Annotazioni (pubblicate anche sul web)',
        'fornitori-codici' => 'Codici Fornitori',
        'document' => 'Documenti e/o certificazioni',
        'imageweb' => 'immagini e foto',
        'web_mu' => 'Unit&agrave; di misura online',
        'web_price' => 'Prezzo di vendita online',
        'web_multiplier' => 'Moltiplicatore prezzo web',
        'web_public' => 'Sincronizza sul sito web',
        'web_public_value' => array(0 => 'No', 1 => 'Si', 2 => 'Attivo e prestabilito', 3 => 'Attivo e pubblicato in home', 4 => 'Attivo, in home e prestabilito', 5 => 'Disattivato su web'),
        'ordinabile_value' => array( '' => '----','S' => 'Open','N'=> 'Close'),
        'movimentabile' => 'Articolo Movimentabile',
        'movimentabile_value' => array ( '' => '----','S' => 'Si','N'=>'No','E' => 'Esaurito'),
        'codice_fornitore' => 'Codice del produttore',
        'utilizzato' => 'Utilizzato',
        'depli_public' => 'Pubblica sul catalogo',
        'depli_public_value' => array(0 => 'No', 1 => 'Si'),
        'web_url' => 'Web url<br />(es: http://site.com/item.html)',
        'modal_ok_insert' => 'Casa inserita con successo clicca sulla X in alto a destra per uscire oppure...',
        'iterate_invitation' => 'INSERISCI UN\'ALTRA CASA',
        'browse_for_file' => 'Sfoglia',
        'id_anagra' => 'Fornitore di riferimento',
        'last_buys' => 'Ultimi acquisti da fornitori',
        'ordinabile' => 'Accommodation opening',
        'durability_mu' => 'Unità di misura durabilità',
        'durability' => 'Valore durabilità',
        'warranty_days' => 'Giorni di garanzia',
        'id_agent' => 'Proprietario/responsabile',
        'unita_durability' => array('' => '', '>' => '>', '<' => '<', 'H' => 'H', 'D' => 'D', 'M' => 'M'),
        'deposit_type_value' => array(0 => 'a valore', '1' => 'a percentuale sul totale'),
        'mesg' => array('La ricerca non ha dato risultati!',
            'Inserire almeno 1 carattere!',
            'Cambia fornitore'
        )
    ),
	"admin_facility.php" =>
    array('title' => 'Gestione delle strutture turistiche',
        'ins_this' => 'Inserimento struttura turistica',
        'upd_this' => 'Modifica la struttura turistica',
        'err' => array(
            'codice' => 'Il codice alloggio &egrave; gi&agrave; esistente',
            'empty_var' => 'Deve esserci per forza almeno un\'alloggio inserito nella struttura',
            'grcod' => 'Questo alloggio appartiene già ad un\'altra struttura',
            'descri' => 'Inserire una descrizione',
            'no_ins' => 'Non sono riuscito ad inserire l\'aalloggio sul database',
            'char' => 'Sul codice alloggio ho sostituito i caratteri speciali non consentiti con "_" ',
            'codart_len' => 'Il codice alloggio ha una lunghezza diversa da quella stabilita in configurazione avanzata azienda per gli articoli ',
            'filmim' => 'Il file dev\'essere nel formato png, x-png, jpg, gif, x-gif, jpeg',
            'filetoobig' => 'Controllare che il file selezionato non superi le dimensioni impostate nella configurazione php'
        ),
        'war' => array(
            'ok_ins' => 'Alloggio inserito con successo'
		),
		'info' => 'La struttura turistica è qui intesa come un insieme di alloggi presenti nello stesso stabile. <br/>Un esempio classico è un hotel che ha le camere nello stesso edificio.',
		'home' => "ID struttura",
		'variant' => "Alloggi",
		'codice' => "ID struttura",
        'descri' => "Descrizione",
		'image' => 'immagine',
        'web_public' => 'Sincronizza sul sito web',
        'web_public_value' => array(0 => 'No', 1 => 'Si', 2 => 'Attivo e prestabilito', 3 => 'Attivo e pubblicato in home', 4 => 'Attivo, in home e prestabilito', 5 => 'Disattivato su web'),
		'body_text' => 'Descrizione estesa',
        'depli_public' => 'Pubblica sul catalogo',
        'depli_public_value' => array(0 => 'No', 1 => 'Si'),
        'web_url' => 'Web url<br />(es: http://site.com/item.html)',
        'modal_ok_insert' => 'Alloggio inserito con successo clicca sulla X in alto a destra per uscire oppure...',
        'mesg' => array(
        )
    ),
	"banner_search.php" =>
    array('title' => 'Iframe total search',
        'err' => array(
			'date_uguali'=> 'check-in and check-out dates are identical',
			'start>end'=> 'Check-in date is after check-out date'
        ),
        'war' => array(
            'ok' => 'ok riempitura array'
		),
		'guest'=>'Guests',
		'look'=>'Look at',
		'price'=>'Price',
		'search'=>"Search",
		'open_calendar'=>"Open total calendar",
		'imposta'=>"For price or to book, set check-in and check-out date",
		'risultato'=>"Availability for the dates requested",
		'book'=>"Book",
		'nessun_risultato'=>"There is no availability for your requested dates. Try to modify them or look at the total calendar.",
		'for_night' => 'for night',
		'nights' => 'nights',
		'over_guest' => 'Attention: this accommodation is available but it has a max capability of',
		'persons' => 'persons',
		'avviso' => 'The minimum stay is',
		'avviso2' => 'There are increasing discounts for 12, 21 and 28 nights.',
		'over_max_booking' => 'Some accommodations have the maximum limit of ',
		'over_max_booking2' => 'Try to reduce the nights in the request.',
		'no_search_house' => 'The requested accommodation is not available, check availability in your calendar. Or there are these alternatives:',
		'msg_minstay' => 'This accommodation would be available but the minimum stay is',
		'msg_minstay2' => 'nights while you requested only',
		'available' => 'AVAILABLE! Look at it or book it now',
    'alternative' => 'Alternative availability bookable:'
    ),
	"booking_form.php" =>
    array('title' => 'Booking form',
        'err' => array(
			'date_uguali'=> 'Check-in and check-out dates are the same',
			'start>end'=> 'Check-in date is after check-out date',
			'no_payment'=> 'You have to selecte a payment method',
			'no_ccinfo'=> 'Credit card datas are wrong or missing',
			'email-error' => 'The e-mail addresses you wrote are not the same',
			'email-validate' => 'The e-mail address you wrote ha a wrong form',
			'inexistent_booking' => 'There is no booking with this number',
			'wrong_data' => 'Wrong data',
			'too_many_error' => 'Too many errors. Your access is blocked. Please, try later',
			'text_missing' => 'Feedback text is missing or too short',
			'err_codfis' => 'Tax code error: correct it and try again',
			'coupon_error' => 'Discount code not applied because it is invalid',
			'cliente_anonimo' => 'This quote is for an anonymous user, you cannot use it to book. Request a quote with your details or make a reservation on the website',
      'accesso_negato' => 'Denied access',
      'errore_proforma' => 'ERRORE nella generazione contratto proforma'
        ),
        'war' => array(
            'ok' => 'ok riempitura array',
            'pay_thanks' => 'Grazie, il pagamento è stato inoltrato. Un operatore lo eseguirà quanto prima.'
		),
    'print'=>'Print',
    'minors' => 'Minors',
    'adults' => 'Adults',
    'total_people' => 'Total people',
    'people_number_change' => 'Modify people',
    'request_upd_btn'=>'Request Change or Cancellation',
    'booking_req' => 'Booking modification request',
    'user' => 'User',
    'declaration' => 'I declare that I am the holder of the booking and that I irrevocably request its <strong>modification / cancellation / replacement</strong> as indicated above. I acknowledge that this request is legally binding pursuant to Art. 1326 of the Italian Civil Code and will amend the related contract previously signed by me, and that it may involve costs or penalties as per the contractual clauses. This is an electronic signature in compliance with Regulation (EU) No. 910/2014 eIDAS.',
    'declaration2' => "Dichiaro di essere il titolare della prenotazione e di richiederne irrevocabilmente la <strong> modifica / cancellazione / sostituzione </strong> come sopra indicato. Sono consapevole che tale richiesta ha valore vincolante ai sensi dell'art. 1326 c.c. e modificherà il relativo contratto da me a suo tempo firmato, solo previa approvazione del proprietario, e che può comportare costi o penali come da clausole contrattuali. Questa è una firma elettronica conforme al Regolamento (UE) n. 910/2014 elDAS.",
    'body1' => 'Gentile cliente,<br><br>abbiamo ricevuto la sua richiesta di',
	'body2' => 'for booking ID:',
    'body3' => 'Attached you will find a PDF copy with the details.<br><br>Best regards,<br>',
    'sent_req' => 'Request successfully sent. A copy has been sent to you at',
    'sent_req2' => 'An administrator will review your request as soon as possible, and you will receive a notification.',
    'req_title' => 'Modification or Cancellation Request for Booking No. ',
    'action_req' => 'Action requested',
    'deleting' => 'Cancellation',
    'date_changing' => 'Date modification',
    'changement_acc' => 'Accommodation replacement',
    'new_accommodation' => 'New accommodation',
		'guest'=>'Guests',
		'rules_label'=>'Read the lease agreement',
		'privacy_label'=>'Read the privacy rules',
		'rules_button'=>'Lease agreement',
		'privacy_button'=>'Privacy rules',
		'title'=>'Booking form',
		'booking' => 'Booking',
		'dashboard' => 'Dashboard',
		'submit'=>'Go to summary',
		'return'=>'Back',
		'tur_tax' => 'Turist tax',
		'submitpay'=>'Sign the lease and pay',
		'check_submit2' => "Yes, I confirm that I have fully read the contract, that I had the opportunity to download and/or print it. I am aware that the contract will only be binding upon confirmation by the owner, and that such confirmation is subject to the immediate payment of the deposit, which constitutes an additional manifestation of the intention to conclude the agreement. This declaration of intent constitutes an electronic signature under Article 1326 of the Civil Code and complies with Regulation (EU) No. 910/2014 (eIDAS). The IP address, date, and time of the signature are recorded for evidentiary purposes.",
		'check_submit' => 'Yes, I confirm that I have read and fully accept the following clauses: 1,2,3,4,5,6,7.',
		'contractor' => 'The contractor',
		'how_sign' => 'To sign, tick the confirmation boxes',
		'price_for' => 'Price for ',
		'discount_to' => 'Discount to be applied ',
		'select_guest' => 'Select the guests ',
		'max_capability' => 'Max capability ',
		'persons' => ' persons',
		'adults' => 'adults',
		'children' => 'children up to years old ',
		'price' => 'price',
		'each' => 'each',
		'per_person' => 'per person',
		'per_booking' => 'per booking',
		'per_night' => 'per night',
		'per_person_night' => 'per night and per each person',
		'out_stock' => 'Not available for this period',
		'quantity' => 'quantity',
		'per_stay' => 'per stay',
		'per_night_adult' => 'per night and only per adult',
		'per_person_adult' => 'per adult person',
		'required' => 'required',
		'read_rules' => 'I have read and I accept the lease',
		'read_privacy' => 'I accept the processing of sensitive data',
		'price_sum' => 'Prices summary',
		'booking_tot' => 'Total rental price',
		'which_deposit' => 'Amount to be paid to confirm the reservation (confirmatory deposit)',
		'select_pay_deposit' => 'Select the type of payment for the confirmation deposit',
		'select_pay_balance' => 'Select the payment type for your balance',
		'bank_transfer' => 'Bank transfer',
		'hype_transfer' => 'Hype transfer',
		'hype_transfer_instruction' => '<b>Make the money transfer between Hyper to the following telephone number within 6 hours and send a copy of the receipt.</b> Failure to send the receipt will result in the automatic cancellation of the reservation.</h4>',
		'credit_card_offline' => 'Credit card offline',
		'payment' => 'Payment',
		'transfer_instruction' => '<b>Make the bank transfer to the following coordinates within 6 hours and send a copy of the receipt.</b> Failure to send the receipt will result in the automatic cancellation of the reservation.',
		'bank_beneficiary' => 'Beneficiary',
		'amount' => 'Amount',
		'bank_reason' => 'Payment Reason:',
		'unsecure_protocol' => '> ATTENTION your connection is not secure, you are in http <',
		'secure_protocol' => 'You are in a secure connection https',
		'amount_pay' => 'Amount to pay',
		'nights' => 'nights',
		'name' => 'First name',
		'surname' => 'Surname',
		'address' => 'Address',
		'postalcode' => 'Postal code',
		'city' => 'City',
		'provincia' => 'District',
		'nation' => 'Nation',
		'vatcode' => 'Vat code',
		'phone' => 'Telephone',
		'email' => 'E-mail',
		'email2' => 'Just to avoid issue, repeat e-mail',
		'apartment' => 'Apartment',
		'house' => 'House',
		'bandb' => 'Bed & breakfast',
    'room' => 'Room',
		'loc' => 'Tourist rental',
		'for' => 'for',
		'and' => 'and',
		'card_holder' => 'Card holder (first name and surname)',
		'card_number' => 'Card number',
		'cvv' => 'CVV number (Card Validation Value)',
		'expiry' => 'Scadenza',
		'email_confirm_body' => 'Hi, <br> thank you for choosing to spend a holiday in our facility, we are sending you a copy of your booking request as an attachment. The manager has already been notified about it and the reservation will be confirmed as soon as possible according to the rules of the structure. ',
		'email_confirm_subject' => 'Booking request n.',
		'email_confirm_addbody' => '<p>Within 6 hours, you have to make the payment of the deposit as follows:</p>',
		'email_confirm_addbody_warning' => '<p>Take notice: The failing pay or the failure to send the receipt will delete the booking automatically.</p>',
		'email_confirm_addbody_receipt' => '<p>Once the payment has been made, you will have to send the receipt.</p>',
		'email_confirm_add_access_url' => 'You will find the booking in your personal user page on the website (dashboard), where you can also add extras and make additional payments.',
		'email_confirm_add_access_code' => ' and the following access codes: ',
		'regards' => 'Best regards',
		'of' => 'of',
		'discount_code' => 'If you have a discount code, write it here; you\'ll see it on the next step',
		'coupon_apply' => 'Discount coupon to apply',
		'discount_apply' =>'Discount to apply',
		'coupon_error' => 'Discount code not applied because it is not valid',
		'paypal_payment' => 'Payment with PayPal',
		'paypal_cancelled' => 'The PayPal transaction and the booking request were canceled',
		'booking_cancell' => 'Booking cancellation',
		'confirm_cancell' => 'Confirmation of cancellation of the reservation.',
		'click_to_paypal' => 'To proceed with the payment on PayPal click the button',
		'user_access' => 'User access',
		'deposit' => 'Lease confirmation deposit ',
		'balance' => 'Balance',
		'total_amount' => 'Total amount',
		'paypal_cancelled2' => 'The PayPal transaction was canceled',
		'stripe_payment' => 'Credit Card payment',
		'accommodation' => 'Accommodation',
		'pay_now' => 'Pay now',
		'payment_success' => 'Payment made correctly',
		'payment_failed' => 'Payment NOT successful, check your credit card',
		'payment_info' => 'Transaction data',
		'back_to_site' => 'Close and back to the website',
		'security_deposit_des2' => 'In addition to the above, at check-in you will have to pay cash a security deposit of',
		'security_deposit_des' => 'At check-in you will have to pay cash a security deposit of',
		'GENERATO' => 'GENERATED to approve',
		'PENDING' => 'PENDING',
		'CONFIRMED' => 'CONFIRMED and APPROVED',
		'FROZEN' => 'FROZEN (waiting payment, reserved days)',
		'ISSUE' => 'PROBLEMS to be solved',
		'CANCELLED' => 'CANCELLED',
		'changement' => 'Status change of booking ',
		'no_extra' => 'No extras bought',
		'change_status' => 'The status of the reservation has changed to',
		'booking_number' => 'Booking number',
		'deposit_return' => 'If there is no damage, the security deposit will be returned at check-out',
		'ask_feedback' => 'Thank you for being our guest, we hope you enjoyed your stay. <br> Total satisfaction of our guests is our goal. Your review is greatly appreciated, just take a few minutes and leave a review, please.',
		'ask_feedback2' => 'Your judgment is very important to us. <br> Hoping to see you again soon <br> Sincerely',
		'use_access' => 'To leave a review, you need to log in to your user page and open the booking.',
		'more_info' => 'More info',
		'booking_status' => 'Booking status',
		'total_paid' => 'Total paid',
		'transfer_instruction2' => '<b>Make the bank transfer to the following coordinates and send a copy of the receipt to the tourist facility.</b>',
		'add_extra' => 'Add a new extra',
		'confirm_extra' => 'Confirm add new extra',
		'welcome_back' => 'Welcome back',
		'point_lev' => 'Your fidelity level is:',
		'point_saved' => 'Saved points',
		'gain_level' => 'Fidelity level',
		'give_point' => 'We thank you for staying in our facility and we inform you that they have been attributed to you',
		'give_point1' => 'points and that his fidelity level is',
		'delete_point' => 'We inform you that there has been an update and we have been removed',
		'feedback_request' => 'Feedback request for ',
		'no_level' => 'No level',
		'exp_lev' => 'but the points are expired and your level is going to delete.',
    'upd_data' => 'Update data',
    'email_extra_sbj' =>'Added extras on reservation n.',
    'email_extra_body' =>'<p>Please note that the requested extras have been added to the reservation in question.</p><p>You can view the update on your user page.</p>',
    'selfcheck_button' => 'Read self check-in rules',
    'self0' => 'Request to perform the SELF-checkin',
    'self1' => 'Self check-in In progress',
    'self2' => 'Self check-in Activated',
    'self3' => 'Self check-in Blocked',
    'self4' => 'Self check-in NOT activatable',
    'ins_yourData' => 'Input your data',
    'minor_notice' =>'',
    'title_vote' => 'Vote your stay',
    'subtitle_vote' => 'The positive rating is only 5 stars. Below 5 stars you must indicate what problem you have experienced',
    'placeorder_vote' => 'Write here what the problem was',
    'write_feedback' => 'Write a comment',
    'send_feedback' => 'Submit review',
    'vote_sent' => 'Rating sent',
    'feedback_sent' => 'Comment sent',
    'your_booking' => 'Your bookings',
    'number'=>'Number',
    'lease'=>'Lease',
    'security_deposit'=>'Security deposit',
    'status'=>'Status',
    '2fa_des'=>'2-Factor Authentication: At each log-in you will receive an enabling code by email (It is recommended to enable for greater security)',
    'sign_by'=>'Contract signed online by ',
    'sign_ip'=>'. The contract signature was recorded with IP ',
    'in_data'=>' on  ',
    'alle_ore'=>' at  ',
    'cancell_payment' => 'Cancell payment',
    'refund' => 'Refund',
    'points' => 'Points',
    'missing' => 'Missing',
    'next_level' => 'for the next level',
    'detail_points' => 'Points detail'
    ),

  "admin_extra.php" =>
    array('title' => 'Gestione degli extra',
		'ins_this' => 'Inserimento nuovo extra',
		'upd_this' => 'Aggiorna questo extra',
		'codice' => 'Codice extra',
		'descri' =>"Descrizione",
		'catmer' => 'Categoria merceologica',
		'body_text' => 'Descrizione estesa',
		'barcode' => 'Codice a barre',
		'image' => 'immagine base',
		'aliiva' => 'aliquota IVA',
		'web_url' => 'Url pagina web corrispondente',
		'web_public' => 'Pubblicazione sito web',
		'document' => 'Documenti e/o certificazioni',
		'imageweb' => 'immagini e foto HQ',
		'web_public_value' => array(0 => 'No', 1 => 'Si', 2 => 'Attivo e prestabilito', 3 => 'Attivo e pubblicato in home', 4 => 'Attivo, in home e prestabilito', 5 => 'Disattivato su web'),
		'web_price' => 'Prezzo anche su web',
		'mod_prezzo' => 'Modalità applicazione prezzo',
		'web_multiplier' => 'Moltiplicatore prezzo web',
		'web_mu' => 'Unità di misura',
		'retention_tax' => 'Applica la ritenuta d\'acconto',
        'retention_tax_value' => array(0 => 'No', 1 => 'Si'),
		'payroll_tax' => 'Genera rigo Cassa Previdenziale',
        'payroll_tax_value' => array(0 => 'No', 1 => 'Si'),
		'codcon' => 'Conto di ricavo su vendite',
        'id_cost' => 'Conto di costo su acquisti',
		'annota' => 'Annotazione',
		'err' => array(
        'valcod' => 'Non hai inserito il codice dell\'extra',
        'descri' => 'Non hai scritto la descrizione',
        'char' => 'Il codice è stato modificato perché conteneva caratteri speciali non ammessi'
		),
		" Extra ",
		"Descrizione",
		"Prezzo",
		"Modalità prezzo",
		"Codice alloggio",
		"5 booo",
		"codice extra",
		"codice alloggio",
		'typerow_price' => array(0 => 'a prenotazione', 1 => 'a persona', 2 => 'a notte', 3 => 'a persona e a notte', 4 => 'cadauno'),
		'mesg' => array('La ricerca non ha dato risultati!',
            'Inserire almeno 1 carattere!',
            'Cambia fornitore'
      )
    ),
    "lease.php" =>
    array('locatore' => 'The landlord',
    'conduttore' => 'the tenant',
    'parti' => 'The parts',
    'e' => 'and ',
    'contratto_n' => 'Tourist lease agreement n.',
    'body1' => 'stipulate the following: ',
    'oggetto' => 'Object',
    'body2' => 'For residential tourist use only, the landlord leases to the tenant who accepts: ',
    'body3' => 'As described on the website at the page ',
    'body4' => 'Any other thing or service not contemplated in the aforementioned internet page or in this contract are to be considered not included in the rent and therefore not provided.',
    'divieti' => 'Prohibitions and obligations',
    'durata' => 'Duration and times',
    'canone' => 'Fee and expenses',
    'rinvio' => 'Referral',
    'rinvio1' =>'Although not expressly provided for in this contract, the parties declare applicable the provisions of the italian civil code and the italian rules of the tourism code, as well as local italian customs.',
    'apartment' => 'Apartament',
		'house' => 'Vacation house',
		'bandb' => 'Bed & breakfast',
    'room' => 'Room',
		'loc' => 'Tourist rental',
    'body5' => 'The lease is granted for a maximum number of ',
    'body6' => ' people, of which ',
    'body7' => ' adults and ',
    'body8' => ' children under years old ',
    'divieto1' => 'It is forbidden the overnight stay, even occasional, of a number of people higher than that agreed.',
    'divieto2' => 'The tenant undertakes to agree with the landlord the expected arrival and departure times at least 12 hours in advance. The tenant undertakes to notify the landlord, during the trip, of any update of the expected arrival time.',
    'divieto3' => 'With the collection of the keys, the tenant accepts and undertakes to become the keeper of the accommodation for the entire duration of the lease. Therefore, we undertake the obligation to keep it with due diligence and not to cause damage to the accommodation, furniture and appliances, not to make any changes to the arrangement of the furniture and objects and not to carry out any repairs except in advance. authorized by the landlord.',
    'divieto7' => 'Any faults or breakages must be immediately reported to the landlord. If faults or breakages are derived from a correct and conscientious use of the property, they will be charged to the landlord, otherwise they will be charged to the tenant. The technical times for repair and / or restoration will be determined from time to time by a competent technician who will be appointed by the landlord. Pending repair, for the non-use of the faulty asset the tenant declares from now on to renounce any type of compensation.',
    'divieto4' => 'It is strictly forbidden to house animals of any species and size.',
    'divieto5' => 'The landlord will deliver the accommodation in a good state of cleanliness and maintenance. The same must be returned in the same state. To this end, the tenant accepts that cleaning during the stay, as well as the final cleaning upon departure, will be his responsibility.',
    'tour_tax' => 'of tourist tax,',
    'durata1' => 'This contract is stipulated for a fixed period, for a maximum duration of nights ',
    'durata2' => 'Arrival (check-in, delivery) is established and accepted by the tenant for the day',
    'durata2bis' => 'and in the time slot',
    'durata3' => 'The departure (check-out, return) is established and accepted by the conductor for the day',
    'durata4' => ' In this moment this lease will cease without any need for notice, which is understood to be given now by then, with the tenant\'s obligation to return the accommodation to the landlord.',
    'durata5' => 'Arrivals or departures outside the established time slot are not allowed.',
    'canone1' => 'The rent of this lease, agreed and accepted by both parties, is',
    'canone2bis' => ' inclusive ',
    'canone2' => ' of expenses for the consumption of electricity, water and gas. The tenant accepts and undertakes to pay the balance of the lease together with the collection of the keys on the day of arrival.',
    'canone3' => 'As a guarantee, at check-in the tenant agrees to have to pay in cash a non-interest-bearing security deposit of',
    'canone4' => 'Once there is no damage and the final cleaning has taken place, this deposit will be returned upon check-out. Otherwise, the amount will be retained by the landlord by way of reimbursement without prejudice to the right to request greater damage even for any non-use of the accommodation.',
    'recesso' => 'Withdrawal',
    'recesso1' => 'The tenant can withdraw from this contract at least 60 days before the date of arrival; in this case the landlord will refund the confirmatory deposit holding back € 50.00 even if due to force majeure and/or unforeseeable circumstances.',
    'recesso2' => 'The tenant can withdraw from this contract between 59 and 31 days before the arrival date; in this case the landlord will reimburse only half of the confirmatory deposit, keeping the remaining half even if due to force majeure and/or unforeseeable circumstances.',
    'recesso3' => 'The tenant can withdraw from this contract in the 30 days preceding the arrival date; in this case the landlord will keep all the confirmatory deposit even if due to force majeure and/or unforeseeable circumstances.',
    'recesso4' => 'The landlord can withdraw from this contract at least 30 days before the arrival date; in this case he will return the confirmation deposit to the landlord.',
    'recesso5' => 'The landlord may withdraw from this contract within 29 days prior to the arrival date. In this case he will return the confirmatory deposit received as well as a further amount of the same amount as compensation and compensation.',
    'recesso6' => 'Upon check-in, the tenant may terminate the lease early but will not be entitled to any refund for unused nights.',
    'recesso7' => 'If due to extraordinary events that would make the accommodation unusable (by way of example only: fire, earthquake, flooding, etc.) the tenant is forced to terminate the lease early, the landlord will refund the amount of the unused nights. No other damage can be claimed from the landlord.',
    'recesso8' => 'Failure by the tenant to comply with even a single point of this contract as well as the non-presentation of the tenant, in the absence of cancellation, on the date of arrival and within the established time slot will result in the express resolution ipso iure of this contract pursuant to of art. 1456 of the Italian Civil Code and the obligation to pay the balance of the lease.',
    'accettazione' => 'Acceptance',
   'accettazione1' => "Il presente contratto è stato letto integralmente scaricato e/o stampato, approvato e sottoscritto on-line con la spunta sulla apposite caselle: privacy, lettura download e stampa del contratto, firma e accettazione clausole vessatorie ai sensi dell'art. 1326 c.c. Pertanto è conforme al Regolamento (UE) n. 910/2014 (eIDAS). L’indirizzo IP, la data e l’ora della sottoscrizione vengono registrati a fini probatori. L'avvenuto pagamento della caparra confirmatoria costituisce una ulteriore manifestazione della volontà di accettazione",
    'accettazione2' => 'Per ogni controversia in ordine all\'esecuzione del presente contratto viene tra le parti convenuta ed accettata la competenza esclusiva del foro di Fermo.',
    'sign-online' => 'Firmato in modalità telematica',
    'sign-clauses' => 'Ai sensi e per gli effetti degli articoli 1341 e 1342 del Codice Civile, il conduttore dichiara di aver preso visione e di aver approvato on-line specificamente le seguenti clausole: 1,2,3,4,5,6,7.',
    'sign' => 'Signed',
    ),
    "review_viewer.php" =>
    array('title' => 'Reviews viewer',
        'err' => array(
			'date_uguali'=> 'Le date di check-in e check-out sono uguali'
        ),
        'war' => array(
          'ok' => 'ok riempitura array'
		),
		'guest'=>'Guests',
    'opinion' => 'Guest rating',
    'average' => 'Average rating',
    'guest_reviews' => 'Guest reviews',
    'no_review' => 'There are no reviews yet',
    'prev' => ' Previous ',
    'next' => ' Next '
    ),
    "self_checkin.php" =>
    array('title' => 'Self Check-in Management',
        'choose_sex' => 'choose gender',
        'text1' => 'Perfect, the documents have been successfully uploaded!',
        'text2' => 'Now, make sure you have paid the security deposit and the rental balance. If payment is not made, self check-in cannot be enabled.',
        'text3' => 'There is still an outstanding payment of € ',
        'text4' => 'Payments can always be made from your user booking page.',
        'text5' => '<p>An administrator will review the submission. If everything is complete, you will receive the code and instructions for self check-in.</p><p><br>If needed, do not hesitate to contact the facility.</p>',
        'instr1' => 'Group leader identification for check-in on ',
        'instr2' => 'Take a selfie holding your ID document and a note indicating the check-in.',
        'instr3' => 'The person in this selfie must be: ',
        'instr4' => '<p>You must take a photo (selfie) of yourself holding both your ID document and a piece of paper with the words " Check-in \'<i>check-in date</i>\' " handwritten on it. The check-in date must be the arrival date at the accommodation (e.g.: 13/06/2023).</p><p>Face the camera and frame only from shoulders to top of the head, similar to a passport photo; Use a plain wall as background, if possible.</p><p>Make sure the light is coming from in front of you, not behind you, ensuring your face is clearly visible without backlighting; DAYLIGHT IS RECOMMENDED.</p><p>Do not wear sunglasses, hats, or anything that covers your face. If you wear glasses in your passport photo, wear them in the selfie. If not, remove them.</p><p>The ID document must also be fully and clearly visible in the selfie: BEWARE OF REFLECTIONS.</p>',
        'instr5' => '<p>You must take a photo (selfie) of yourself holding both your ID document and a piece of paper with the words " Check-in \'<i>check-in date</i>\' " handwritten on it. The check-in date must be the arrival date at the accommodation (e.g.: 13/06/2023).</p><p>Face the camera and frame only from shoulders to top of the head, similar to a passport photo; Use a plain wall as background, if possible.</p><p>Make sure the light is coming from in front of you, not behind you, ensuring your face is clearly visible without backlighting; DAYLIGHT IS RECOMMENDED.</p><p>Do not wear sunglasses, hats, or anything that covers your face. If you wear glasses in your passport photo, wear them in the selfie. If not, remove them.</p><p>The ID document must also be fully and clearly visible in the selfie: BEWARE OF REFLECTIONS.</p><p>Use the front camera (uses less memory).</p>',
        'webcam_start' => 'Start webcam',
        'take_photo' => 'Take photo',
        'go' => 'Continue',
        'submit' => 'Submit',
        'selfie_success' => 'Selfie successfully submitted, thank you!',
        'text6' => 'Upload identity documents',
        'instr6' => '<h4>When uploading your photo ID, please pay attention to the following:</h4>
        <li>Make sure your document is valid and not expired;</li>
        <li>Ensure it has no holes or modifications that would prevent it from being read;</li>
        <li>You must upload both sides of your document (front and back);</li>
        <li>When taking a photo of the document, avoid cutting off corners or edges;</li>
        <li>Make sure the entire document is fully visible and in focus;</li>
        <li>Only jpg, jpeg, pdf, and png formats are accepted.</li>
        ',
        'text7' => '<b>group leader/head of household</b>',
        'text8' => 'the guest',
        'text9' => 'enter the name and document of the',
        'name' => 'First Name',
        'surname' => 'Last Name',
        'load_doc' => 'Upload FRONT side of ID document',
        'load_doc_back' => 'Upload BACK side of ID document',
        'text10' => 'enter the name and document of the minor',
        'no_doc' => 'No document available',
        'b_place' => 'Place of birth',
        'b_date' => 'Date of birth',
        'r_place' => 'Place of residence',
        'country' => 'Nationality',
        'indspe' => 'Address',
        'pronas' => 'Province of birth',
        'counas' => 'Country of birth',
        'tip_doc' => 'Document type',
        'num_doc' => 'Document number',
        'tip_doc_instr' => 'The document you provide must be the same one you bring with you during your stay.',
        'sex' => 'Gender',
        'male' => 'Male',
        'female' => 'Female',
        'like_boss' => 'Same as group leader',
        'parent_question' => 'Is this guest a minor? Is at least one parent present?',
        'parent_option' => 'No option selected: please indicate if at least one parent is present',
        'born_missing' => 'Please fill out all required fields: date of birth',
        'citizenship' => 'Citizenship',
        'coucard' => 'Country of document issuance',
        'loccard' => 'Place of issuance',
        'no_parent' => 'No parent present',
        'load_aut' => 'Upload parent’s authorization',
        'id_card' => 'ID document of the',
        'id_card_instr' => 'Enter the information exactly as it appears on the document.',
        'provincia' => 'Province',
        'send' => 'Submit',
        'text11' => 'Perfect, the documents have been uploaded successfully!',
        'text12' => '<p>Now, make sure you have paid the security deposit and the rental balance. If the payment is not completed, self check-in cannot be activated.</p>',
        'text13' => 'You still owe € ',
        'text14' => 'Payments can always be made from your user booking page.',
        'text15' => '<p>An administrator will review the submitted documents. If everything is in order, you will receive the code and instructions for self check-in.</p><p><br>If you need anything, do not hesitate to contact the facility.</p>',
        'text16' => 'Pre check-in has been completed. <br>An administrator will review it and notify you of the result.',
        'text17' => '<p>Now, if you wish, you can also pay the remaining balance immediately, or do it upon arrival at the property.</p>',
        'text18' => '<p>For payments, adding extras, and everything related to your account, simply log in to the user area of the website and open your booking.</p>',
        'stay_from' => 'Stay from',
        'to' => 'to','self_title' => "Request for autonomous access (self check-in) to the accommodation",
        'self_intr' => "<li>The self check-in request procedure will take place through a webcam, with which you will need to take a selfie as part of the identification process.</li>
        <li>Subsequently, valid and non-expired identity documents and copies must be provided for all guests, including newborns. IMPORTANT NOTE: the health card/tax code is NOT an identity document.</li>
        <li>To proceed, you must sign the addendum to the lease contract you previously signed and complete all payments in advance: rental balance and security deposit.</li>
        <li>Once this is completed, an administrator will review the correctness and, if positive, will authorize the self check-in.</li>",
        'addendum_title' => "Addendum to lease contract n",
        'the_undersigned' => "The undersigned",
        'self_ask' => "requests to be able to access the accommodation independently as the expected arrival time does not fall within the permitted time frame. Therefore, once authorization is received, he/she undertakes to check the accommodation at the time of autonomous access and to promptly report, <b>within 2 hours</b>, via email/whatsapp/sms with photos and descriptive text, any possible problems found regarding the cleanliness or condition of the property; after this period, he/she tacitly accepts and confirms that the condition of the accommodation is as described in the lease contract, in good condition of cleanliness and maintenance and with all agreed equipment and extras.</p>
        <p>The undersigned accepts that, in order to establish the exact time of access to the accommodation, the log automatically recorded by the electronic devices used for autonomous access (key box/electronic lock) will be used.",
        'self_ask2' => "Finally, he/she declares to be the holder of the aforementioned lease contract and to be aware that this request has binding value pursuant to art. 1326 c.c., only after the correct submission of the requested documents and payments and subject to the owner's approval. <br>This declaration of intent is signed through a simple electronic procedure pursuant to Regulation (EU) No. 910/2014 (eIDAS). The signatory has been identified by authentication with restricted access using personal credentials. The data relating to the signature (IP, timestamp, user ID, signed content) are securely stored for legal and evidentiary purposes.</label>",
        'check_to_sign' => "To confirm the request, it is necessary to tick the above box. This action has contractual acceptance value pursuant to art. 1326 c.c.",
        'self_gdpr' => "Signature data are securely stored for legal and tracking purposes, in compliance with GDPR.",
        'sign_by'=>'Online signed by',
        'auth_method' =>"authentication method."
    )
);
?>
